### ISSUE TITLE
electroneumd won't sync

### ISSUE THREAD

**Issue by CryptoSiD** [electroneum/electroneum#1]
I'm trying to sync the blockchain with electroneumd but i'm stuck at height 1 (print_height always show 1)

electroneum.log https://pastebin.com/7zHKM8nj

**Comment by santiky** [comment]
Same here using debian stretch. There are peers but without any block.

**Comment by CryptoSiD** [comment]
electroneumd.exe --add-exclusive-node 76.91.14.76:26967 (for linux use ./elctroneumd instead of electroneumd.exe)

Fixed the issue for me, once you added a good peer you can stop and restart the daemon without the --add-exlusive-node, it continue syncing

**Comment by santiky** [comment]
Thank you, works for me too.

**Comment by electroneumRepo** [comment]
If it's not syncing, remove the data directory - For you its `C:\ProgramData\electroneum\`

Then try again.

Can you confirm which operating system this is happening on so I can look into it further.

**Comment by CryptoSiD** [comment]
I tried removing c:\programdata\electroneum\ but it didn't work.
Also disabled firewall, ran as admin.

The issue is that I was only getting "bad" peers (invalid handshake)

As soon as I added a valid peer manually it started syncing

My OS is Windows 10 Pro Version 1709 (Build 16299.64)

**Comment by electroneumRepo** [comment]
Thanks for getting back to me.

Can I ask where you got the IP address for the `valid peer`

It seems a little weird that your daemon failed to connect to any of the seed servers

**Comment by CryptoSiD** [comment]
I asked on the electroneum.space discord (https://discordapp.com/invite/QBmtnsW) for good peers. (sync_info output)

**Comment by electroneumRepo** [comment]
Well glad to hear that you got it sorted :)

I'll now close this issue.

**Comment by rvrsh3ll** [comment]
update check
2017-12-18 12:52:23.888     7fd5831ca700        WARN    net.dns src/common/dns_utils.cpp:487    WARNING: no two valid ElectroneumPulse DNS checkpoint records were received
Error: Problem fetching info -- Error checking for updates

**Comment by gasiferox** [comment]
I´m stuck 13 days before syncing, what should I do to get fully sync?

**Comment by Unyxos** [comment]
Hey, are you using the v0.11.0.0-revert v3 version of the software? If not, that could explain the issue, you can find it on https://GitHub.com/electroneum/electroneum/releases

**Comment by bitkevin** [comment]
may find answer here: https://github.com/electroneum/electroneum/issues/170
