### ISSUE TITLE
net.dns warning

### ISSUE THREAD

**Issue by ryczo** [electroneum/electroneum#10]
Hello when I run electroneumd on my mac there is warning pop up : 2017-11-26 21:44:52.669	[P2P1]	WARN 	net.dns	src/common/dns_utils.cpp:487	WARNING: no two valid ElectroneumPulse DNS checkpoint records were received
I've give them some time to synchronize but nothing happen.
do you have any solve for this ??

**Comment by electroneumRepo** [comment]
> Hello when I run electroneumd on my mac there is warning pop up : 2017-11-26 21:44:52.669	[P2P1]	WARN net.dns	src/common/dns_utils.cpp:487	WARNING: no two valid ElectroneumPulse DNS checkpoint records were received
I've give them some time to synchronize but nothing happen.
do you have any solve for this ??

This is simply a warning. Can you confirm which OS you are using.

Try removing the electroneum data folder (Windows: C:\ProgramData\Electroneum; Mac/Linux: ~/.electroneum), then try running the daemon again.

**Comment by t78Linux** [comment]
@ryczo 
This error message ist perfectly normal, I have it too in Linux. To see what is going on, type during opened electroneumd:  `set_log 2` which shows you a lot more debug info. Revert back to semi-quiet: `set_log 0`
