### ISSUE TITLE
Syncing blockchain error

### ISSUE THREAD

**Issue by JernejV** [electroneum/electroneum#100]
Hi! I was trying to mine some ETN yesterday with my windows laptop - bad idea as obviosly I wasn't well prepared.

I made the wallet, DL the electroneumd.exe cmd prompt miner and started syncing the blockchain. I let it work thru the night but didn't realize I had too low hd space and this led to errors. Stopped it in the morning, but now it seems the synced data is still stored somewhere on my drive as it is still completely clogged.

Can anybody tell me where this synced data (many GB I suppose) should be? I mean directory or file where it is stored. I'd really like to delete it manually. Thanks!

**Comment by smith901** [comment]
Started yesterday also using linux. Had the same space problem. The database is named data.mdb and is 8.6Gb as of this posting.
Try looking in C:\ProgramData\electroneum.

**Comment by ghost** [comment]
Smith is correct. @DeanCole please close
