### ISSUE TITLE
multiple wallets and the wallet-rpc 

### ISSUE THREAD

**Issue by crazy-logic** [electroneum/electroneum#103]
When calling the wallet-RPC in the --wallet-dir mode, so that multiple wallets can be opened. 

1. Can I have more than one wallet open at a time?
2. Is there a way to ensure that one connection to the server doesn't get information from another wallet and vice versa? 

Basically I would like to have multiple wallets open and be abel to read from each of them, but only have one wallet-rpc running on the host. Is this possible?

**Comment by electroneumRepo** [comment]
No, You would need to run a seperate rpc server for each wallet.

The `--wallet-dir` flag is for generating wallets
