### ISSUE TITLE
Daemon / RPC Issues

### ISSUE THREAD

**Issue by delone70** [electroneum/electroneum#104]
Hi, I'm trying to setup a small pool (mainly to understand how it works). I've failed at an early point as I can't even get "electroneum-wallet-rpc.exe" to communicate with "electroneumd.exe" (which is fully synced and running, wallet created locally etc). 

Anybody got example command lines they can share?

**Comment by electroneumRepo** [comment]
Hi,

Firstly, if your going to setup a pool then you need to be running Ubuntu 16.04
Connecting the rpc to the daemon is pretty much automatic. The rpc will try to connect to the daemon on it's local default port.
If your having issues then check your firewall is not blocking the access or it could also be your antivirus if your running one.
Make sure that the daemon and rpc are running on the same machine.
