### ISSUE TITLE
Missing Coins From Official EU-Pool and Miner. (months and not received) 

### ISSUE THREAD

**Issue by JASHIKO** [electroneum/electroneum#105]
I'm currently having a similar problem. I have thousands of missing coins which I mined during the first 2 weeks after launch. I have the transactions that state they have been sent and paid to my wallet address. (the addresses are entered correctly) I was using the official CPU miner and the official eu-mining pool. So far only 650 of several thousand have made it to my offline wallet. I have mined from other sources and those payments have made it to my wallet, so I'm guessing the issue is with the official miner and pool.

Has anyone else had a similar issue? I emailed ETN (raised a ticket) and they said they are aware of the problem and that the coins aren't missing.... That was over a month ago now....... Any suggestions?

**Comment by jpeter12** [comment]
Please contact pool owner to support you with this issue.

**Comment by KhmerRun** [comment]
@JASHIKO Generate new wallet file from your existing viewkey may solve your issue. Mine solved with that.

**Comment by JASHIKO** [comment]
@KhmerRun Thanks Khmer :) That was the first thing I tried. I have 2 wallets and the first one had an issue which was fixed using your method. The second one seems to be a different issue linked to the pool.

**Comment by ghost** [comment]
We can't provide assistance for recovering funds from pools, but just check on your cli wallet that you have done,

set refresh-from-block-height 0
rescan_bc

Many thanks
