### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by jasonpulaski** [electroneum/electroneum#108]
Hi my 'make' is blowing up, any ideas?
[  1%] Built target version
[ 13%] Built target libminiupnpc-static
[ 15%] Built target lmdb
[ 16%] Built target easylogging
[ 33%] Built target obj_cncrypto
[ 33%] Built target cncrypto
[ 37%] Built target epee
[ 48%] Built target obj_common
[ 48%] Built target common
[ 52%] Built target obj_ringct
[ 59%] Built target obj_cryptonote_basic
[ 59%] Built target cryptonote_basic
[ 59%] Built target ringct
[ 62%] Built target blocks
[ 63%] Building CXX object src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o
In file included from /home/ubuntu/boost_1_66_0/boost/asio/impl/write.hpp:25:0,
                 from /home/ubuntu/boost_1_66_0/boost/asio/write.hpp:927,
                 from /home/ubuntu/boost_1_66_0/boost/asio/buffered_write_stream.hpp:29,
                 from /home/ubuntu/boost_1_66_0/boost/asio/buffered_stream.hpp:22,
                 from /home/ubuntu/boost_1_66_0/boost/asio.hpp:41,
                 from /home/ubuntu/electroneum/contrib/epee/include/net/abstract_tcp_server2.h:39,
                 from /home/ubuntu/electroneum/contrib/epee/include/net/levin_server_cp2.h:32,
                 from /home/ubuntu/electroneum/src/p2p/net_node.h:48,
                 from /home/ubuntu/electroneum/src/cryptonote_core/cryptonote_core.cpp:47:
/home/ubuntu/boost_1_66_0/boost/asio/detail/consuming_buffers.hpp: In member function ‘boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepared_buffers_type boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepare(std::size_t)’:
/home/ubuntu/boost_1_66_0/boost/asio/detail/consuming_buffers.hpp:105:50: error: parse error in template argument list
     while (next != end && max_size > 0 && result.count < result.max_buffers)
                                                  ^
make[2]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o] Error 1
make[1]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all] Error 2
make: *** [all] Error 2

**Comment by electroneumRepo** [comment]
Hi,

Could you try `make release-static`
If the issue still persists, it seems like it's the version of boost your running - try an older version.

**Comment by alessiosavi** [comment]
It's a clang compiler bug. You can fix it modyfing the libboost file related to the buffer:
In your case ->
nano home/ubuntu/boost_1_66_0/boost/asio/detail/consuming_buffers.hpp

Press ctrl +W for open search bar -> search for "result.count".
Surround it with ( ).

At the end you have ->  while (next != end && max_size > 0 && (result.count) < result.max_buffers) and the bug is fixed.

In low-end hardware pc you have to reduce the number of threads while compiling
