### ISSUE TITLE
mac error when syncing blockchain

### ISSUE THREAD

**Issue by oaksi** [electroneum/electroneum#109]
Hello! i am very new to this and decided i would give it a go. everything was going fine, hit ~30000 in the sync and started giving me this error.

2018-01-22 16:00:43.234	  0x7fff77f9a310	ERROR	daemon	src/daemon/main.cpp:287	Exception in main! Failed to initialize p2p server.
logout

I have searched through the forum to try find a work around with no prevail. i’ve re installed, and deleted the data file. 

Anyone have advice for me?

**Comment by oaksi** [comment]
Still trying to resolve this with no answers yet.

**Comment by electroneumRepo** [comment]
Are you running under sudo?

Check the permissions on the file - make sure your user is the owner.

If running as a normal user then try sudo

**Comment by oaksi** [comment]
Abort trap: 6
logout

[Process completed]

This is what it shows in the termial.
