### ISSUE TITLE
Block added...

### ISSUE THREAD

**Issue by teodoradr** [electroneum/electroneum#110]
Hi,

I have some problems . I mine Electroneum from my MacBook and in miner appear sometimes Block Added as alternative on height , what this mean . I don't received in my wallet (no offline) the coins .

Thank you .

**Comment by truth3** [comment]
@teodoradr I am no expert, but I believe the log is telling us that a different block is being used than what we have synced with. I don't think its related to you being awarded a block.

For what its worth, I have been CPU mining ETN on my mac for a while now (more than a month) and have not seen any blocks awarded for my efforts. The machine is rather dated, but still has 2.8GHz Intel Core i7
