### ISSUE TITLE
WARN: batch transaction mode already enabled

### ISSUE THREAD

**Issue by prox443** [electroneum/electroneum#111]
Hi,
One of you will have seen this warning ?
Is it blocking for the pool?

`[P2P7]  WARN    blockchain.db.lmdb      src/blockchain_db/lmdb/db_lmdb.cpp:2674 WARNING: batch transaction mode already enabled, but asked to enable batch mode`

**Comment by hakobyanzoro** [comment]
Hi. I've it too and trying to find some info ;)

**Comment by jpeter12** [comment]
Yes... I believe you can safely ignore it. Pools should not have a problem because of this warning.
