### ISSUE TITLE
my. Wallet Manager doesn't warn of split tranactions, doesn't explain failed transactions

### ISSUE THREAD

**Issue by mvpel** [electroneum/electroneum#117]
Each time I attempted to send all but 0.2 ETN of my balance from the Wallet Manager website to my Cryptopia account, based on its assertion that the maximum fee is 0.2, the transaction failed. After a small test transaction, I lowered the amount to leave more ETN left over out of my full balance, and it turns out that the WM assertion that the maximum transaction fee is 0.2 ETN is not actually true.

My successful send transaction was apparently split into four separate transactions, and the total fee is showing as 0.44. This evidently explains why I wasn't able to send the full balance minus 0.2.

The WM should warn of this transaction-splitting possibility and its effect on the total fees, and should provide further information on a failed transaction to allow the user to understand and remedy the situation.

**Comment by ghost** [comment]
Will look into this after the fork. Thanks.
