### ISSUE TITLE
Block 202612 hardcoded hash

### ISSUE THREAD

**Issue by Starmute** [electroneum/electroneum#118]
The measures to hardcode a hash for block 202612 (after the Monero network was attacked on September 4, 2014) were carelessly left in the Electroneum codebase, in /electroneum/blob/master/src/cryptonote_basic/cryptonote_format_utils.cpp. If this code is not removed by the time block 202612 is mined, the entire network will break. Please see [MRL-0002](https://lab.getmonero.org/pubs/MRL-0002.pdf) for a description of the attack which led to this original issue.

There is also an instance of code related to this issue [here](https://github.com/electroneum/electroneum/blob/master/src/blockchain_db/blockchain_db.cpp). It should be removed immediately to keep the network functioning once this block is mined.

**Comment by Dr-Hack** [comment]
Surprisingly , No acknowledgement or feedback from the team ..

**Comment by Starmute** [comment]
I should note that the most serious offender is get_block_longhash, which uses a hardcoded height to set the block hash for 202612. This needs to be fixed at once.

**Comment by Mojo-LB** [comment]
Electroneum Team are more bothered with marketing than tech. If they don't fix it, electroneum will die. 

They already had their share of problems, and something like this can really break them, already the network is at the line of a 51% attack probability, and now this!

Kudos for looking into it, but at the moment I doubt electroneum will react in time. Some of their servers were out of sync for weeks causing many people balance issues. It took them a month to resync some servers, I don't believe they are capable of solving this before the deadline.

I think I will sell my hodlings of ETN, it has been too much drama for a single coin.

**Comment by nightvision04** [comment]
Thanks Starmute. Would you be available to to guide the team a bit in case they need assistance with a fork? I know that it's in the best interest of the team to fix this (since their coins are locked), and they might need to lean on your competency a bit.

**Comment by Starmute** [comment]
nightvision04, I would be happy to help if necessary, but I suspect that they will not ask for my help with this.

**Comment by Starmute** [comment]
@XzenTorXz, good work. Hope they implement it in a timely manner.

**Comment by Mojo-LB** [comment]
They replied on twitter.

@electroneumRepo What about the probability of 51% Attack after nanopool gets that percentage?

**Comment by Starmute** [comment]
@Mojo-LB I'm outraged at their response. They decided it was a good idea to attack me because I saved their project.

**Comment by Mojo-LB** [comment]
@Starmute I actually didn't expect any better of them. Though I'm not really sure how to feel about it. I already sold a big part of my ETN holdings, and Stopped my ETN Pool and asked my miners to mine Graft. At least Graft team are involved in the technology and actually respond to issues.

I lost hope on Electroneum when they started deleting unfavorable comments on Twitter and Facebook. That only shows they try to sell illusion, not actual value of any kind.

**Comment by schmeckles22** [comment]
How hard is it to have a team that replies to this sort of thing? It's pretty basic for any company that hosts anything computer related

**Comment by Starmute** [comment]
@schmeckles22 They did reply to it -- by nebulously attacking me and @XzenTorXz, who helped to patch the bug. We were not thanked for our efforts or even acknowledged.

**Comment by schmeckles22** [comment]
They've made it very difficult to find the answers though.

**Comment by Starmute** [comment]
I am KOP2 on the Electroneum telegram, since someone asked for proof.

**Comment by hvnscnt** [comment]
...we have noticed the negative speculation and misinformation being pushed out regarding Monero Block 202162, and the subsequent patch code. This is a very simple 2 line fix, one that we are aware of - as a number of Community Devs have already confirmed. https://www.facebook.com/electroneum/posts/1950027555259213

**Comment by electroneumRepo** [comment]
@Starmute @XzenTorXz Could we ask you both to send us an email to support@electroneum.com with the subject "Block 202612 hardcoded hash" - This is so that we can discuss the issue with you and thank you both for your work.

Regards
Electroneum

**Comment by Mojo-LB** [comment]
@electroneumRepo Seriously though? After publicly slandering them?
And what about the issues regarding nearing 51% hashrate control and possibility of attack? Silence as well?

**Comment by electroneumRepo** [comment]
@Starmute @XzenTorXz hi, I really want to clear this up! 

I am very grateful for your input and ALL the positive community input. It's incredible. I've just re-read the Facebook post that you think is attacking you, and I can understand that it can be read that way - but I completely assure you that is NOT the case. In the section of that post where Taylor states "We are forever grateful for the support and patience shown by our community" - that's about you guys - the guys at the coalface of Electroneum - making it work and making it awesome. Then when he states "we have noticed the negative speculation and misinformation being pushed out regarding Monero Block 202162" he is talking about a very hard effort by a number of individuals on Telegram and other social media sites that were using this information to attack Electroneum. I promise you faithfully that this statement was not about you in any way. 

I am personally grateful for what you are adding to the community and I'll make sure that all correspondence is run past me before it gets released on our Facebook page to try and prevent this kind of thing from happening in the future.

Best Regards,
Richard Ells.
CEO / Founder of Electroneum.

**Comment by XzenTorXz** [comment]
since i allready wrote an email to "support@" i just gonna repost it here:

I'm not very happy about the whole situation and how you handled it. You basicly accused a user (starmute) in public about spreading misinformation and you can interpret a lot more into it with the paragraph you wrote before. This is a serious hit against the open source community. You should be happy and thankful that there are people out there, who take a look in your code and publish the issues and dont expect anything in return. He never had to take a look, he never had to publish it. I expect an apology to him. He has to take a lot of shit from the community at the moment, because they lost a few $, but still better then having a non-working blockchain.

Yes the community was a bit worried and since there was no official statment, i decided to create a little fix to calm them down. We did a lot of informing over the issue on discord and explained what it is all about and what needs to be done. There was no missinformation, we calmed the people who thought all is over and explained more who thought this isnt a deal at all. You have a big community, you should treat them the right way, because they're the most valuable product you have.

sincerely
XzenTorXz

**Comment by Mojo-LB** [comment]
Dear Mr. Ells @electroneumRepo  , @Starmute, and @XzenTorXz,

I think we can either keep a conversation going back and forth here, or settle this publicly as it was created publicly.

Mr. Richard, you are the marketing genius here, and I assume you are already preparing/prepared a plan to undo the damage that have been accidentally done.

As the community of Electroneum, we feel concerned about the stagnation and delays. You guys talk about 27 days since you went online, but we are on our nerves since November. That, combined with both hype, fear, and some tiny trigger, can (and already did) cause turbulence.

Honestly, we want to see actions both in terms of technology AND business. And yet (I know it's more complex than that, but not "1 month with your budget" complex) resync of some servers and implementing accurate checks took way too long to be done. 

I guess the most frustrating part is the feeling that our voices and concerns are not being heard, except when they are blown out of proportion.

Regards,
Mojo from Lebanon.

**Comment by Starmute** [comment]
The following email was sent to support@electroneum.com on January 29. 2018 at 8:08AM EST:

Hello Electroneum,

I’m Starmute from the GitHub, and will prove this by posting on the GitHub the exact timestamp of the email sent to you.

I was dismayed at the response to my discovery of the block-202612 bug. When I disclosed it, I expected to be at least thanked by your team and your community. This was a small bug, and an easy to fix one, yet it held the potential to stop the entire Electroneum network in its tracks. I reported it with the intention of helping your community, and receiving your thanks in return.

Instead I was met with rage, anger and threats from angry investors who had lost money, and your Facebook update piled on to that. What you posted was interpreted by many as an accusation, against myself, of spreading misinformation, and my discovery of a fatal flaw in your code was not rewarded, not thanked, not even acknowledged. All that myself and XzenTorXz got was a vague reference to the “community devs” who “confirmed that it is a 2 line fix.”

When I asked, on your Telegram group, to speak to an Electroneum team member, simply saying that I had discovered the block-202612 bug, I was immediately banned by David Payton, an administrator in the Electroneum group. 

You have created a community and an environment that, rather than rewarding and thanking those who work to keep it alive, slanders us and screams “FUD!!!”. This type of attitude is dangerous and self-destructive, and if you allow it to continue, your community will shrink in turn.

I never had to publish the bug. There are a vast number of ways I could have profited by keeping it a secret. I published it because I wanted to keep Electroneum alive, and because I expected the gratitude of the community to be its own reward. Instead, your community and team decided to shoot the messenger.

You should be rewarding people who help you the way I have.

Sincerely,

Starmute/KnifeOfPi2

**Comment by mattcode55** [comment]
Poor @Starmute  :(

Should have just left ETN to die.

**Comment by bet0x** [comment]
They want to keep the shame in private? Why is that hard just to say "sorry" and continue.

**Comment by ra-dave** [comment]
Guys this is an issue tracker, not a general forum.  Stop posting completely irrelevant stuff.

**Comment by JoelIsMe** [comment]
Release an updated binary file to github. Also, please send the binary to cryptopia before september 2032. 
The version 1.0 of the released files hosted here will crash the blockchain in 37 days.

**Comment by JoelIsMe** [comment]
Also the 4 pools and big mining farms with private pools that actually mine the coin have to update their software too for the chain to continue.

Every electroneum-daemon has to be updated to the new code that is NOT released as a binary file as of now.

**Comment by kevin39** [comment]
Stay calm, you're boring everyone. There is no "big" emergency, they'll fix it soon.

**Comment by JoelIsMe** [comment]
@kevin39 the market loves to dump when a coin is guaranteed to fail in 37 days from now.
there is no binary release available with the fixed code and cryptopia has to install that program.

when i'll see an updated .exe file here on this github, I'll say I'm calm.

**Comment by rizwansarwar** [comment]
Isn't it the same problem for everyone? If ETN forks due this or some other reason, why would people invest in new fork? And if the update/patch/fix solves the issue, why would you need to fork? A fix before the imminent bug will be as if an update to wallet has been issued. I am struggling to see the logic, why would ETN deliberately allow the bug to be hit and create a fork? Surely if there is a solution (as posted above), they would accept it, what am I missing?

**Comment by XzenTorXz** [comment]
there is no hardfork needed, you could call it softfork or just call it update. Every node needs to update (else they will stop working on the height of 202612), thats about it. But you still need to anounce the update (so everyone has some time) and its very critical that its announced loud and quick.

**Comment by ghost** [comment]
Hello Everyone and @Starmute @XzenTorXz @electroneumRepo

I am running a mine pool software of my own making - that is dependent on electroneumd.

Do I have to update electroneumd for this bug? I have read the entire thread, but it was not entirely clear to me, it appears there is a fix, but do we have to re-download and re-compile the electroneumd?

Best regards,
C.

**Comment by schmeckles22** [comment]
@cambazz if they've released a fix you will have to recompile electroneumd

**Comment by Carolusian** [comment]
@electroneumRepo Any updates on the issue, by the way, the maintenance of this repo is too inactive...

**Comment by Starmute** [comment]
Richard Ells has still not responded to my second email after 24 hours.

**Comment by Starmute** [comment]
@cambazz - yes, you will need to recompile electroneumd once the patch is released.

**Comment by bobbieltd** [comment]
Electroneum team shoud be more clear about this. A concrete plan. I'm a pool owner. With the fix, after Electroneum recompilation, will I have to resync daemon (electroneumd) ?

**Comment by XzenTorXz** [comment]
no you dont need to resync the blockchain, everything should work fine, when the patch is applied

**Comment by stilkus** [comment]
Hey, how did Monero fix this Block, I never heard they hard-forked their blockchain, so how exactly was it done ?

**Comment by XzenTorXz** [comment]
no, they are the ones who needed this block, because of another bug. Thats why its still in the monero code and always will be there.

**Comment by stilkus** [comment]
still, how could it be fixed ? is it a big issue that will involve forking the chain or just a simple code line like I've seen on FB ?

**Comment by Mojo-LB** [comment]
Guys, here is not the correct venue for this discussion, let's create a reddit post and move it there.

Regarding guys asking for updates, such things on this scale can't be done overnight, even though the code is ready. Electroneum themselves have hundreds of servers,exchanges/upcoming exchanges have several nodes operational, pools also have nodes. 

Any kind of update to something this big must be checked and double checked several times, and must pass a lot of quality control before going live.

No fork will take place, just a patch. an update.

Please guys let's continue this on reddit.

**Comment by nightvision04** [comment]
I don't have enough reddit karma. xD Someone post a link and we will continue there.

**Comment by XzenTorXz** [comment]
Further discussion:
https://www.reddit.com/r/Electroneum/comments/7u50iy/here_you_can_ask_question_of_the_upcomming_patch/

**Comment by electroneumRepo** [comment]
Hi,
We have a update coming on that will be rolled Monday 5th Feb that will include the required fix for this block issue and a number of other fixes and enhancements. We have a number of pools and exchanges that we will contact directly to ensure they are using the updated code and we will make an announcement to ensure the update is in place where required by the March deadline.
Thanks everyone - the input from the community on this has been amazing, and we really appreciate all the effort by everyone involved.

**Comment by TheQuantumPhysicist** [comment]
@electroneumRepo Please post the branch/pull request with the changes publicly so that we can review it. We're your people! We want to help you get this right :-)

**Comment by jeffreyscholz** [comment]
I'll also leave a reference to https://github.com/electroneum/electroneum/pull/120 here

**Comment by Carolusian** [comment]
@electroneumRepo It is great to hear about that, and it is really appreciated about your efforts. One suggestion is that, we would love to see the electroneum base chain keep opensourced and keep maintained actively.  Active maintenance of the whole chain in a technological transparent way will help give more confidence to the community. Thanks again @Starmute and @XzenTorXz

**Comment by XzenTorXz** [comment]
they have to publish their source commint on github. Else the source and the binaries wouldnt be in sync.

**Comment by infiniteC001** [comment]
Will I have to manually update my daemon or will it grab the new update automatically once it is published?

**Comment by Starmute** [comment]
@infiniteC001 You will need to manually update electroneumd

**Comment by electroneumRepo** [comment]
Hi All, Please use the latest version of our code in all nodes and use cases. This fixes this issue regarding block 202612. We've also merged various improvements and bug fixes from Monero's v0.11.1.0.
In a similar way to Monero's regular updates we have introduced a fork at height 179840.

All users must update their code before that block to remain in sync.

We have notified major pools and exchanges already.

Thanks for all your help and feedback.

Electroneum Team.

**Comment by Starmute** [comment]
@electroneumRepo,

I sent you an email one week ago, but you still have not responded. Please send me a response as soon as you can.

Thanks,
Starmute/KnifeOfPi2

**Comment by mannie65** [comment]
@electroneumRepo - It's great that you updated the major pools, but how about the other pool owners. Can you publish something about this on your new look website in the support section, and make it nice and easy for people to find.

**Comment by Mojo-LB** [comment]
Pool owners know how to find posts on github...

Excuse typos - Sent from mobile

________________________________

**Comment by bobbieltd** [comment]
@Mojo-LB : Lol , young pool owners are busy to look for miners. Moreover, how can they find this posts from hundreds of post ?

**Comment by Starmute** [comment]
@electroneumRepo Please respond to my email. Thanks.

**Comment by Mojo-LB** [comment]
Just to make things clear, the "difficulties" are related to the fork dated today?

It doesn't make sense to pull in the team for the weekend for an unreleased product.

What went wrong with the fork? Is the network out of sync? did you guys forget to update your own nodes?


Excuse typos - Sent from mobile

________________________________

**Comment by Starmute** [comment]
@Mojo-LB From the looks of it, somebody screwed up the update code. The difficuties are related to the fork. Most people seem to have updated but only empty blocks are being mined which means no transactions can go through.

**Comment by Mojo-LB** [comment]
Well at least people panicking are not able to sell 😂 😂

**Comment by fetenete** [comment]
Seems like something is wrong with the previous block 179839.. According to the blockexplorer the fees are N/A

**Comment by mannie65** [comment]
Pools with updates are stuck on block 179846/7 - with Zero rewards, pools that have not applied the patch are progressing with new blocks - up to 179928 according to their stats, so I'm no expert on the fix, but do we have 2 forked (varied block chains) ?

**Comment by fetenete** [comment]
I'm not familiar with the code, but what if the block 179840 was found by a node that hasn't been patched yet? Would that be an explanation?

**Comment by Starmute** [comment]
@fetenete No, it's a v3 block. They have compiled a new version which will be released tonight.

**Comment by mannie65** [comment]
@Starmute  - Does that mean a recompile/update for all pool owners - or back-end fix ?

**Comment by fetenete** [comment]
@Starmute thx for the update! Appreciate your help for the electroneum community!

**Comment by XzenTorXz** [comment]
@mannie65 every node needs to update again and then we might move along

**Comment by bobbieltd** [comment]
What should I do for the pool to fix it now ? Any quick solution or I have to wait for an update fix from dump Electroneum devs ?

**Comment by keybutler** [comment]
They say it will be updated on GitHub so all Pool Masters will update the code? / patch?
Yolo

**Comment by keybutler** [comment]
Soon

**Comment by Ogy** [comment]
Is it ok now ? ..

**Comment by bobbieltd** [comment]
It’s ok now. Download and recompile.

**Comment by bmatthewshea** [comment]
Shame they put the exact same version on 'revert release'. It isn't a complete revert to previous "v0.11.0.0". Therefore the version should be changed. (duh). If you use 'original' "11.0.0" **it will not go past 202612**. Not to say I'm surprised they created more confusion. They seem to be good at it.

This is what you get when 'devs' fork code (monero), but generally have no idea what they are doing overall aside from renaming it. Form before function.. same old story.
Thank you @XzenTorXz and rest for "pushing" them on this!
