### ISSUE TITLE
Electroneum node list, please, add in comment

### ISSUE THREAD

**Issue by xlp0rk0lx** [electroneum/electroneum#12]
29/11/2017
______________________
91.107.97.108:4904
175.142.65.149:51704
129.21.89.185:26967
70.76.17.198:26967
178.251.110.84:26967
70.76.17.198:26967
___________________________

**Comment by electroneumRepo** [comment]
Who's IP's are these?
Where did you source them from?
What is their up-time?

(Please provide more information on why we should add those into the node list)

**Comment by thesunlover** [comment]
NB: 70.76.17.198:26967 is duplicated

**Comment by kim0** [comment]
They all don't seem working! Wish the official team would launch official servers and/or web wallets soon
