### ISSUE TITLE
Daemon/Wallet install to secondary HDD

### ISSUE THREAD

**Issue by ScotchVA** [electroneum/electroneum#121]
Hello,

I am installing the daemon/wallet on Ubuntu 16.04 (VPS) that has an additional HDD. I was wondering how to get the Blockchain to download to the secondary HDD, not the limited primary.

Thank you.

**Comment by electroneumRepo** [comment]
You can use the --data-dir flag when you start the daemon.

For example, In command prompt on windows `electroneumd --data-dir="D:\electroneum"
