### ISSUE TITLE
Get Windows Direct Miner running with GPU

### ISSUE THREAD

**Issue by sound-engineer** [electroneum/electroneum#126]
Hy there! The efficiency of the electroneumd.exe seems to be dependent from the power of the CPU (so number of cores, frequency, number of threads and L3 cache). By the way: 2 MB L3 cache seems to be recommended for each thread - but as I'm using the AMD FX 9370 (4 modules with together eight logical cores á 4,4 GHz and 8 MB L3 cache), I get ~ 270 H/sec with four threads (50 % CPU load) and ~ 370 H/sec with eight threads (100 % CPU load). So for the AMD Bulldozer seems to be 1 MB L3 cache enough?

But my original question was: How to get the GPU calculating the hashes too with the so called "Windows Direct Miner"? Running the analysis tool GPU-Z shows 0 % GPU load during mining with the electroneumd.exe (at 100 % CPU load). On the other hand a Youtube documentation shows, that the Radeon RX Vega 64 GPU would calculate 2000 H/sec. What is the tool to get the GPU running as miner (as stand alone version, not a pool) - and is there a possibility to activate it within the process of the electroneum daemon? Thanks!

![mining](https://user-images.githubusercontent.com/35989931/35611184-2da806dc-065c-11e8-9a4e-3b6d8740998e.jpg)

**Comment by Starmute** [comment]
I believe the default daemon miner has no GPU support. Use XMR-STAK or some other software for this capability.

**Comment by jpeter12** [comment]
@Starmute I believe you are absolutely correct :)
