### ISSUE TITLE
48 Hours sync, 50% done

### ISSUE THREAD

**Issue by smith901** [electroneum/electroneum#127]
Cloned from git on 1-12, no problems compiling and running, stopped running 1-13 after learning how to use these programs.  Fastfoward to 1-29, made EXTRA space on HDD ran electroneumd, it is taking extremely too long. My system is not the problem because it is fast for everything except the electroneumd blockchain sync. 

48 hours syncing and it is 50% done. Very lean system with almost no HDD, CPU or RAM usage from other programs/services. Inet bandwidth as wide as it want to be. Up/Down speeds faster that my server can handle. It takes 8-30 minutes to sync 100 blocks. Saved progress, stopped daemon, removed everything from network except this unit. Restarted daemon, now it is throwing "levin-protocol -->> start_outer-call failed" errors constantly. The --add-peers, fast-block-sync, & db-sync-mode switches are not honored on CLI or in conf file.  
 
My pings and network related stats come back great.

**Comment by flicker581** [comment]
Though 48 hours seem too much, HDD may be very slow to sync. Especially if you have not much RAM for cache. Those daemons are very random access intensive. SSD can be much faster.

**Comment by smith901** [comment]
@flicker581 HDD good, all other hardware #s well in range, RAM maxed out for MOBO. I know SSDs are faster, problem is the sync is happening soooooo ssllooooww its not making the HDD work hard enough for read/write operations to cause the slowdown. Same binary from initial compilation, slim conf file with only sync related info.

If the daemon RAM sensitive, what does HDD vs. SSD got to do with it.

I feel like I can FedEx you my rig, you can see for yourself and get it back before this sync is estimated to finish. Or go to England, download tbe blockchain to USB and get back to Memphis before the estimated finish, provided I could get a flight a few hours from now.

Since numbers are the topic, what is the recommended minimum specs for a node? What are the recommended minimum specs for the internet connection? Simple up to date information is very hard to find and the search engines give BS and misinformation.

**Comment by ra-dave** [comment]
In my experience platter HDDs are always slow.  It took days and days to sync the Monero blockchain the first time.  I really don't think there is anything that can be done on the software side.  Get an SSD.

**Comment by smith901** [comment]
OK.
In simple English: ain't no hard drive activity going on. hard drive is new.

25years of computers gives me the insight to know this shit is "1992 dialup slow."

I haven't had swap activity in some years on any on my units so the HDD ain't the problem.

**Comment by flicker581** [comment]
One more and last time on HDD. Blockchain sync is a special task. Due to huge database size, it needs many random seeks to be done. If you are on Windows, this can be noticed using Performance Monitor or just by HDD led nearly always on. Volume of I/O is very low in this case.

I'm, like you, never seed any problems with HDD, until I'd tried to sync blockchain. It starts rapidly and then slows down to stop. SSD makes huge difference. Unfortunately.

The protocol error which you have cited above is unknow to me. This can be another problem.

**Comment by smith901** [comment]
@flicker581 So you don't know so therefore the problem you had must be my problem, nevermind everything else. Ya'll make too many assumptions. "That protocol error" is what electroneumd gives. @Grimm2017 ditto

**Comment by fmikolajczak** [comment]
It has taken me less than 10 hours to synchronize full blockchain using HDD and elderly computer. I did this last night. It is only 11GB!

**Comment by smith901** [comment]
Thanks for the info @fmikolajczak.10 hours was about how long it took the first time. Took a few days to find DDR2 RAM, resurrected the Old Man, it is going faster than Archie. Archie finished syncing @ 11pm last night, 5days. I just hope I don't have to do it again unless I'm getting paid by the hour.
Same binary, same computer, comparable network activity with vastly different times for the same thing is a problem.
Thanks for reading and using your brain.
