### ISSUE TITLE
Error: refresh failed: no connection to daemon. Please make sure daemon is running.. Blocks received: 0

### ISSUE THREAD

**Issue by xlp0rk0lx** [electroneum/electroneum#13]
(https://user-images.githubusercontent.com/30440412/33385192-4ad4c9ee-d528-11e7-9f6c-cf7f5d28ff07.png)

Unfortunatly wallet won't sync

**Comment by electroneumRepo** [comment]
You need to run the daemon first (electroneumd). You must leave this running all the time you wish to use the wallet.

Wait for it to download the blockchain then you can start the wallet.
