### ISSUE TITLE
Ophaned blocks

### ISSUE THREAD

**Issue by Griunvaldas** [electroneum/electroneum#134]
Hi, pool digged 4 ophan blocks per 2 days @ 5mh speed. How can pool operator prevent ophanes blocks?

**Comment by marki555** [comment]
Connection to more nodes (preferably other large pools), so that the pool knows as soon as possible when someone already found a block. Also running daemon with `--fluffy-blocks` should help.

**Comment by ghost** [comment]
@DeanCole close
