### ISSUE TITLE
link to 'CONTRIBUTING.md' broken?

### ISSUE THREAD

**Issue by ETN-A** [electroneum/electroneum#140]
Just tried the link for the above (https://github.com/electroneum/electroneum/blob/master/CONTRIBUTING.md) [here](https://github.com/electroneum/electroneum#contributing) and got a '404 Page not Found'.

?

**Comment by bet0x** [comment]
As you can see they are not taking any PR. Because "Tech Stuff"

**Comment by ETN-A** [comment]
Such a small thing to fix, right?

**Comment by LeadManPL** [comment]
A year later and still not done :1st_place_medal:

**Comment by ghost** [comment]
We will update in the next release.

**Comment by LeadManPL** [comment]
You know, the whole idea of bug tracking systems like github, is to close the ticket **after** bug was fixed - not before...

**Comment by ghost** [comment]
@LeadManPL This is the issues section for the core blockchain repo. Nobody that works on the core blockchain also works on the mobile miner payments. You're in the wrong place so I'll leave the ticket closed.
Go here https://support.electroneum.com/servicedesk/customer/user/login?destination=portals
in future to open support tickets.
