### ISSUE TITLE
Code error 16 - Sent of ETNs out of my.electroneum.com wallet fails

### ISSUE THREAD

**Issue by louloops** [electroneum/electroneum#144]
I tried twice to transfer my coins from the wallet my.electroneum.com to Cryptopia, but it fails twice with same Error 16. It's the same problem reported in issue #133 but only difference is that my ETNs are still in my wallet.

<img width="770" alt="screen shot 2018-02-14 at 22 56 01" src="https://user-images.githubusercontent.com/35570604/36230424-ab4b5ff6-11da-11e8-8ee5-e4c3a04a8dde.png">

**Comment by KhmerRun** [comment]
I think many people had this issue and mine also. I think we just keep waiting.

**Comment by flyingfork21** [comment]
Same issue here. Since the first failed transaction wallet shows only failed transactions. Coins seems to be sent though but impossible to be sure of foreign transactions. No documentation either about this error code.

**Comment by KhmerRun** [comment]
Mine is more than 48 hours already and still not see the balance in. Sent two days ago from my.electroneum.com to my own wallet. Keep refreshing from time to time but still 0.00 ETN balance. Hopefully, waiting is one solution.

**Comment by KhmerRun** [comment]
Just doubt if other people got the problem solved. I just keep waiting 4 days already and https://my.electroneum.com/ still took my sent balance out to nowhere.

**Comment by martinvenus** [comment]
I have the same problem. I've sent money to offline wallet, transaction failed with code 16, money are not in offline wallet and current balance does not contain money from the failed transaction. I'm already waiting for more than a week, but money seems to be lost.

I've created a support ticket #38816 but no response at all.

**Comment by louloops** [comment]
7 days and no reply from the support team whatsoever....  Could we have a status please?

**Comment by martinvenus** [comment]
I'm really afraid that we will not get any response. Two days ago I have received this e-mail from the support team:
>Hi Martin Venuš
>
>Sincere apologies for the delay in replying. If your issue has not been resolved can you please reply to this ticket and we will look into this for you.
>
>Kind regards,

I have replied immediately, but no more response from the support team.

**Comment by ChengYen-Tang** [comment]
Try leaving 2 ETNs on my.electroneum.com
