### ISSUE TITLE
electroneumd

### ISSUE THREAD

**Issue by dasher10** [electroneum/electroneum#145]
Can anyone tell me clearly how to see if you have resolved a new block by yourself using the daemon "electroneumd" and how soon to expect the balance to show up in the wallet-cli created wallet?

**Comment by p2svn** [comment]
just login to wallet
check hash, it will show how much blocks need to unlock balance

**Comment by dasher10** [comment]
Thanks, but what command exactly to use to check hash? All I wanted to see clearly is if my direct miner yielded any new blocks solo. Is there a message that I should look for in the electroneumd daemon?
