### ISSUE TITLE
Where can i download electronum blockchain raw for import ?

### ISSUE THREAD

**Issue by p2svn** [electroneum/electroneum#146]
Where can i download electronum blockchain raw for import ?

**Comment by electroneumRepo** [comment]
A copy of the raw blockchain can be downloaded from https://downloads.electroneum.com/blockchain.raw

You will need to use the blockchain importer to use this. It was last updated on the 23rd of February.

**Comment by ingeniuz** [comment]
I get "Access denied" when I try to download https://downloads.electroneum.com/blockchain.raw

**Comment by flashjpr** [comment]
@electroneumRepo Thank you for the raw bchain file. Saves a lot of time!

**Comment by usetn** [comment]
Can you please upload a new raw file it is too outdated.
There are unofficial files online but I am not comfortable to use those files as it is not secure.

**Comment by electroneumRepo** [comment]
A new version of the blockchain has been uploaded today at https://downloads.electroneum.com/blockchain.raw

**Comment by jst1974** [comment]
How can I import this file into electroneumd? My PC is already syncing for 6 daysand still 51 days behind. Would like to speed upthis
