### ISSUE TITLE
Unable to Open/Run electroneumd.exe

### ISSUE THREAD

**Issue by blamb211** [electroneum/electroneum#147]
I just get an error:

Operation did not complete successfully because the file contains a virus or potentially unwanted software.

I know what I'm about, Windows. I'm on Windows 10, if that makes any difference.

**Comment by Bradx** [comment]
This is just what it says it is.  Your scanner (Security Essentials?) sees the daemon as a virus.  You need to go into settings and whitelist it as well as the wallet files.  You might also need to recopy the files to that directory because scanners often delete or quarantine wallet components.
