### ISSUE TITLE
GLIBC_2.16' not found (required by ./electroneumd)

### ISSUE THREAD

**Issue by da110us** [electroneum/electroneum#15]
HI,

Tried the Linux direct miner on a VPS (CentOS 6). Any idea?

`# ./electroneumd
 
./electroneumd: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by ./electroneumd)
./electroneumd: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./electroneumd)
./electroneumd: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./electroneumd)
./electroneumd: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./electroneumd)`

**Comment by electroneumRepo** [comment]
Hi,

The version you've downloaded was compiled on Ubuntu 16.04.

I've tested on a CentOS 6 box and I get the same errors as you. The reason this is happening is because CentOS 6 uses an older version of GLIBC. I'll try to get it compiled on CentOS 6 if I can.

Sorry for the inconvenience

**Comment by da110us** [comment]
Thanks for the quick response. Let me know when the Centos version becomes available.

I've got the miner running on Windows now. Just experimenting how things work. I have generated an offline wallet (web generator) and used the public address for mining. can you tell me how I can check if the mined ETN is landing in this wallet? Just checking everything before I throw my GPU's in.

**Comment by luckyluke113** [comment]
How about this issue? Is it available for CentOS ?
