### ISSUE TITLE
Wallet sync takes a week 

### ISSUE THREAD

**Issue by Cryptoerror** [electroneum/electroneum#152]
Every time I open my wallet  it takes a week to sync  it always begins at Height 64000 and takes a week to reach 169000  this is impossible to work with and even if I have synced to the latest block  if i close and open it again it will begin from 64000  Plz Help

**Comment by angelhvargas** [comment]
when you get the wallet synced, you can execute `save_bc` and `save` that would solve the problem. Don't forget to do it before exit every time you re-sync your wallet.

**Comment by jpeter12** [comment]
Must be a local wallet issue (with your installation). Wallet syncs just fine on my systems (ca. 100 blocks per second...maybe 75).

Have you tried to recreate your wallet with the seed (25 words)?
With your seed, you can easily recreate your wallet using the following command:

electroneum-wallet-cli --restore-deterministic-wallet

I have had a similar problem with the monero problem. Nothing worked until I recreated the wallet.

**Comment by Cryptoerror** [comment]
thanks for response guys I will try them when  It finishes sync
