### ISSUE TITLE
Electroneum Raw Blockchain Synced Nodes?

### ISSUE THREAD

**Issue by r7avi** [electroneum/electroneum#154]
Hi, 
Can you guys Please upload Raw blockchain syncd data? 
so we can directly download it ? 
Because, Its been 2 days and my nodes syncing stuck at 90k height. :( and It is taking forever,

**Comment by lkelemen** [comment]
if you are in win10 make sure it is not this case: when you click inside the cmd.exe window it freezes the window content i.e. it is not updated. You can see that the top row left corner it says "Select C:\Windows ..."
You press a key so there is no "Select ..." at the beginning. If you don't do this soon enough your sync process may finish but it is not printed in the window.

**Comment by r7avi** [comment]
what? thats really not helping!
monero website gives raw blockchain data with some pre synced block height,
like that please provide raw blockchain data, so we can download and put it in C:\ProgramData\electroneum\lmdb and headstart :)

**Comment by electroneumRepo** [comment]
@r7avi Raw blockchain can be downloaded from https://downloads.electroneum.com/blockchain.raw.

You'll need to use the blockchain import executable to extract this. This can take some time depending on your system.

**Comment by r7avi** [comment]
@electroneumRepo , I tried to download from there , it comes with following error

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BC6FC785044B9804</RequestId>
<HostId>
ljESZjNtiRhryitG6Ze3RRd7T73rwO3IwRtnBTXnnbbacNQ3d7GZfFZYV6r1Zzqz8dvlADSqohg=
</HostId>
</Error>`

**Comment by bmatthewshea** [comment]
@electroneumRepo 
"@r7avi Raw blockchain can be downloaded from https://downloads.electroneum.com/blockchain.raw."

That was a joke, right?

Finally got that to import.
It' still 60 days out of date.

https://i.imgur.com/C6ksqXA.png

Why not automate your export, nightly? Or even weekly?
Also, you do not show this blockchain download on "downloads" page.
Why?

**Comment by ItzBigFun** [comment]
yeah there nodes are outdated , even if u download raw blockchain u need sync it untill current block,
which will take more then 4-5 days with minimum requirements :(

they need to update raw data atleast once a week
