### ISSUE TITLE
Update Snap please

### ISSUE THREAD

**Issue by TheLastTriarius** [electroneum/electroneum#162]
Hi. Could you update Snap version of Electroneum to newest?

**Comment by ghost** [comment]
Will look into this

**Comment by ghost** [comment]
I've created most of the snapcraft.yml but I believe there is a bug or something odd going on with the snapcraft cmake plugin and the cmakecache.txt file. I created a branch snap-package. Anyone is welcome to try and fix it. As soon as it builds, i'll upload it.
