### ISSUE TITLE
blockchain.cpp -  Fork to v3

### ISSUE THREAD

**Issue by jamessenior1** [electroneum/electroneum#163]
Hi,
Should the code which was pasted in for Fork to v3 be changed like the below

static const uint64_t mainnet_hard_fork_version_1_till = 1009826;

be changed to

static const uint64_t mainnet_hard_fork_version_1_till = 179839;

The value 1009826 is from the old version of monero version2 code and should not have been left in Fork to v3
-  // version 2 starts from block 1009827, which is on or around the 20th of March, 2016. Fork time finalised on 2015-09-20. No fork voting occurs for the v2 fork.
-  //{ 2, 1009827, 0, 1442763710 },

Not sure what can be done now after the fact as i'm not a blockchain developer.

Thanks,
James

**Comment by jpeter12** [comment]
Justified...devs are working on the issue.
