### ISSUE TITLE
Important : About Hard Fork v3 Revert!`

### ISSUE THREAD

**Issue by r7avi** [electroneum/electroneum#167]
My Question is Simple!

Do we need to Download Entire Blockchain Node Once again? or Just Replacing new Verison with old Node is Enough ?

If we need to download entire blockchain again then this is pain in ass , coz it takes 3-4 days or even weeks to download again,

I requested you guys in last post to upload raw blockchain , coz this link never worked https://downloads.electroneum.com/blockchain.raw ( giving error - `This XML file does not appear to have any style information associated with it. The document tree is shown below. <Error> <Code>AccessDenied</Code> <Message>Access Denied</Message> <RequestId>BC6FC785044B9804</RequestId> <HostId> ljESZjNtiRhryitG6Ze3RRd7T73rwO3IwRtnBTXnnbbacNQ3d7GZfFZYV6r1Zzqz8dvlADSqohg= </HostId> </Error>`)

If there is some other way to download using that link, then make a tutorial or give a method , rather then saying go download https://downloads.electroneum.com/blockchain.raw and use electroneum-blockchain-import to extract it (coz without a tutorial or commands how can u expect us to do that so?) 

i dnt want to wait a week to access my funds, coz syncing blockchain makes my Pc fuckin slow i cant even open other app while it is syncying ?

You need to Fix this First!

**Comment by spoonwzd** [comment]
Link works fine - just right-click and save-as.

**Comment by r7avi** [comment]
What about another 7GB ? Should i ask ur ,,,?

**Comment by r7avi** [comment]
Okie , now its Solved , 

I Problem is my indian IP is taking me to error page, 
but using vpn i can download the .raw file and its still many days away , please update with latest one where u did hardforkv3
