### ISSUE TITLE
Hard Fork v3 Revert — "Wrong" version number?

### ISSUE THREAD

**Issue by ETN-A** [electroneum/electroneum#169]
Hard Fork v3 Revert ( Revert "Upgrade to v0.11.1.0" ) is marked with "old" (previous) version number (v0.11.0.0). Updated Electroneumd (on Mac—perhaps elsewhere too) shows "Electroneum 'Helium Hydra' (v0.11.0.0-release)".

It seems to have "gone back" from 0.11.1.0 here: 
https://github.com/monero-project/monero/commit/7c1d0076730a710e421ecec60ab3575373c4b871#r27901691. Current file: https://github.com/electroneum/electroneum/blob/master/src/version.h.in

This potentially creates a confusion when checking/making sure that the latest version is running.

Am I missing a compelling reason?

**Comment by XhmikosR** [comment]
The patch version number should have been bumped to avoid confusion IMO.
