### ISSUE TITLE
Sync Stuck on Block 179848

### ISSUE THREAD

**Issue by Cryptoerror** [electroneum/electroneum#170]
Electroneumd  is  stuck on block 179848  can anyone help plz

**Comment by navossoc** [comment]
Just download the latest release.
https://github.com/electroneum/electroneum/releases/tag/v0.11.0.0-revert

**Comment by wszczepaniak** [comment]
It would be nice to update the snap version also.

**Comment by RinTye** [comment]
Same problem.  Stuck on 179848 and I'm using the new win-x64 revert version.

**Comment by Starmute** [comment]
Please delete the blockchain LMDB files and resync after that. This should fix the problem.

**Comment by jpeter12** [comment]
For the more tech savy people, you can also export your current block chain with the electroneum-blockchain-export tool and set a stop block before 179848 (let's say 179800). Then you reimport the same after deleting the blockchain LMDB files. This way, you won't have to sync the entire blockchain. I suppose we haven't heard the last of fork v3.

**Comment by RinTye** [comment]
Thank you all, working as intended now!  Human error on my part.  I had done a resync before I originally posted.  I then ran into the same problem again after pruning off 20 blocks of the blockchain.   I made a rookie mistake and missed updating one of my shortcut paths.  The blockchain was being updated in the revert directory but using the 0.11.1.0 daemon.  Oops! Thanks again.

**Comment by jpeter12** [comment]
@jedisca Popping the blocks never worked for me. But good suggestion. That's probably the quickest way (if it does work).

**Comment by Lbni** [comment]
Hello guys, 

i don't find the blockchain LMDB files on my computer.. somebody could help me please ?

**Comment by bitkevin** [comment]
@jpenner123 Don't expect too much, I wasted two days on this issue, just use `v0.11.0.0-revert`. ETN really sucks.

**Comment by bitkevin** [comment]
```
electroneum-blockchain-import --pop-blocks 20
```
Does NOT work at all.
