### ISSUE TITLE
install on win7 x64

### ISSUE THREAD

**Issue by shadowolfs** [electroneum/electroneum#171]
Ok installing electroneum with msys ran through the steps but when i run 
make release-static-win64
i get this
make: *** No rule to make target 'release-static-win64'
how do i get past this thanks

**Comment by electroneumRepo** [comment]
Could you confirm what directory you are in?

**Comment by shadowolfs** [comment]
ServiceTech@DESKTOP-H80KSAT MINGW32 ~
$

**Comment by shadowolfs** [comment]
nvm mind got it....duh...needed to be in Elec...-master
