### ISSUE TITLE
Electroneumd.exe keeps crashing

### ISSUE THREAD

**Issue by wtf808** [electroneum/electroneum#172]
Worked like a charm up until a few days ago.. old version and new version now crashes shortly after running it.  Windows Server 2016..

**Comment by sempiterna** [comment]
Happens to me as well. The old version i've been using since Electroneum went live in 2017 has been running without any crash. The new one crashes after X minutes. Sometimes 15 minutes, sometimes 30, etc. I'm using windows 10.

**Comment by wtf808** [comment]
I just renamed the block data MDB and started over.. suuuuucks.. but seems to be working so far.  I’ll report back once it’s finally back in sync. :(

**Comment by electroneumRepo** [comment]
You can download the raw blockchain from [https://downloads.electroneum.com/blockchain.raw](here)

Then use the following command to import it:
`./electroneum-blockchain-import --input-file blockchain.raw --verify 0`

This will make getting the blockchain setup a lot quicker.

**Comment by sempiterna** [comment]
Unfortunately after deleting the old lmdb folder, importing the chain, and starting electroneumd.exe, it still crashed after X minutes.

**Comment by wtf808** [comment]
redoing the chain seems to have fixed it for me...  so far so good..  knock on wood.
