### ISSUE TITLE
Nodes

### ISSUE THREAD

**Issue by FrankK53** [electroneum/electroneum#174]
After reading the message from Richard I decided to run a node. I know that most nodes are not rewarded for their work, but it is a necessity. I have a machine that isn't doing anything and I have the bandwidth to spare.

Would someone please tell me how to run a node? I have the latest software installed.

Thanks,
Frank

**Comment by tandasima** [comment]
1. Download the latest binaries
2. Run electroneumd.exe
3. Wait for the whole blockchain to sync
4. Leave the electroneumd process running (will continue to sync latest blocks) - Hence you are a node.

NB: You don't have to be mining to be a node.

**Comment by FrankK53** [comment]
Thank you, kind sir. I appreciate the information. Does/should the node's IP address be promulgated to someone?

**Comment by tandasima** [comment]
@FrankK53 You are welcome. 

No it doesn't. As long as you're online, you're good. Your node will know how to talk/communicate with other nodes in the ETN network.

Feel free to close the issue/ question if satisfied. Thank you.
