### ISSUE TITLE
Ubuntu 14.04 unable to build

### ISSUE THREAD

**Issue by cristianb84** [electroneum/electroneum#177]
$ make
mkdir -p build/release
cd build/release && cmake -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=release ../.. && make
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Building without build tag
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1f") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found MiniUPnPc: /usr/include/miniupnpc  
CMake Error at cmake/FindMiniupnpc.cmake:51 (if):
  if given arguments:

    "GREATER" "10" "OR" "EQUAL" "10"

  Unknown arguments specified
Call Stack (most recent call first):
  external/CMakeLists.txt:38 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/cristi/BitcoinZ/electroneum/build/release/CMakeFiles/CMakeOutput.log".
See also "/home/cristi/BitcoinZ/electroneum/build/release/CMakeFiles/CMakeError.log".
make: *** [release-all] Error 1

**Comment by TurkishPower92** [comment]
use windows 10 for electroneum wallet :)
