### ISSUE TITLE
Cant Get wallet.cli.exe to work properly

### ISSUE THREAD

**Issue by AlienRob** [electroneum/electroneum#18]
Hi I am trying to get wallet.cli.exe to work in dos through command prompt, but after I follow all steps correctly (at least i think I am) it asks me to specify a starting date or block number which I do and then just returns back to the directory. I am mining Electroneum on my desktop buti can't see my mined balance. For all I know I am just wasting precious time & energy without any ETN to show for it. Any help in solving my mystery is absolutely 100% appreciated.
Cheers in advance 
Alien rob

**Comment by electroneumRepo** [comment]
@AlienRob When it asks you for a specific date / block just simply hit enter.
