### ISSUE TITLE
Balance 0 my cli-wallet

### ISSUE THREAD

**Issue by msorokin177** [electroneum/electroneum#180]
Tx hash: c0495815f66f2a862921030dd13d89891435f55d1d2c687dc26d5826f9dff204

I was sent an ETN to the purse created through the wallet-cli.
Blocks are synchronized.

# Command status
Opened wallet: etnjzLZq4N2Z6oDgLis5uq4M6n5TvTq9v7iouXSYiELufASPqsAXB3c715FdYQ5CchCwNi8RUvkjCa1c5aDBKGV85SKkKiUBrX
************************************************** ********************
Use "help" command to see the list of available commands.
************************************************** ********************
Refreshed **197107/197107**, synced, daemon RPC v1.13

# Command balance
Opened wallet: etnjzLZq4N2Z6oDgLis5uq4M6n5TvTq9v7iouXSYiELufASPqsAXB3c715FdYQ5CchCwNi8RUvkjCa1c5aDBKGV85SKkKiUBrX
************************************************** ********************
Use "help" command to see the list of available commands.
************************************************** ********************
Balance: **0.00**, unlocked balance: **0.00**

# Blockchain Explorer
<img width="1387" alt="2018-03-14 21 51 12" src="https://user-images.githubusercontent.com/11409466/37424801-6f1bf67c-27d2-11e8-897a-bfe8df89ce34.png">

# Account Sender
<img width="909" alt="2018-03-14 21 54 57" src="https://user-images.githubusercontent.com/11409466/37424802-6f54e64e-27d2-11e8-855c-af3c14db80e1.png">

# P.S
Maybe I'm doing something wrong? Perhaps you need to execute a sequence of commands to get this transaction?

**Comment by lemanhbk55** [comment]
Hi there,

I have already started mining with 
start_mining etnk3KXrJTMV5cZzo5afN3ECNZQBqAjPUJSfMuZvaFsFUmYaoHyGPLx5j2Y4UHTtWug1iyYSwjbQkavSRdwj71rL5TcAhtPvs7 4 do_background_mining
but now has no ETN in balance.
etnk3KXrJTMV5cZzo5afN3ECNZQBqAjPUJSfMuZvaFsFUmYaoHyGPLx5j2Y4UHTtWug1iyYSwjbQkavSRdwj71rL5TcAhtPvs7 is my Public address at offline wallet.

I am a newbie, please help me clear,
Thanks in advance!

**Comment by schmeckles22** [comment]
You are either not fully synced with the blockchain yet or... You are viewing the wrong wallet.

**Comment by ghost** [comment]
Try typing into the cli:
set (you'll see the refresh height)
set refresh-from-block-height 0

**Comment by msorokin177** [comment]
bad idea refresh full node every time
