### ISSUE TITLE
How can i save blockchain after sync so i don't  have to wait 2 weeks to sync again

### ISSUE THREAD

**Issue by Cryptoerror** [electroneum/electroneum#182]
My wallet is finally  synced what should i do so I don't go throw 2 weeks of sync  again

**Comment by TurkishPower92** [comment]
wait finish download after type save and done !

**Comment by schmeckles22** [comment]
electroneum-blockchain-export and then save the blockchain.raw somewhere and then electroneum-blockchain-import --verify 0 --input-file ./blockchain.raw

**Comment by ETN-A** [comment]
Further to schmeckles22 post above, you can also "use" an existing blockchain.raw file, which will then get appended (bootstrapping). 

E.g. if you have your electroneum lmdb saved in /Data/.electroneum and blockchain.raw saved in /Data/, use:

`electroneum-blockchain-export --data-dir /Data/.electroneum --output-file /Data/blockchain.raw`

This will then "append" the existing blockchain.raw file, which is obviously a lot quicker than building it from scratch.
