### ISSUE TITLE
Seed nodes

### ISSUE THREAD

**Issue by fengshuicoin** [electroneum/electroneum#187]
How is electroneum using monero seed nodes??? Or is source just show old code?

**Comment by TurkishPower92** [comment]
maybe yes :)

**Comment by fengshuicoin** [comment]
What purpose to keep seed nodes secrete or is it a monero dev that hosts
seed servers for both. Monero and electroneum. Hmmm lol

**Comment by TurkishPower92** [comment]
i think server's not both. Only cmd console both :)

**Comment by fengshuicoin** [comment]
Some type of connection ;)

**Comment by TurkishPower92** [comment]
yeah :)
