### ISSUE TITLE
running cmake with -DCMAKE_BUILD_TYPE=Debug causes successive make to fail.

### ISSUE THREAD

**Issue by Alia-morsi** [electroneum/electroneum#195]
Problem:
makefiles are created to link .dylib libraries, despite of them being created with .a. First error happens with libcommon.a, where it is searched for as libcommon.dylib

System:
OSX el Capitan 10.11.6

**Comment by ghost** [comment]
Does adding this to your Cmake options help at all?

-D ARCH="x86-64" -D BUILD_64=ON -D STATIC=ON
