### ISSUE TITLE
Logfiles in the .electroneum directory

### ISSUE THREAD

**Issue by BKdilse** [electroneum/electroneum#196]
My pool ran out of space today, and I couldn't understand why, as it has sufficient amount of disk space (100GB).

I can see loads of 100MB Log files in the Daemon folder (.electroneum).

Why are these being created?

**Comment by bosna387** [comment]
shit code shit  coin

**Comment by DeanCole** [comment]
What log level are you using?

**Comment by bradburycode** [comment]
Are you certain that it is the log files taking up all the space?
try adding this argument  
--log-level 0 
0 is least verbose

**Comment by DeanCole** [comment]
log level 0 is the default logging level so you don't need to specify it

**Comment by BKdilse** [comment]
Not using any log level, running as default.  No further logs have appeared since I raised this, so happy to close for now, can re-open if it happens again.

**Comment by BKdilse** [comment]
Spoke too soon, this happened again today around 16:00 GMT.
Over 100GB total logfiles, 100MB each, filled up the disk, and pool crashed.

I am not using any custom logging, and I checked 2 days ago, and confirmed that there was only 1 small log file, before I closed this.

Any ideas what is happening, to cause a flood of logs on random occasions?

**Comment by Unyxos** [comment]
Is it the pool software or the daemon creating logs file ? I noticed - when running my testnet’s pool - that there is an option in the config.json file of the electroneum-pool to configure the logging level

**Comment by BKdilse** [comment]
I believe it's the daemon.  Normally there is only 1 log file present "electroneum.log".

When the issue occurs, multiple files are created, and it looks like archives of "electroneum.log".  I should have recorded a few names, but just wanted to get the pool up ASAP.

I will grab more details next time, but any ideas if there is a setting to create loads of logs, if something weird is going on?

**Comment by Unyxos** [comment]
What’s the content of the electroneum.log file? (Sorry for the quotes at every of my replies, I’m replying through mail)

**Comment by BKdilse** [comment]
No probs. The contents is what looks like the output from the Daemon.  Exactly what you would see when you run the Daemon manually.  It's 20KB in size.

**Comment by DeanCole** [comment]
The logs rotate when it reaches 100mb.

This usually only happens (in my experience) when you change the logging level on the daemon or if there are many errors being displayed in the daemon.

Again, this likely wouldn't happen with the default logging level because not a lot of information is being output.

Has this happened again?
Is this happening at common times (e.g a specific day of the week / time of day)?

**Comment by BKdilse** [comment]
I have not made any custom log changes.  I guess has happened when there have been issues with Daemon/Network.

This has not happened again.  I will will close this for now.
