### ISSUE TITLE
Mobile Mining

### ISSUE THREAD

**Issue by akashgupta9990** [electroneum/electroneum#199]
From 1st of april mining in mobile is not updating pending balance sometimes even if i mine for 7-8 hours straight

Also if i mine 10etn it is deducted from my pending balance but not updated my Electroneum wallet.

Fyi - i have updated my device to oreo on 1st april. Not sure if that is the issue or it is issue in app.

**Comment by Unyxos** [comment]
This is not a blockchain-related issue, please don’t open issues for that…
Better to open a support ticket on https://support.electroneum.com, but as far as I saw on Telegram lot of tickets have been sent about that so… wait a bit ;)

**Comment by akashgupta9990** [comment]
@Unyxos 
Thanks for the info.
