### ISSUE TITLE
wallet-rpc returns "not found" when trying to lookup a wallet-address

### ISSUE THREAD

**Issue by sabudbai** [electroneum/electroneum#20]
I have issues getting stats for wallet addresses.
The redis-server is running on port 6379 and the wallet-rpc also on port 8082.
Nevertheless I can't get the stats working on our pool ? It always returns not found?
I have tried to debug the code lib/api.js

`if (urlParts.query.longpoll === 'true'){
        redisClient.exists(config.coin + ':workers:' + address, function(error, result){
            if (!result){
                response.end(JSON.stringify({error: 'not found'}));
                return;
            }
            addressConnections[address] = response;
            response.on('finish', function(){
                delete addressConnections[address];
            })
        });
    }
`
Somehow the redisClient doesn't find the worker with linked address ? I have started the wallet-rpc with following command succesfully 

> ./electroneum-wallet-rpc --wallet-file WalletName --password mypwd --rpc-bind-port 8082  --daemon-address 127.0.0.1:26968

Would be glad if someone could help me out with this

**Comment by electroneumRepo** [comment]
@sabudbai Firstly this is not a issue for this repo. It should be on the pool repository.

Secondly, The stats on the web interface is reading from your redis database NOT the wallet-rpc.

By the sounds of it, your api is not set up correctly for the front end.

Please be sure to read all of the instructions on the pool repository readme file
