### ISSUE TITLE
Can't open CLI wallet

### ISSUE THREAD

**Issue by hardmallet** [electroneum/electroneum#201]
"electroneum-wallet-cli.exe --generate-from-keys" command isn't working for "win-x64-v0.11.0.0-revert"? Keeps saying electroneum-wallet-cli.exe is not a recognized internal command.

used to work fine with the old version...any ideas?

**Comment by Unyxos** [comment]
Are you sure you’re in the directory of the binaries when trying to launch the command? Is it working fine when you try to launch electroneumd.exe ?

**Comment by hardmallet** [comment]
@Unyxos It's fully synchronized.  This is how I always open my wallet. IDK what's wrong why it won't work with the new version. Was totally fine with the old version.

open command prompt
type "cd [win-x64-v0.11.0.0-revert extraction location]" 
press ENTER
type "electroneum-wallet-cli.exe --generate-from-keys Wallet.etn"
press ENTER
input PUBLIC WALLET ADRESS
press ENTER
input PRIVATE SPEND KEY
press ENTER
input PRIVATE VIEW KEY
press ENTER
type [PASSWORD]
press ENTER
retype [PASSWORD]
press ENTER

**Comment by Unyxos** [comment]
Hmm I’m not using Windows a lot, I’ll try on my side today if you want and see if I have this issue too !

**Comment by hardmallet** [comment]
@Unyxos Thanks! :) Have a nice day!

**Comment by Unyxos** [comment]
Alright, I've just tested and it's working fine for me..

```
C:\Users\coren\Desktop\etn>dir

 Répertoire de C:\Users\coren\Desktop\etn

07/04/2018  12:47    <DIR>          .
07/04/2018  12:47    <DIR>          ..
03/03/2018  02:48        12 156 829 electroneum-blockchain-export.exe
03/03/2018  02:48        57 207 715 electroneum-blockchain-import.exe
03/03/2018  02:43        19 420 787 electroneum-wallet-cli.exe
07/04/2018  12:49             1 310 electroneum-wallet-cli.log
03/03/2018  02:42        19 697 218 electroneum-wallet-rpc.exe
03/03/2018  02:47        62 716 214 electroneumd.exe
03/03/2018  02:28         3 802 396 libcrypto.a
03/03/2018  02:28           597 956 libssl.a
03/03/2018  02:28            57 317 libwinpthread-1.dll
               9 fichier(s)      175 657 742 octets
               2 Rép(s)  408 045 510 656 octets libres

C:\Users\coren\Desktop\etn>electroneum-wallet-cli.exe --generate-from-keys test
Monero 'Helium Hydra' (v0.11.0.0-3b62c743)
Logging to C:\Users\coren\Desktop\etn\electroneum-wallet-cli.log
Standard address:

**Comment by hardmallet** [comment]
@Unyxos Is there something wrong with how I open it? I normally open it that way and it was fine.Any suggestions?  electroneum-wallet-cli.exe is not a recognized internal command, any potential cause?

**Comment by lkelemen** [comment]
What command prompt do you use? What does dir command show?

**Comment by hardmallet** [comment]
@ikelemen idk what you mean by dir, i'm noob ....i just open the windows command prompt, is there another one?

**Comment by hardmallet** [comment]
figured it out :)

It has to be placed on C:\ 

I extracted it on my E:\ drive (bad move i guess)

problem solved 👍
