### ISSUE TITLE
ETN stuck in blockchain

### ISSUE THREAD

**Issue by bhoomij** [electroneum/electroneum#202]
I have withdrawn 21133 ETN from kucoin on 1st april

For first day transaction was showing up in blockchain with Block: N/A and 0 confimations

Next day onwards when searching for hash on ETN blockchain, it shows errror 
 
**Cant get tx: ...hash**

Its been 7 days and still I didnt receive my coins. Talked with kucoin team also many times but they are not able to solve my issue ?

I see that there was hash attack on ETN chain and looks I am victim of this and lost my coins

Please urge you to look into this. I have also created support ticket on ETN zendesk, but still electroneum team also has not provided any solution for this

ETN zendesk ticket is  (47888) or  (38382). For more details check this tickets

Its been 7 days and no coin take this much time to complete on blockchain? Should I consider my coins as lost?

**Comment by ghost** [comment]
Your money should have been returned to Kucoin after 24 hours if it got stuck in the pool (7*24 for tx included in an orphaned block). It's a misconception that a 51% attacker can spend your coins - really what happens is they 'cancel a purchase receipt after receiving the goods'. Ie
Miner A (with 51%) pockets a block with their tx.
Miner B finds a block and includes the tx.
Miner A receives the goods in exchange for the ETN (goods might be btc, software, whatever)
Miner A finds another block and includes his original transaction again, and publishes both this block AND the pocketed block, which subsequently 'orphans' the first, rendering it invalid, and allowing for spending twice.
Or are you talking about an actual password hash attack? (something we're pretty sure never happened).

You need to ask Kucoin to check if any money was returned to them.

**Comment by bhoomij** [comment]
No, I am not talking about  password hash attack
I have asked to kucoin team many times, they never told like this that coins are returned back. 
Is it possible to get any help from electroneum team in this matter, because it looks apparently, kucoin wont be able to find any solution for this, and in that case my coins wont be returned back to my wallet

Also would like to know what could be technical reasons for below ?

First day: tx was showing in blockchain with **Block:N/A and Confirmations: 0**
After around 1 day it started showing **Cant get tx**

i.e. why the same tx which was earlier showing up in ETN site is now stated as cant get this tx

**Comment by jcraigseller** [comment]
I am also suffering from this problem.  It has only been 24 hours.  Here is a TXID so you can take a look at it in the blockchain explorer:

729ead38ca8a1edec6a7282dfe04d9595b1495070202404e0b9730ca8a859cfb

**Comment by jcraigseller** [comment]
My transaction has now disappeared after 24 hours.  Here is a JPG of the top of the page before it disappeared.  I have screen grabs of all the input detail too, if you want them.
![capture1](https://user-images.githubusercontent.com/37228908/38477639-603f824e-3b79-11e8-92bc-212e480625c6.JPG)
Is this the behavior of an 'orphaned' block?

**Comment by jcraigseller** [comment]
I also withdrew from KuCoin.

**Comment by sanitariu** [comment]
I have the same problem. I think there is actually an attack. I see many transactions with the size of 0.09 ETN. Actually every second. This is the real problem i think.

**Comment by aiglon8** [comment]
Same problem here / transaction appeared for 24 hours, and now 
"Cant get tx: 03e7cb2d39ef2400deed0c9318cfbf10c09a..................."

ETN are neither in Kucoin nor in Online ETN wallet

Any info somebody ??

**Comment by aiglon8** [comment]
Same problem here / transaction appeared for 24 hours, and now 
"Cant get tx: 03e7cb2d39ef2400deed0c9318cfbf10c09a..................."

ETN are neither in Kucoin nor in Online ETN wallet

Any info somebody ??

**Comment by arcane30** [comment]
Sanm thing happened to me. Electroneum support sent me a message last Saturday morning saying wait 172 hours. Kucoin hasn't answered my emails since last Tuesday. Don't know what going to happen to my 89000 ETN.  (51016)

**Comment by aiglon8** [comment]
Hi arcane30 ,

My ETN finaly arrived on my online wallet, took about 4 days. Hope this can help.

**Comment by arcane30** [comment]
Yeah this gives me hope, I thought all was lost especially when I clicked
on Check Transaction on Kucoin and all it said was.

"Cant get tx:"

On Apr 17, 2018 11:04 PM, "aiglon8" <notifications@github.com> wrote:

Hi arcane30 ,

My ETN finaly arrived on my online wallet, took about 4 days. Hope this can
help.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/electroneum/electroneum/issues/202#issuecomment-382251658>,
or mute the thread

**Comment by bhoomij** [comment]
@aiglon8 

Your receiving platform was exchange ? 
Were u facing same error "Cant get tx:"

I faced this 18 days back and still not received coins either on kucoin nor on receiving platform

**Comment by arcane30** [comment]
Wow I been waiting 9 days now. Has Kucoin support been replying back to
you, they stop replying to me when I told ETN support told me to keep
checking with them on my funds being returned.

**Comment by bhoomij** [comment]
I got my funds back today at receiving platform after 28 days
Closing this ticket

**Comment by arcane30** [comment]
Electroneum claim my ETN is on the way nothing has changed as of yet still
waiting to see.

**Comment by arcane30** [comment]
I appreciate u reach out to me that was dope 😎

**Comment by arcane30** [comment]
Deposit arrived overnight 😎

**Comment by jcraigseller** [comment]
Also received my balance today after 21 days.  My thanks to all.
