### ISSUE TITLE
where is docs on http rcp?

### ISSUE THREAD

**Issue by msorokin177** [electroneum/electroneum#207]
where is docs on http rcp?

**Comment by Unyxos** [comment]
Hey,

As ETN is based on Monero, I think this doc should be helpful : https://getmonero.org/resources/developer-guides/wallet-rpc.html

**Comment by msorokin177** [comment]
@Unyxos no, this does not work

i called method **create_wallet**
rcp return "Method not found"

**Comment by DeanCole** [comment]
`create_wallet
Create a new wallet. You need to have set the argument "–wallet-dir" when launching monero-wallet-rpc to make this work.`

**Comment by DeanCole** [comment]
You need to make sure that your using the --wallet-dir flag when starting the rpc server. This is instead of --wallet-file
