### ISSUE TITLE
Error on make release-static (Debian Stretch)

### ISSUE THREAD

**Issue by syndrael** [electroneum/electroneum#209]
Hello,
I can't find why make is unsuccessful.
Could you help me please ?
Thanks a lot for your help.
Regards

make release-static

mkdir -p build/release
cd build/release && cmake -D STATIC=ON -D ARCH="x86-64" -D BUILD_64=ON -D CMAKE_BUILD_TYPE=release ../.. && make
...
Scanning dependencies of target unbound
make[3]: Leaving directory '/home/myHome/electroneum/build/release'
make[3]: Entering directory '/home/myHome/electroneum/build/release'
[  8%] Building C object external/unbound/CMakeFiles/unbound.dir/services/cache/dns.c.o
[  8%] Building C object external/unbound/CMakeFiles/unbound.dir/services/cache/infra.c.o
[  9%] Building C object external/unbound/CMakeFiles/unbound.dir/services/cache/rrset.c.o
[  9%] Building C object external/unbound/CMakeFiles/unbound.dir/util/data/dname.c.o
[ 10%] Building C object external/unbound/CMakeFiles/unbound.dir/util/data/msgencode.c.o
[ 10%] Building C object external/unbound/CMakeFiles/unbound.dir/util/data/msgparse.c.o
[ 11%] Building C object external/unbound/CMakeFiles/unbound.dir/util/data/msgreply.c.o
[ 11%] Building C object external/unbound/CMakeFiles/unbound.dir/util/data/packed_rrset.c.o
[ 12%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iterator.c.o
[ 12%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iter_delegpt.c.o
[ 13%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iter_donotq.c.o
[ 13%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iter_fwd.c.o
[ 14%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iter_hints.c.o
[ 14%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iter_priv.c.o
[ 14%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iter_resptype.c.o
[ 15%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iter_scrub.c.o
[ 15%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iter_utils.c.o
[ 16%] Building C object external/unbound/CMakeFiles/unbound.dir/respip/respip.c.o
[ 16%] Building C object external/unbound/CMakeFiles/unbound.dir/services/listen_dnsport.c.o
[ 17%] Building C object external/unbound/CMakeFiles/unbound.dir/services/localzone.c.o
[ 17%] Building C object external/unbound/CMakeFiles/unbound.dir/services/mesh.c.o
[ 18%] Building C object external/unbound/CMakeFiles/unbound.dir/services/modstack.c.o
[ 18%] Building C object external/unbound/CMakeFiles/unbound.dir/services/outbound_list.c.o
[ 19%] Building C object external/unbound/CMakeFiles/unbound.dir/services/outside_network.c.o
[ 19%] Building C object external/unbound/CMakeFiles/unbound.dir/services/view.c.o
[ 20%] Building C object external/unbound/CMakeFiles/unbound.dir/util/alloc.c.o
[ 20%] Building C object external/unbound/CMakeFiles/unbound.dir/util/as112.c.o
[ 21%] Building C object external/unbound/CMakeFiles/unbound.dir/util/config_file.c.o
[ 21%] Building C object external/unbound/CMakeFiles/unbound.dir/util/configlexer.c.o
[ 22%] Building C object external/unbound/CMakeFiles/unbound.dir/util/configparser.c.o
[ 22%] Building C object external/unbound/CMakeFiles/unbound.dir/util/fptr_wlist.c.o
[ 23%] Building C object external/unbound/CMakeFiles/unbound.dir/util/locks.c.o
[ 23%] Building C object external/unbound/CMakeFiles/unbound.dir/util/log.c.o
[ 23%] Building C object external/unbound/CMakeFiles/unbound.dir/util/mini_event.c.o
[ 24%] Building C object external/unbound/CMakeFiles/unbound.dir/util/module.c.o
[ 24%] Building C object external/unbound/CMakeFiles/unbound.dir/util/netevent.c.o
[ 25%] Building C object external/unbound/CMakeFiles/unbound.dir/util/net_help.c.o
[ 25%] Building C object external/unbound/CMakeFiles/unbound.dir/util/random.c.o
[ 26%] Building C object external/unbound/CMakeFiles/unbound.dir/util/rbtree.c.o
[ 26%] Building C object external/unbound/CMakeFiles/unbound.dir/util/regional.c.o
[ 27%] Building C object external/unbound/CMakeFiles/unbound.dir/util/rtt.c.o
[ 27%] Building C object external/unbound/CMakeFiles/unbound.dir/util/storage/dnstree.c.o
[ 28%] Building C object external/unbound/CMakeFiles/unbound.dir/util/storage/lookup3.c.o
[ 28%] Building C object external/unbound/CMakeFiles/unbound.dir/util/storage/lruhash.c.o
[ 29%] Building C object external/unbound/CMakeFiles/unbound.dir/util/storage/slabhash.c.o
[ 29%] Building C object external/unbound/CMakeFiles/unbound.dir/util/timehist.c.o
[ 30%] Building C object external/unbound/CMakeFiles/unbound.dir/util/tube.c.o
[ 30%] Building C object external/unbound/CMakeFiles/unbound.dir/util/ub_event.c.o
[ 31%] Building C object external/unbound/CMakeFiles/unbound.dir/util/winsock_event.c.o
[ 31%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/autotrust.c.o
[ 31%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_anchor.c.o
[ 32%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/validator.c.o
[ 32%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_kcache.c.o
[ 33%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_kentry.c.o
[ 33%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_neg.c.o
[ 34%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_nsec3.c.o
[ 34%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_nsec.c.o
[ 35%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_secalgo.c.o
/home/myHome/electroneum/external/unbound/validator/val_secalgo.c: In function ‘verify_canonrrset’:
/home/myHome/electroneum/external/unbound/validator/val_secalgo.c:637:35: error: dereferencing pointer to incomplete type ‘EVP_MD_CTX {aka struct evp_md_ctx_st}’
  ctx = (EVP_MD_CTX*)malloc(sizeof(*ctx));
                                   ^~~~
/home/myHome/electroneum/external/unbound/validator/val_secalgo.c:669:2: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’ [-Wimplicit-function-declaration]
  EVP_MD_CTX_cleanup(ctx);
  ^~~~~~~~~~~~~~~~~~
external/unbound/CMakeFiles/unbound.dir/build.make:1430: recipe for target 'external/unbound/CMakeFiles/unbound.dir/validator/val_secalgo.c.o' failed
make[3]: *** [external/unbound/CMakeFiles/unbound.dir/validator/val_secalgo.c.o] Error 1
make[3]: Leaving directory '/home/myHome/electroneum/build/release'
CMakeFiles/Makefile2:236: recipe for target 'external/unbound/CMakeFiles/unbound.dir/all' failed
make[2]: *** [external/unbound/CMakeFiles/unbound.dir/all] Error 2
make[2]: Leaving directory '/home/myHome/electroneum/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/myHome/electroneum/build/release'
Makefile:67: recipe for target 'release-static' failed
make: *** [release-static] Error 2

**Comment by DeanCole** [comment]
What version of openssl do you have installed?
