### ISSUE TITLE
Mobile game isn't paying out 

### ISSUE THREAD

**Issue by ghost** [electroneum/electroneum#212]
I've been playing the mobile game for a few days now and I haven't received anything in my wallet yet.  Is there any way of viewing the source code for the mobile game either android or iOS?  Thanks!  Great coin btw!

**Comment by Mr-Kumar-Abhishek** [comment]
I am searching for the source code of the app as well

**Comment by electroneumRepo** [comment]
Mobile miner does pay out - just be patient!
