### ISSUE TITLE
Unable to download Blockchain.raw

### ISSUE THREAD

**Issue by ETN-A** [electroneum/electroneum#214]
For the past few days the [regular URL](https://downloads.electroneum.com/blockchain.raw) has been returning:

> This XML file does not appear to have any style information associated with it. The document tree is shown below.
`<Error>`
`<Code>AccessDenied</Code>`
`<Message>Access Denied</Message>`
`<RequestId>DAE65F63C3608981</RequestId>`
`<HostId>`
`co2E+sLxM1iz2VsgyZ+e7kw0w9wcsmHGD8140Roe1FQmHD0M5m186sQy1dRjsDuHUKhri2dEF88=`
`</HostId>`
`</Error>`

**Comment by BegaMutex** [comment]
Here's a copy (height 249032) until the official one is available again.
https://s3-eu-west-1.amazonaws.com/etnblockchain/blockchain_271793.raw

Remember to do --verify 1 for safety when importing.
