### ISSUE TITLE
Issue about Mobile miner

### ISSUE THREAD

**Issue by tadangky** [electroneum/electroneum#215]
I'm a Mobile miner

The first time when I got 10 ETN from Mobile application. 10 ETN will send to my wallet.
But now when I got > 70 ETN, nothing happen.
I already write comment on Google play store but nobody reply.
Please check it.

**Comment by steemandlinux** [comment]
https://twitter.com/electroneum

**Comment by Mr-Kumar-Abhishek** [comment]
Same issue . Where is the app source code anyways ?

**Comment by Unyxos** [comment]
The mobile miner pending balance payments are gradually processed, don’t worry, you will receive your ETN, and... I don’t think the app is open source ;)
