### ISSUE TITLE
CryptoNightV7 - Which version will Electroneum fork to?

### ISSUE THREAD

**Issue by easyhash** [electroneum/electroneum#216]
Could you please post some information on which version we should use in multi-hashing for nodejs ?

`hash = cryptoNight(convertedBlob, ?); `

**Comment by QwertyJack** [comment]
No plan to fork, at least no schedule now.

**Comment by BegaMutex** [comment]
Of course its forking. No blockheight announced yet. I've forwarded this issue on to the devs OP.

**Comment by GoldKimber-Mining** [comment]
Well, that's clear as mud.  One of you is wrong.  So which is it?  Are
either of you actually working in a official ETN capacity to be announcing
forks?  Could we hear from someone who is?  (mean no disrespect to either
you)

**Comment by BegaMutex** [comment]
None taken. Yes the ETNv2 update is being worked on by the dev team. You can even look at pr189 for some of the changes they have been looking at for it.

As i said, no date has been given yet.

**Comment by andrepatta** [comment]
CryptoNight variant 1.

It should be something like `hash = cryptoNight(convertedBlob, 1);` in your code.
