### ISSUE TITLE
Is 8.2B ETN premined for mobile mining?

### ISSUE THREAD

**Issue by lkelemen** [electroneum/electroneum#223]
The first block (actually the 2nd) has 12.6 billion ETN as a reward. AFAIK from this amount 4.4billion went for the ICO so is the 8.2B ETN the premined amount for mobile mining?

https://blockexplorer.electroneum.com/search?value=1

**Comment by electroneumRepo** [comment]
The ICO was 4.656B including bounty and bonus ETN payments which leaves just under 8 Billion in mobile mining payouts.
However, this is not the place for this type of comment - only code comments and coding issues, bugs and codebase discussion should take place on Github.
Thanks!
