### ISSUE TITLE
CPU MINING ERROR

### ISSUE THREAD

**Issue by cryptoconversations** [electroneum/electroneum#226]
hi 
I downloaded the direct CPU miner on my windows 8 and started the cmd . I am 622 bloacks away and 0 days behind since quiet a while. This is not progressing what should I do? Any help would be great. Thanks.

**Comment by ghost** [comment]
Tell us what comes up when you type in the daemon

1. sync_info
2. status

Also do set_log 2 in the daemon and tell us if you see anything that looks like it's not working (any errors).

**Comment by cryptoconversations** [comment]
Got it working. thank you! Closed the electroneummd and restarted it. And it synchronized.

Sent from Yahoo Mail on Android 
 
  On Tue, May 8, 2018 at 7:27 PM, Chris Harrison<notifications@github.com> wrote:   
Tell us what comes up when you type in the daemon
   
   - sync_info
   - status

Also do set_log 2 in the daemon and tell us if you see anything that looks like it's not working (any errors).

**Comment by ghost** [comment]
Happy mining! @DeanCole

**Comment by cryptoconversations** [comment]
Thanks 😁
