### ISSUE TITLE
Freaking out - Is the ETN Web wallet hacked?

### ISSUE THREAD

**Issue by ghost** [electroneum/electroneum#227]
@electroneumRepo please help. I had 55,960 ETN in my web wallet and now there is only 6,980 ETN Did the web wallet got hacked? If it did please let us all know.

I was trying to move them to a paper wallet and it said transaction pending for 4 days and now it only shows 6,980 ETN. Where is the rest of my ETN?

I need my private keys to see what happened to my coins. What are you doing hiding our private keys?

**Comment by BegaMutex** [comment]
No of course it's not hacked. 

The ETN Repo is not the place for account queries. Raise a support ticket. https://support.electroneum.com

**Comment by electroneumRepo** [comment]
Hi,

Yes this is not the place for these queries, please raise a support ticket and the support team will assist you.
