### ISSUE TITLE
Electroneum windows ver is not working anymore

### ISSUE THREAD

**Issue by nasopraso** [electroneum/electroneum#23]
Hi

Today before couple of minuets I can't start anymore electroneumumd and wallet cli  (Windows 7)

It just said that is not compatible with this OS ver.... since yesterday was working fine

**Comment by electroneumRepo** [comment]
Hi,

Could you a screen shot of what error messages shows up.

Can you also download the binaries again and see if they work.

**Comment by krismin01** [comment]
![image](https://user-images.githubusercontent.com/34316016/33684333-a0f35d8c-dad6-11e7-93a6-b090976f9fb8.png)
not working either

**Comment by nasopraso** [comment]
It said that is not workable 32 or 64 bit windows application...but anyway I found the problem - one of my hard drive have some errors exactly where is written the cli wallet. So I just delete the application and download it again and now is ok
Thanks

**Comment by krismin01** [comment]
i wasn't patient enough done now.
