### ISSUE TITLE
electroneum-wallet-cli issue

### ISSUE THREAD

**Issue by ghost** [electroneum/electroneum#230]
Hi there
I,m Linux OS user i have issue with syncing electroneum-wallet-cli , daemon running well without problem and its now in block 271782 , but when i run electroneum-wallet-cli and begin refreshing the wallet its stopping the daemon and giving bus error . i will attach image file about issue but dont care about block same issue i tweet it in your twitter account so many time and now here please fix it .
![photo_2018-05-06_00-08-06](https://user-images.githubusercontent.com/39014730/39667826-ca8e1f90-50c6-11e8-9d8a-67d79266c28e.jpg)
Best regards
        benistiman

**Comment by ArshaParsa** [comment]
Hi.
I have the same problem with my wallet when i want to start mining

"" Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address. ""
Please help us to solving this issue

Thanks
