### ISSUE TITLE
Blockchain download consumes all bandwidth

### ISSUE THREAD

**Issue by fedecaccia** [electroneum/electroneum#231]
How can I limit the bandwith used by electroneum downloading the blockchain?

**Comment by ontje-dev** [comment]
using ```electroneumd --help``` shows some arguments you could pass when starting your daemon:

```
  --block-sync-size arg (=0)            How many blocks to sync at once during
                                        chain synchronization (0 = adaptive).

  --out-peers arg (=-1)                 set max number of out peers`

  --limit-rate-up arg (=-1)             set limit-rate-up [kB/s]

  --limit-rate-down arg (=-1)           set limit-rate-down [kB/s]

  --limit-rate arg (=-1)                set limit-rate [kB/s]
```
i am using: ```--out-peers=4 --limit-rate-up=32 --limit-rate-down=384 --block-sync-size=5```

**Comment by r7avi** [comment]
use command - limit 1024
which will make deamon to use data speed below 1mbps (up/dwn)


or try the below command for faster sync
--out-peers=2 --limit-rate-up=32 --limit-rate-down=2048 --block-sync-size=10
