### ISSUE TITLE
RPC Won't start

### ISSUE THREAD

**Issue by felix920506** [electroneum/electroneum#232]
RPC won't start and gets stuck at loading key files

**Comment by Unyxos** [comment]
What command are you using to launch rpc wallet ? I’m working with it since weeks and never had this issue

**Comment by felix920506** [comment]
./electroneum-wallet-rpc --wallet-file [x] --password [x] --daemon-address 127.0.0.1:26968 --rpc-bind-port 26969 --disable-rpc-login
it just gets stuck at 2018-05-09 14:41:14.052	    7f41bc220740	WARN 	wallet.wallet2	src/wallet/wallet2.cpp:2497	Loaded wallet keys file, with public address: etnkGS7zyhccfWvEaq5RC2A6pmzmxRw2d6hfGyeoSP6sNz5o2JpKiizXd7mLBVotzMgbGjEFvkvNj9ucqndM9byNA6o9X64pEa

**Comment by Unyxos** [comment]
I'm using this : 
`./electroneum-wallet-rpc --daemon-port 26968 --wallet-file originalwallet --password xxxx --rpc-bind-ip 0.0.0.0 --rpc-bind-port 26969 --confirm-external-bind --disable-rpc-login`

and it's working fine..
Are you sure you have the latest release etc? That issue looks strange.

Also, you can try to launch the wallet-rpc with `--log-level 2`, you might get more infos

**Comment by BegaMutex** [comment]
I had similar issue when a previous rpc .login file wasnt removed properly after closing earlier session. Might be worth checking.
