### ISSUE TITLE
Version 2.0.0.0 is not set as a Unix Executable in MacOS when downloaded

### ISSUE THREAD

**Issue by h4nkyn** [electroneum/electroneum#237]
When the _electroneum-macOS-x64-v2.0.0.0.tar.bz2_ is downloaded and uncompressed from the download page, the files are not Unix Executables and need to be converted through Terminal first.

**Comment by ETN-A** [comment]
Yes, found the same thing too... Initially threw up a "Permissions denied" even though (having checked) all permissions (file/folder) were as should be...

Fixed it with `chmod 755` but `chmod +x` would likely : ) do it, too. [This is a nice write-up](https://askubuntu.com/a/932719) for anyone interested in the difference.


**EDIT: CORRECT BINARIES HAVE NOW BEEN UPLOADED!**

**Comment by ghost** [comment]
We just re-uploaded the binaries with the correct permissions. They should run without any issues now. Can you please confirm this for us?
https://github.com/electroneum/electroneum/releases/download/v2.0.0.0/electroneum-macOS-x64-v2.0.0.0.tar.bz2

**Comment by ETN-A** [comment]
YES, just tried: all good! (But you probably knew that ;)) THANK YOU for the prompt "fix"!
