### ISSUE TITLE
Blockchain not syncing after upgrade

### ISSUE THREAD

**Issue by ikeman32** [electroneum/electroneum#238]
I have upgraded to the latest release ahead of the scheduled upgrade for the 30th, but the blockchain is not syncing. Everything starts up just fine but stalls at synchronization started. I am using Linux Mint 17.3 with the latest kernel release. Everything was working fine before the upgrade and now not so much. All other functions appear to work normally it just won't sync.

**Comment by DeanCole** [comment]
Please could you stop the daemon and then delete the `p2pstate.bin` file located in your electroneum data directory, On linux this would be `~/.electroneum`

Once deleted, start the daemon up again and see if it starts syncing

**Comment by ikeman32** [comment]
I've done that and deleted the data directory, then imported from the last time i backed up the blockchain.

**Comment by ikeman32** [comment]
It's apparently syncing now, just at a snail's pace from previous version.

**Comment by crosser306** [comment]
I got the same issue. After download the latest release at [https://github.com/electroneum/electroneum/releases/tag/v0.11.0.0-revert] I had deleted the db and start the sync from the beginning. However it went up to block 227874 and stuck there.

FYI, I am on Windows 10.

**Comment by DeanCole** [comment]
@crosser306 That's not the latest version. The latest version can be downloaded from [here](https://github.com/electroneum/electroneum/releases/tag/v2.0.0.0)
