### ISSUE TITLE
Error Code: 3080

### ISSUE THREAD

**Issue by finleyexp** [electroneum/electroneum#239]
I just set up my first electroneum wallet on my.electroneum.com. Had no issues setting the account or accessing it through the computer web browser. I downloaded the app from google play store. I can get all the way to insert pin, then I get error code 3080 signin took too long.

So, anyone know how I can get electroneum app to work for testing the mobile mining features?

**Comment by finleyexp** [comment]
@electroneumRepo why is this issue closed? I've gotten no response from you or anyone on dev about the error code and I still can't get electroneum to work on the device.

**Comment by electroneumRepo** [comment]
The Github repository is a place to open issues regarding the Blockchain i.e. the blockchain daemon, wallet cli / rpc. Any issues regarding my.electroneum.com and the mobile app should be raised as a support ticket on support.electroneum.com
