### ISSUE TITLE
wallet-rpc randomly detaches from the daemon

### ISSUE THREAD

**Issue by Dwynr** [electroneum/electroneum#24]
Hey,

does anybody know why the wallet-rpc would randomly detach from the daemon?
After those detaches the wallet-rpc is out of sync and wont sync again untill its restarted.

(and sorry if this is the wrong section/repo)

**Comment by electroneumRepo** [comment]
Hi,

I've never had the occur before.

Could you please post some output of what happens. Screen shots will also be helpful
