### ISSUE TITLE
Error Code: 3080

### ISSUE THREAD

**Issue by finleyexp** [electroneum/electroneum#243]
#239 issue closed without resolution. The error code is still appearing on my device. Picture's blurry but you get the point...

![login_error](https://user-images.githubusercontent.com/18469214/40512418-a6592d64-5f57-11e8-86f6-4c19355df4a2.jpg)

**Comment by Unyxos** [comment]
It’s actually really simple, this is not mobile miner support, issues on GitHub should only be about possible issues with daemon, CLI wallet, etc.

**Comment by finleyexp** [comment]
@Unyxos This is the github for Electroneum? As in the place where dev is taking place?

The mobile miner is touted as a "major" feature of Electroneum. If I can't get help from the dev team, where do you suggest I go for help with the Electroneum mobile miner?

**Comment by electroneumRepo** [comment]
The Github repository is a place to open issues regarding the Blockchain i.e. the blockchain daemon, wallet cli / rpc. Any issues regarding my.electroneum.com and the mobile app should be raised as a support ticket on support.electroneum.com
