### ISSUE TITLE
Critical Upgrade??!!

### ISSUE THREAD

**Issue by cannonlinc** [electroneum/electroneum#244]
https://electroneum.com/2018/05/17/critical-electroneum-network-upgrade/

I have no idea what all of this means, or how to do any of the steps on github.

I am just doing plain old ETN "psuedo" mining on my Samsung phone, App version 2.3.4.

Do i need to upgrade my wallet or something? If so, how (github stuff doesn't make any sense to me).

**Comment by marki555** [comment]
If you are using the mobile app to "mine" and using online wallet, you don't need to do anything.

**Comment by cannonlinc** [comment]
Ok, thanks for the quick reply.

Sent from Mail for Windows 10
