### ISSUE TITLE
0 Balance - Can't restore wallet

### ISSUE THREAD

**Issue by kopspa** [electroneum/electroneum#247]
I have an issue: blockchain in full synced in electroneumd, i have the wallet opened and still 0 balance.
I have sent about 5000 ETN, the transaction is 

60040524011baaf4c322e7eaa88199929291425e395113f65e338f253e529355

i've tryed to import my keys (printed by electroneum-wallet-cli) but

wallets ~ # /home/coins/etn-bin/electroneum-wallet-cli --generate-from-keys ETNRO
Electroneum 'May 2018' (v2.0.0.0-release)
Logging to /home/coins/etn-bin/electroneum-wallet-cli.log
Standard address: etnkGQwxkRegTpEPyfyR5T9qyvuoc9pSCfMLoYy1dasH6UcFBDVgNQWho96h7MXzciFh9w2jLwewzQWrVubU3QLS64uqQQusmp
Secret spend key: ***
Secret view key: ***
Error: failed to verify spend key secret key

the keys are copied/pasted from the command viewkey on my wallet!

why i can't import this wallet? i have always imported wallets with this procedure without problems
please help, thanks!

**Comment by eybeestudios** [comment]
i think i ran into the same thing of issue, i created a fresh offline wallet with the cli and have a transaction already confirmed in the blockchain, but the transaction never showed up in my wallet...

**Comment by ghost** [comment]
On one hand you say you've opened the wallet and on the other hand you show us a log that says 'failed to verify spend key secret key'. The key must have been written wrong. If you manage to open a wallet in the cli, it could be that your refresh from height is wrong, in which case you should write:

set refresh-from-block-height 0
rescan_bc
