### ISSUE TITLE
 [46.101.40.29:39384 INC]  peer claims higher version that we think - we may be forked from the network and a software upgrade may be needed

### ISSUE THREAD

**Issue by TheBudda** [electroneum/electroneum#254]
![screenshot blockchain synced stuck at height 307517-307516-2018-06-02 22 52 21](https://user-images.githubusercontent.com/16983376/40881159-243197aa-66b8-11e8-97ae-5a36dea480d8.png)
![screenshot electroneumd blockchain synced 2018-06-02 21 27 57](https://user-images.githubusercontent.com/16983376/40881160-244c8218-66b8-11e8-9f10-d521f857b58f.png)

Hi electroneum, I have this issue!  My pool runs on Ubuntu 16.04. I downloaded the new binaries. I am now getting this error! ( [46.101.40.29:39384 INC]  peer claims higher version that we think - we may be forked from the network and a software upgrade may be needed) I have tried 3x adding your new binaries (May 2018) version. I have also resynced the whole blockchain. You can see in my screenshots! Height 307517 / 307516 stuck!

Height: 307517/307516 (100.0%) on mainnet, not mining, net hash 1.51 GH/s, v6, up to date, 7(out)+7(in) connections, uptime 0d 0h 1m 16s
2018-06-02 21:54:03.117 [P2P9]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:303     [109.129.57.191:26967 OUT] Sync data returned a new top block candidate: 307517 -> 309677 [Your node is 2160 blocks (3 days) behind]
SYNCHRONIZATION started
2018-06-02 21:54:23.526 [P2P6]  WARN    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:273     [159.203.28.200:51110 INC]  peer claims higher version that we think - we may be forked from the network and a software upgrade may be needed

NOT SYNCING!! https://cryptoblock.uk https://etn.cryptoblock.uk

![screenshot electroneumd 2018-06-02 21 27 57](https://user-images.githubusercontent.com/16983376/40881099-aea3ff38-66b6-11e8-9242-bd62881ee2a4.png)

I look forward to your reply and help with this issue

Kind regards
TheBudda

**Comment by BH-Alex** [comment]
Same message here.

**Comment by electroneumRepo** [comment]
This is simply another node reporting a higher block. This is incorrect. The correct block height can be found on the block explorer.

If you change to a higher log level you can see the details of the validation taking place, the node is reporting a higher block but with the wrong block version (V1) but V6 is required hence it does not listen to that node and never syncs its data.

**Comment by shopglobal** [comment]
It's not us

**Comment by mstrickk** [comment]
I got the same message and took the time to create an account on the official website and send them a ticket. I got a bogus response stating they don't support desktop mining, completely skipping the word WALLET in the email.

I see here you got a little better response from electroneumrepo. So Repo, what do we do to fix this issue?

[1;31m[104.225.223.32:46160 INC]  peer claims higher version that we think - we may be forked from the network and a software upgrade may be needed[0m

**Comment by Giusepp3** [comment]
Also I have the same problem, tried to update but it shows me error
<img width="1280" alt="schermata 2018-06-16 alle 16 02 33" src="https://user-images.githubusercontent.com/3754641/41499343-deeb6474-717e-11e8-81c6-7265b52aafda.png">
<img width="1280" alt="schermata 2018-06-16 alle 16 02 37" src="https://user-images.githubusercontent.com/3754641/41499344-df0880cc-717e-11e8-9bd2-5d60cd604c88.png">
<img width="1280" alt="schermata 2018-06-16 alle 16 02 59" src="https://user-images.githubusercontent.com/3754641/41499345-df22eee4-717e-11e8-85e7-d190cc64b80f.png">

**Comment by Giusepp3** [comment]
I downloaded the miner 2 days ago and did the sync with the blockchain for the first time. This morning I've tried to mine and noticed this error.

**Comment by chrisleung1985** [comment]
@electroneumRepo 

![image](https://user-images.githubusercontent.com/40571444/41856316-55cb814c-78c7-11e8-8c5d-88bc6be40c47.png)

Could you please advise how to fix it?

**Comment by phlibby** [comment]
Sorry but this is ridiculous having to rework the files and take a week to fix this, not knowing for sure if it will really resolve the problem! We only have 3 days wasted on this project. We are pulling out and finding something else to mine!

**Comment by chrisleung1985** [comment]
Please inform us if any solutions could be provide in here, thank you

**Comment by TheBudda** [comment]
@electroneumRepo solved my issue! He told me to change to a higher log level

**Comment by AllenChong** [comment]
issue
