### ISSUE TITLE
Unable to compile in QT Cannot find SSL

### ISSUE THREAD

**Issue by bonkingbob** [electroneum/electroneum#255]
I'm trying to open and view the code in QT on Mac but it is falling over with the following error:

CMake Error at /usr/local/Cellar/cmake/3.11.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)

Is this an issue in the cmake.txt file or computer related?

**Comment by electroneumRepo** [comment]
You need to have a libssl-dev installed on your machine. Please ensure you have this and the other dependencies installed.
