### ISSUE TITLE
Double Spend Issue

### ISSUE THREAD

**Issue by kopspa** [electroneum/electroneum#256]
Hi
I've lost my coins because of the fork?
I have rescan_bc:

Refresh done, blocks received: 307570                           
Balance: 4923.89, unlocked balance: 4923.89

I have nothing on my transfers:
[wallet etnkGQ]: show_transfers
  307146     in       2018-05-30              4923.89 60040524011baaf4c322e7eaa88199929291425e395113f65e338f253e529355 0000000000000000 - 
Try to transfer my ETN:
[wallet etnkGQ]: transfer priority etnkK41HsyNUvtnBX7hsrn3z9VZquSfUGb5Y1uTxQav8GQn9KNjpucgYa5C9wSb5TndUXBfZwajbmPLTjdEr1WG6Ag1KbzcNi1 4923 999b4e86bd862230d3e39f3a6fce5e10c70008de1816d0b1de292990879b590f
Wallet password: ************
There is currently a 5 block backlog at that fee level. Is this okay?  (Y/Yes/N/No)y
Sending 4923.00.  The transaction fee is 0.80
Is this okay?  (Y/Yes/N/No): y
Error: transaction <714f6e386176acb0f1624172caab47a99943013354ad493b7943967a80c3da0b> was rejected by daemon with status: Failed
Error: Reason: double spend

Why double spend? 
My address is: etnkGQwxkRegTpEPyfyR5T9qyvuoc9pSCfMLoYy1dasH6UcFBDVgNQWho96h7MXzciFh9w2jLwewzQWrVubU3QLS64uqQQusmp

If needed, i can provide my viewkey also
Please HELP!

**Comment by ghost** [comment]
Have you updated your software?

You're behind the network on block 307570. 

Try

Set refresh-from-block-height 0

rescan_bc
