### ISSUE TITLE
cli wallet not working

### ISSUE THREAD

**Issue by ontje-dev** [electroneum/electroneum#258]
Hi
- i created a new fresh wallet with the cli
- send ETN to this wallet
- have the transaction verified and confirmed in the blockchain (checked with viewkey)

wallet not receiving the transcation. rescan_bc stuck at 299913
`[wallet etnjwA]: rescan_bc`
`Starting refresh...`
`Height 299913 / 307889`
then after a while:
`Refresh done, blocks received: 0`
`Balance: 0.00, unlocked balance: 0.00`
`[wallet etnjwA]: status`
`Refreshed 307890/307891, syncing, daemon RPC v1.13`
`[wallet etnjwA]:`

this is just wrong as there are missing a few thousand ETN from this transaction:
[430f89dd040c2f814bf890f0af2a19fa3234b60aa2abf7cac92ab3fca42050c5](https://blockexplorer.electroneum.com/tx/430f89dd040c2f814bf890f0af2a19fa3234b60aa2abf7cac92ab3fca42050c5)

**Comment by ckhatton** [comment]
Same issue here. I didn't upgrade the wallet before the fork. Now that I have, and tried a re-sync, I keep getting the same error.

**Comment by ontje-dev** [comment]
a few more informations: 
- the error happend with a self compiled version on a raspberry pi3

so i switched to ubuntu...
- export DB
- import DB with --pop-blocks 2000
- sync the blockchain
- issue consists... the transaction will not reflect in the wallet!

who else can confirm that there is a severe problem?

**Comment by ontje-dev** [comment]
---- UPDATE --- 

after reading this issue: https://github.com/electroneum/electroneum/issues/19

i reload the complete wallet with --restore-deterministic-wallet

- the wallet sync stucked again at 299913
- after a while it jumped to 305xxx and synced every block one by one

the transaction appeared in the wallet as the sync reached the corresponding block.

i recognized that the false sync state come up as the sync-process was jumping 10000 blocks at once and not one by one. could there be a possible bug ?

**Comment by mkrufky** [comment]
@eybeestudios `--restore-deterministic-wallet` did the trick for me.  I saw the same (half second) hang at 299913, followed by a quick sync thereafter.  Thank you!

**Comment by DeanCole** [comment]
Please can you post the output of "set" from the cli.

There is a value in here that is used when the wallet is scanning the blockchain for transactions.

Basically, when "resyncing" it will start looking for transactions starting from that block height, by restoring the wallet it automatically scans the whole blockchain from block 0.
The "jumps" as you call them is just the wallet skipping over the blocks, when it gets to the block it is set to scan from it goes slower as it is checking the transactions against the wallet to match them up.

**Comment by DrEhsan** [comment]
why you are trying this on a dead coin?

**Comment by ghost** [comment]
In the cli write:
set refresh-from-block-height 0
rescan_bc
