### ISSUE TITLE
Wrong currency name in fee

### ISSUE THREAD

**Issue by noraj** [electroneum/electroneum#26]
I think `monero` need to be replaced by `electroneum`.

```
[wallet] fee
Current fee is 0.01 monero per kB
12 block (12 minutes) backlog at priority 1
No backlog at priority 2
No backlog at priority 3
12 block (12 minutes) backlog at priority 4
```

**Comment by electroneumRepo** [comment]
Hi,

Thanks for pointing this out.

This is something I'm sure will be fixed in our next release.

**Comment by crazy-logic** [comment]
please see https://github.com/electroneum/electroneum/pull/93 for fix.
