### ISSUE TITLE
Daemon stucked on alt.chain (lower height) and failed to restart

### ISSUE THREAD

**Issue by minerrocks** [electroneum/electroneum#263]
Daemon stucked on alt.chain (lower height) and failed to restart

We run the daemon with recommended patch from
https://github.com/electroneum/electroneum/pull/249/files

Last height we had: 309365
While some part of other pools had: 309,522

The log from restart attempt:
`2018-06-09 21:41:38.571 7fc684ffa740 INFO global src/cryptonote_core/cryptonote_core.cpp:324 Loading blockchain from folder /home/ubuntu/.electroneum2/lmdb ... 2018-06-09 21:41:39.230 7fc684ffa740 ERROR txpool src/cryptonote_core/tx_pool.cpp:326 internal error: kept_by_block=0, kei_image_set.size()=1 txin.k_image=<7dbd8ed9fafb6ba085d38206d610ebf9b6b825e71e15ac06aba054b9eff74411> tx_id=<aadf014b803e0a2ef9c89f71dec5101e7940c3478016a30e943d76ff5353a7e3> 2018-06-09 21:41:39.230 7fc684ffa740 FATAL txpool src/cryptonote_core/tx_pool.cpp:1057 Failed to insert key images from txpool tx 2018-06-09 21:41:39.230 7fc684ffa740 ERROR cn src/cryptonote_core/cryptonote_core.cpp:410 Failed to initialize memory pool`

**Comment by Cideg** [comment]
If only the only mistake would be ^ ^ Download the blockchain.raw down and let it run through. The Demon is extremely busy with errors currently.
https://github.com/electroneum/electroneum/pull/257/commits/5dca9bf7406fe561bd254c2aae0f543e8ba8d671

wget https://downloads.....
./electroneum-blockchain-import --input-file ./blockchain.raw

2018-06-10 07:27:28.739 [P2P5]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:303     [86.124.26.81:50636 INC] Sync data returned a new top block candidate: 309814 -> 313196 [Your node is 3382 blocks (4 days) behind]
SYNCHRONIZATION started
2018-06-10 07:28:47.948 [P2P6]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:303     [86.124.26.81:50669 INC] Sync data returned a new top block candidate: 309815 -> 313196 [Your node is 3381 blocks (4 days) behind]
SYNCHRONIZATION started
2018-06-10 07:31:15.984 [P2P6]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:303     [86.124.26.81:50735 INC] Sync data returned a new top block candidate: 309815 -> 313196 [Your node is 3381 blocks (4 days) behind]
SYNCHRONIZATION started

**Comment by minerrocks** [comment]
Yes, we have restored pool operations by redownloading blockchain raw. 
But it is very inconvinient for pool operator to go downtime for a long time.
We had two daemons, and both were stucked, and were not able to restart.

**Comment by ckhatton** [comment]
This is really annoying, as it keeps happening for me since the fork and importing the `blockchain.raw` file is super slow at the moment!

I wonder if because I updated the wallet after the fork, it is part of the problem here? :octocat:

**Comment by electroneumRepo** [comment]
You can use `--verify 0` which can help to speed up the import

**Comment by ckhatton** [comment]
@electroneumRepo Thanks! Someone on reddit sent me this...

    ./electroneum-blockchain-import --prep-blocks-threads 3 --fast-block-sync 1 --db-sync-mode fastest:async:10000 blockchain.raw

I will peg on `--verify 0` and that should be fine, right?

**EDIT:** Yeah, it seems to be wizzing through the blocks now.

**Comment by andrepatta** [comment]
The following PR would solve this issue automatically:

https://github.com/electroneum/electroneum/pull/261

Still, importing the blockchain.raw file is the only available option now (although it's kind of annoying to apply).
