### ISSUE TITLE
CMake Error at cmake/FindMiniupnpc.cmake:51 (if):   if given arguments:

### ISSUE THREAD

**Issue by xslugx** [electroneum/electroneum#265]
CMake Error at cmake/FindMiniupnpc.cmake:51 (if):
  if given arguments:

    "GREATER" "10" "OR" "EQUAL" "10"

  Unknown arguments specified
Call Stack (most recent call first):
  external/CMakeLists.txt:39 (find_package)
[CMakeOutput.log](https://github.com/electroneum/electroneum/files/2129333/CMakeOutput.log)
[CMakeError.log](https://github.com/electroneum/electroneum/files/2129334/CMakeError.log)

**Comment by ghost** [comment]
This is related to your computer and not the cmake files by the looks of things(CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'). We don't have time to fix things like this. However we are releasing a new codebase very soon (3.1.0.0) that has reworked this file and many other things. You should try that. 

Also please make sure you visit the README/build documents and install all of the required dependencies at the appropriate version. Cheers.
