### ISSUE TITLE
http://127.0.0.1:26968/get_height 404 not found

### ISSUE THREAD

**Issue by steemandlinux** [electroneum/electroneum#268]
How to use electroneumd rpc server?  It`s not work for me.

url = 'http://127.0.0.1:26968/get_height'
headers={ 'Content-Type': 'application/json' }    
session = requests.Session()
r = session.post(url, headers = headers)
print(r)

<Response [404]>

launched the server as electroneumd --data-dir=/bla/bla/bla

**Comment by steemandlinux** [comment]
wallet-rpc also works for me.

**Comment by copayasia** [comment]
Try use "http://127.0.0.1:26968/json_rpc" with headers and body
```
{
"jsonrpc":"2.0",
"id:"0",
"method":"get_info"
}
```

**Comment by steemandlinux** [comment]
```
def create():
    
    url = 'http://127.0.0.1:26968/get_height'
    headers={ 'Content-Type': 'application/json' }   
    req = {
            "jsonrpc":"2.0",
            "id":"0",
            "method":"get_info"
           }
    post_data = json.dumps(req).encode(); 
    session = requests.Session()
    r = session.post(url, headers = headers, data = post_data)
    return r
    
print(create())
```
<Response [404]>

**Comment by mbIkola** [comment]
electroneum daemon implements /getheight  http handler (without underscore). 
Curl example:
``` 
# curl -vv -X GET http://127.0.0.1:26968/getheight 
* Connection #0 to host 127.0.0.1 left intact
{ "height": 333888, "status": "OK" }
```
![image](https://user-images.githubusercontent.com/4107999/42821624-a34efc3e-89e1-11e8-8bec-7253c9f2920d.png)

You can also retrieve current daemon height and by calling json_rpc method "get_info" 
code snippet: 
```python
import json;
import requests;

def get_info():

    url = 'http://127.0.0.1:26968/json_rpc'
    headers={ 'Content-Type': 'application/json' }
    req = {
            "jsonrpc":"2.0",
            "id":"0",
            "method":"get_info"
           }
    post_data = json.dumps(req).encode();
    session = requests.Session()
    r = session.post(url, headers = headers, data = post_data)
    return r

def get_height():
    url = 'http://127.0.0.1:26968/getheight'
    session = requests.Session()
    r = session.get(url)
    return r


print(get_info().text)
print(get_height().text)
```

**Comment by andrepatta** [comment]
Thanks for your help @mbIkola !

Seems that your issue is solved @steemandlinux if you follow the suggestion above?
