### ISSUE TITLE
When the fuc$ you going to make a QT wallet?

### ISSUE THREAD

**Issue by auroracoin** [electroneum/electroneum#271]
Sorry but we have been waiting patiently since launch. How much longer and frustrated do you want us to get.  Well?

**Comment by Yobleed** [comment]
Can you please be a little bit more respectful to the team?

**Comment by bradburycode** [comment]
auroracoin = d*ck

**Comment by mannie65** [comment]
@auroracoin With that attitude - I would be putting any requests from you at the bottom of the list - if not in the bin. Grow up !!!

**Comment by auroracoin** [comment]
Yobleed  THE TEAM HAS BEEN DISRESPECTFUL TO US. WHAT DO YOU EXPECT ?

**Comment by shopglobal** [comment]
Hey Mannie

**Comment by auroracoin** [comment]
Well still waiting.  All other coins, cryptonote, have working GUI wallets on launch. Now you see why I'm mad.

**Comment by Unyxos** [comment]
Make one if you need it so badly ¯\_(ツ)_/¯ that’s what I’m doing
