### ISSUE TITLE
problem with the transaction

### ISSUE THREAD

**Issue by T1000E** [electroneum/electroneum#275]
Hello, the problem with the transaction
![444](https://user-images.githubusercontent.com/41141056/42617281-5eec01c2-85db-11e8-91d5-5f93c6ad1f9c.jpg)
![222](https://user-images.githubusercontent.com/41141056/42617282-5f13ac2c-85db-11e8-80b0-4ddb776d88ea.jpg)
![333](https://user-images.githubusercontent.com/41141056/42617283-5f3a89be-85db-11e8-925a-9ef13537f43d.jpg)
![111](https://user-images.githubusercontent.com/41141056/42617284-5f67b2ae-85db-11e8-902d-5c3377e2615d.jpg)

 from desktop wallet in the web wallet on the official website. I sent transactions from the desktop wallet, they wrote off my wallet. and hung in the air, in the blockchain they are not. They did not reach the purse. Help to solve the problem.!
tx: c12d8a3c15ca090c27dcd06fc0a411403eb44bad835bfbf10023e0bed1d22191
tx: b02dfe2eaef6187f085c2a711d81527ea1a010dc8c02d79eb0722079a82026ac
tx: d49d1cfc4f1d68961123e5d7c6852a5e5b360e1b505415684363a5169b7d76d6
tx: 0637f997fcf6d46873ea704fb35491956b33cbfd8c1b183fc201bc4300fb9dea

network is synchronized, the last block is No. 326499
there is a suspicion that something is wrong with the synchronization. But how to solve this problem, I do not know

all of them were sent to this purse address:

etnk3UGRnsyVxHdyMmqBz72hvdNuGtdyV5yVcFstVmd8gXgaUWNcqaXeAgXvR61y9MY7NnDzBjXQUR4smvR4bFKs9uAzB2jXBV

**Comment by steemandlinux** [comment]
Not official GUI?

**Comment by T1000E** [comment]
https://github.com/XzenTorXz/ElectroneumGUIWallet/releases  


It seems that I do not add network blocks, I'm stuck on 326499 block. The purse writes that the synchronization is 100%


>Пятница, 13 июля 2018, 15:57 +07:00 от steemandlinux <notifications@github.com>:
>
>Not official GUI?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

Антон
