### ISSUE TITLE
CryptoNight ASIC to CryptoNight v7 to be ASIC resistant

### ISSUE THREAD

**Issue by noraj** [electroneum/electroneum#278]
Any plan to move from CryptoNight ASIC to CryptoNight v7 to be ASIC resistant?

**Comment by electroneumRepo** [comment]
Hi,
There are currently no plans to make Electroneum ASIC resistant in the future.

**Comment by noraj** [comment]
@electroneumRepo That's why everyone left the ship and the currency is dying.

Electroneum was loved because of its potential profit, now that is the last thing you want to mine + you launched this non-sense false mobile miner for marketing purpose.

Now electroneum is one of the last Cryptonight currency.
https://www.cryptunit.com/

**Comment by lkelemen** [comment]
I for one didn't leave the ship. I buy instead of GPU/CPU mining and wait. This is not a get rich quick coin.

**Comment by noraj** [comment]
Yeah but instead of having a decentralized hash rate power (from tons of people mining) you'll have like one or two huge mining farm with thousands of ASIC server, so the hash rate power will be highly concentrated. That's not the purpose of a blockchain and this is dangerous.
Not being ASIC proof is a plague for a lot of reasons.

**Comment by lkelemen** [comment]
Do you have any proof that 1 or 2 companies own all the Asics? Or put it this way - does it mean that when Asic resistance is realised then with GPU mining Nvidia and Amd will rule the blockchain?

**Comment by noraj** [comment]
Let's forget this already abandoned currency...
