### ISSUE TITLE
CLI wallet exe deletes itself on execution

### ISSUE THREAD

**Issue by mskovacic** [electroneum/electroneum#281]
I wanted to use my electroneum cli wallet again after a few months, but to my surprise something went wrong. After executing the electroneum-wallet-cli.exe it just vanished from my folder and my computer (as it isn't in recycle bin and cannot be brought back with CTRL+Z). Then I tried this with the newest cli wallet (2.1.0.0) but the problem stayed the same.

OS: Windows 10 x64
Tried wallet versions: 

- 0.11.0.0 revert
- 2.1.0.0

Additional problems:
electroneumd is synchronising the blockchain much slower after executing electroneum-wallet-cli.exe
Same thing happens with electroneum-wallet-rpc.exe

Powershell output:
PS electroneum-win-x64-v2.1.0.0> .\electroneum-wallet-cli.exe
PS electroneum-win-x64-v2.1.0.0> .\electroneum-wallet-cli.exe
.\electroneum-wallet-cli.exe : The term '.\electroneum-wallet-cli.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spell
ing of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\electroneum-wallet-cli.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\electroneum-wallet-cli.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DeanCole** [comment]
Hi,

If the files are being removed from your machine then this will be your anti-virus doing it.
This is a false-positive.

You will need to go into your anti virus settings and add an exception for the folder containing the binaries.

You should not open the wallet-cli before the daemon is totally synced with the blockchain as this will cause further issues. Wait for the block chain to sync (You will see a message appear in yellow once it is up-to-date), then you can open the wallet cli and do what you need to do. Remember, you MUST leave the daemon open all the time you are using the cli.

I hope this helps.

**Comment by mskovacic** [comment]
It seems that the anti-virus quarantined it. I totally forgot to check it because no notification popped up and hadn't had the problem before.
