### ISSUE TITLE
Daemon don't sync

### ISSUE THREAD

**Issue by Zernez** [electroneum/electroneum#282]
Hello,
i have download the .raw file and imported with "electroneum-blockchain-import", it write all in .mdb, all ok. Now I'm to download the rest of the blocks, but it never connect to any peers.
 I'm trying to adding in the command line "--add-peer" with various IP, but never change. I change the DNS, never change. Change PC with windows, same no connect to peers.
The message shows that it try, fails to connect for timeout for every contact. 
The daemon is the last available v 2.1 and I try to cancel the entire data file of the blockchain yet. OS is Linux. 
Thank you for any solution or advice.

**Comment by andrepatta** [comment]
Hi @Zernez,

Could you please check your firewall settings to see whether your daemon is being blocked?

Thanks

**Comment by Zernez** [comment]
Hi andrepatta, thanks for advice, I have port-mapped my router and I have open port reported in the log file. Now works
