### ISSUE TITLE
libcrypto.so.1.1 not fount

### ISSUE THREAD

**Issue by gusevvasily** [electroneum/electroneum#288]
Hello, @electroneumRepo !

Can't run the script, writes, can't find the library - libcrypto.so.1.1. Downloaded manually, compiled, still does not see. Did ln-s from /usr/local/ssl/openssl in usr/lib/x86_64-linux-gnu, the script also does not start but the error was gone.

Please help, thank you.

**Comment by ghost** [comment]
Can you show us a screenshot or something?
