### ISSUE TITLE
Error: wallet failed to connect to daemon

### ISSUE THREAD

**Issue by koffienl** [electroneum/electroneum#29]
I have setup a wallet and got everything working on my Windows PC. after that I installed a docker (https://hub.docker.com/r/tperalta82/electroneum/) and synced the blockchain.
Now I want to connect the ```electroneum-wallet-cli.exe``` on my windows machine to the docker:
```electroneum-wallet-cli.exe --daemon-address 192.168.2.2:26967```

This results in a error:
```
Error: wallet failed to connect to daemon: 192.168.2.2:26967. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Error: wallet failed to connect to daemon: 192.168.2.2:26967. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
```

Just to rule network issues out, I started the blockhain daemon on my Windows machine and start the wallet-cli without any arguments, works as expected.
Exit the wallet and start with ```electroneum-wallet-cli.exe --daemon-address 192.168.2.190:26967``` where 192.168.2.190 is the ip address of the local windows machine I'm working on. It gives me the same error (failed to connect to daemon).

Also : when the docker is running, I can connect to port 26967 on the target machine, when the docker is stopped the port is closed.

Any help on how to connect over the network to the blockchain daemon ? 

update: I learned I was using the wrong port, the correct port is ```26968```. When I run the daemon on local windows machine I can only connect to localhost, not to the local IP.
The docker file is setup to bind RPC to ip 0.0.0.0 , it won't start when I change it to 127.0.0.1

**Comment by pvanvuuren** [comment]
How did you get it to work?  I'm also getting the same errors.
cheers
Pierre

**Comment by song-liu** [comment]
start your daemon first.
