### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by megolosov** [electroneum/electroneum#290]
Hi,

I am trying to get information about the block from the RPC demon.

method: get_info - it is OK

method: get_block

{'jsonrpc': '2.0', 'error': {'code': -32601, 'message': 'Method not found'}, 'id': ''}

documentation used from
https://getmonero.org/resources/developer-guides/daemon-rpc.html#get_block

help me

**Comment by andrepatta** [comment]
Hi @megolosov ,

Electroneum's Daemon RPC specification is a little bit different from the current Monero APIs.
Please refer to our RPC documentation by following this link: [Daemon RPC Documentation (Community Forum](https://community.electroneum.com/t/daemon-rpc-documentation/6137#heading--getblock)

Thanks,
Andre Patta

**Comment by megolosov** [comment]
Thank you very much. I was looking for that.
