### ISSUE TITLE
Mobile miner payment inconsistencies

### ISSUE THREAD

**Issue by LeadManPL** [electroneum/electroneum#293]
Reporting this potential bug here, because I was not able to find any dedicated bug tracker for ETN mobile miner application.

OS: Android
App version: 2.6.5

Scenario:
* Starting  with new account with 0 (zero) balance.
* Mobile Miner mined 10.17 ETN
* Transferring Funds=10.17 was added to queue
* Transactions list updated with new transaction = 10.17 ETN transferred to my wallet
* Wallet balance in Android Miner shows 10.17 ETN (everything OK)
* Mobile Miner mined 10.03 ETN
* Transferring Funds=10.03 was added to queue
* Transactions list updated with new transaction = **10.02** ETN transferred to my wallet (**WRONG QTY**)
* Wallet balance in Android Miner shows **20.19** ETN (**WRONG QTY**)

I couldn't find any information, that would indicate that any fee is taken from what I Mine, so I assume some bug. Please advise. See attached screenshots for reference:

![2018-11-15 17 37 12](https://user-images.githubusercontent.com/13769051/48795466-48f99f80-ecfd-11e8-85e0-914ad482d4fb.jpg)

![2018-11-15 17 37 22](https://user-images.githubusercontent.com/13769051/48795469-4eef8080-ecfd-11e8-99bc-ec90e8ff74fd.jpg)

**Comment by andrepatta** [comment]
Hi @LeadManPL ,

We really appreciate the level of detail you've put to describe this issue. I would love to see more people reporting problems with same clarity as you did!

I'm forwarding this thread to tech team for review.

**UPDATE:** This has been noted recently and it is due to the mobile miner accruement working at 6 decimal places during mining before being rounded up to 2 decimal places at payout and visuals. It is the underlying system that is doing the rounding and we are working to ensure consistency. 

Many thanks.

**Comment by LeadManPL** [comment]
IMHO payouts shouldn't be rounded up at all.
Since this is Android app I assume you use Java, so how about moving from double (I assume) to BigDecimal ?
Side note: all banking institutions use BigDecimal , and you guys kind of ARE financial institution.

**Comment by ghost** [comment]
Has this been fixed yet do you know? I have asked the team where they're at with looking at this.

**Comment by ghost** [comment]
The team say they are well aware of this issue and are working on a solution to be rolled out in the near future. Thanks for bringing it to our attention.

**Comment by LeadManPL** [comment]
You know, the whole idea of bug tracking systems like github, is to close the ticket **after** bug was fixed - not before...

**Comment by ghost** [comment]
I closed it because you're using the wrong tracking system. This issue section is for the core blockchain repo. In future, to open support requests for the mobile miner, please go here:
https://support.electroneum.com/servicedesk/customer/portal/3/user/login?destination=portal%2F3
