### ISSUE TITLE
Electroneum windows service name

### ISSUE THREAD

**Issue by CryptoSiD** [electroneum/electroneum#3]
The service under Windows (electroneumd --install-service) overwrite the Monero daemon service since they both have the same name.

![github](https://user-images.githubusercontent.com/7094808/33165317-5ddb1f58-d004-11e7-8ae5-8db7ad301dc1.png)

That would be a good idea to rename the service "Electroneum Daemon" instead of "Monero Daemon"

**Comment by electroneumRepo** [comment]
Hi,

Thanks for pointing this out.

This is something that will be fixed in the next release. Apologies for the inconvenience.

**Comment by CryptoSiD** [comment]
The service name hasn't been updated in the latest version :)

**Comment by CryptoSiD** [comment]
Guys... you released another version and the service is still named "Monero Daemon". Please fix this.

It overwrite the monero service and I can't have both.

You said you would fix it in the next version 3 months ago.
