### ISSUE TITLE
Snap remains inactive after start

### ISSUE THREAD

**Issue by davclark** [electroneum/electroneum#30]
Running on Ubuntu 17.10, not sure if I'm missing something, but `snap start electroneum` seems to work, and there is no error in the logs:

```
$ systemctl status -l snap.electroneum.electroneumd.service 
● snap.electroneum.electroneumd.service - Service for snap application electrone
   Loaded: loaded (/etc/systemd/system/snap.electroneum.electroneumd.service; en
   Active: inactive (dead) since Fri 2017-12-08 18:05:59 EST; 59s ago
  Process: 68451 ExecStart=/usr/bin/snap run electroneum.electroneumd (code=exit
 Main PID: 68464 (code=exited, status=0/SUCCESS)

Dec 08 18:05:59 monolith systemd[1]: Starting Service for snap application elect
Dec 08 18:05:59 monolith electroneum.electroneumd[68451]: 2017-12-08 23:05:59.93
Dec 08 18:05:59 monolith electroneum.electroneumd[68451]: Forking to background.
Dec 08 18:05:59 monolith systemd[1]: Started Service for snap application electr
```

It seems to fork and die. The cli also reports it can't connect, so I think the service is truly stopping (i.e., it doesn't look like an issue with reporting from snap / systemd).

Happy to poke around if you want to point me in some direction!

**Comment by Cyper77** [comment]
dont use snap repo, use git repo than make it.

**Comment by crazy-logic** [comment]
I too had an issue with the snap so am going to switch to the git clone method.

**Comment by crazy-logic** [comment]
Actually may have found the issue - go to /etc/systemd/system/snap.electroneum.electroneumd.service and add the following to the bottom. 

[Install]
WantedBy=multi-user.target

that's fixed it for me. 

you'll need to issue a systemctl daemon-reload after and then i would do a reboot. 

run 'ps aux | grep electroneum' to see it it's running after a reboot or 'systemctl status snap.electroneum.electroneumd.service'
