### ISSUE TITLE
Commit author attribution

### ISSUE THREAD

**Issue by selsta** [electroneum/electroneum#302]
Almost every single commit in this repo is a copy of a Monero commit with a changed author.

Please look into git author attribution. You can use the `--author="Author Name <email@address.com>"` flag for that.

If you slightly change a Monero commit so that it applies to Electroneum, please look into https://help.github.com/articles/creating-a-commit-with-multiple-authors/

Thanks! :)

**Comment by andrepatta** [comment]
Hi @selsta,

I would like to thank you for the hint and also apologize for the inconvenience.
We should start using the mentioned `--autor` flag and the multiple authors feature whenever it's applicable. :)

Thank you!

**Comment by selsta** [comment]
@andrepatta Thank you for the quick reply. While you are at it, could you also look into https://github.com/electroneum/wallet-manager-php/issues/1 as the linked issue is a copyright violation.

**Comment by andrepatta** [comment]
@selsta I will definitely check that out and forward the message to the responsible team.

(I wasn’t even aware that we have this repo)

Thanks once again for pointing that out!
