### ISSUE TITLE
Electroneum build fails under MSYS2 due to openssl/unbound versions

### ISSUE THREAD

**Issue by wolstech** [electroneum/electroneum#307]
Compiling Electroneum under fully-updated or new installs of MSYS2 fails due to recent OpenSSL version update. Monero fixed this issue back in October as pull #4471. https://github.com/monero-project/monero/pull/4471

The issue is a recent update to the mingw-w64-x86_64-openssl package (updated to 1.1.1a about 13 days ago).

The build fails with the following error:

```
C:/msys64/home/xxx/electroneum/external/unbound/validator/val_secalgo.c: In function 'verify_canonrrset':
C:/msys64/home/xxx/electroneum/external/unbound/validator/val_secalgo.c:637:35: error: dereferencing pointer to incomplete type 'EVP_MD_CTX' {aka 'struct evp_md_ctx_st'}
  ctx = (EVP_MD_CTX*)malloc(sizeof(*ctx));

```

EDIT: Copied wrong error...

**Comment by andrepatta** [comment]
See if #308 works for you.

Thanks

**Comment by wolstech** [comment]
#308 built successfully! Thanks.

**Comment by andrepatta** [comment]
Awesome! It will be included in our next major update.

Thanks for the contribution.
