### ISSUE TITLE
wallet sync error

### ISSUE THREAD

**Issue by syrius01** [electroneum/electroneum#318]
Hi,

I downloaded the latest release for the electroneum wallet and when I start the electroneum-wallet-cli.exe I get the following error msg:

`Error: wallet failed to connect to daemon: http://localhost:26968. Daemon either
 is not started or wrong port was passed. Please make sure daemon is running or
change the daemon address using the 'set_daemon' command.`

Please take in note that my electroneum daemon (electroneumd.exe) is running and syncing:

`2019-01-21 00:50:59.472 [P2P8]  INFO    global  src/cryptonote_protocol/cryptono
te_protocol_handler.inl:303     [47.98.224.31:26967 OUT] Sync data returned a ne
w top block candidate: 449400 -> 468792 [Your node is 19392 blocks (26 days) beh
ind]
SYNCHRONIZATION started
2019-01-21 00:56:56.672 [P2P5]  INFO    global  src/cryptonote_protocol/cryptono
te_protocol_handler.inl:1152    ←[1;33m[18.208.50.210:26967 OUT]  Synced 449500/
468792←[0m`

I've took the 3 following files from the old wallet to import to the new wallet folder:

1) wallet
2) wallet.address.txt
3) wallet.keys

Any solution or help would be very appreciated.

Thanks

**Comment by mannie65** [comment]
Based on your screenshot - your daemon is not fully synced - its still 19K blocks behind. You need to wait for it to say fully synced

**Comment by andrepatta** [comment]
Hi @syrius01 ,

Could you please inform the arguments you used to start wallet-cli and electroneumd?

Thanks.

**Comment by syrius01** [comment]
@mannie65 : Ok will do, should take +/- 24 hrs to sync from that point. Will let you know tomorrow if I have the same issue.

@andrepatta : Hi, I've used 0 args for launching both daemon and wallet-cli, just the good old double-click then opened :P

Something that bothers me in that error msg is:

`wallet failed to connect to daemon: http://localhost:26968`

which sounds like the wallet-client doesn't see the daemon running and unable to connect to it. Oh and btw, while I was replying I just got this message from the wallet-cli:

`Background refresh thread started
Height 101775, transaction <6f162a496d27dcefac14a0c9875b49e89190e824a2ea9a96fdb7
74098e6162a6>, received **5.00`**

which sounds positive :D

**Comment by andrepatta** [comment]
@syrius01 Then it should work once daemon is fully synced as @mannie65 said. I'll be waiting an update from you. :)

**Comment by syrius01** [comment]
I haven't forget you guys, update: still 10 days before sync 100%. Will post as soon as it's fully sync to let you know if everything is working fine or not.

**Comment by andrepatta** [comment]
The syntax is correct. Enjoy!

ps: you can always type "help" to get tips on the available commands.

**Comment by syrius01** [comment]
Allright, thx for supporting me, very appreciated. I believe this ticket can be closed :)
