### ISSUE TITLE
Use privatenet network "start_mining create block but no money"

### ISSUE THREAD

**Issue by uranus97s** [electroneum/electroneum#319]

**Comment by uranus97s** [comment]
I am a developer, just like monero i have created an electroneum privatenet with 2 nodes. and I practiced mining. but when it created >60 block my address still doesn't have money. Please tell me why!

**Comment by andrepatta** [comment]
That's due to the wallet function that calculates the approximate blockchain (mainnet & testnet) height based on current date and block time. Since private testnets starts from genesis block (height 1), and the calculated block height is calculated by considering the live testnet, your wallet won't fetch these blocks from your private net.

You can solve this problem by changing the `rescan_blockchain` function (in wallet2.cpp) to set `m_refresh_from_block_height` variable to either 0 or any height that you like.

Function after the above change should look like this:
```
void wallet2::rescan_blockchain(bool refresh)
{
  clear();

  cryptonote::block genesis;
  generate_genesis(genesis);
  crypto::hash genesis_hash = get_block_hash(genesis);
  m_blockchain.push_back(genesis_hash);
  m_local_bc_height = 1;
  m_refresh_from_block_height = 0;

  if (refresh)
    this->refresh();
}
```

Then, once the new code is compiled, you can open your private testnet wallet and execute "rescan_bc" command to sync blocks from height 0.

**Comment by uranus97s** [comment]
Oh!!! yes. I went to electroneum-wallet-cli rescan_bc, then used "start_mining", the result was expected.
```2019-01-25 02:53:24.462	[RPC0]	WARN 	miner	src/cryptonote_basic/miner.cpp:306	Mining has started with 1 threads, good luck!
2019-01-25 02:53:24.462	[miner 0]	INFO 	global	src/cryptonote_basic/miner.cpp:417	Miner thread was started [0]
2019-01-25 02:53:24.493	[miner 0]	INFO 	global	src/cryptonote_basic/miner.cpp:471	Found block for difficulty: 1
2019-01-25 02:53:24.544	[miner 0]	INFO 	global	src/cryptonote_basic/miner.cpp:471	Found block for difficulty: 1
2019-01-25 02:53:24.619	[miner 0]	INFO 	global	src/cryptonote_basic/miner.cpp:471	Found block for difficulty: 60
2019-01-25 02:54:01.188	[miner 0]	INFO 	global	src/cryptonote_basic/miner.cpp:471	Found block for difficulty: 3660
2019-01-25 02:54:21.865	[miner 0]	INFO 	global	src/cryptonote_basic/miner.cpp:471	Found block for difficulty: 6766
2019-01-25 02:54:59.468	[miner 0]	INFO 	global	src/cryptonote_basic/miner.cpp:471	Found block for difficulty: 12338
2019-01-25 02:56:08.726	[miner 0]	INFO 	global	src/cryptonote_basic/miner.cpp:471	Found block for difficulty: 14726
```
but my balance is still 0

**Comment by uranus97s** [comment]
Oh!!! I am very grateful to you

**Comment by andrepatta** [comment]
No problem. Let me know if that worked for you.

**Comment by uranus97s** [comment]
I am very grateful that you have supported me. But I don't know how to build source electroneum. can you give me a guide help me please

**Comment by uranus97s** [comment]
Thank you so much !

**Comment by uranus97s** [comment]
@andrepatta  Do you known with "sed -i (stream editor)".
how can i use the above command to add  "m_refresh_from_block_height = 0" into rescan_blockchain function  (in wallet2.cpp)

**Comment by uranus97s** [comment]
@andrepatta  I am very grateful to you ... but I did the same as what you instructed, but it still gives me an unexpected result that is ... address mining with balance 0. although that address I have mining.

**Comment by uranus97s** [comment]
//----------------------------------------------------------------------------------------------------
void wallet2::rescan_blockchain(bool refresh)
{
  clear();

  cryptonote::block genesis;
  generate_genesis(genesis);
  crypto::hash genesis_hash = get_block_hash(genesis);
  m_blockchain.push_back(genesis_hash);
  m_local_bc_height = 1;
  m_refresh_from_block_height = 0;

  if (refresh)
    this->refresh();
}

**Comment by uranus97s** [comment]
I am very grateful to you. I was successful !!!

**Comment by ghost** [comment]
Well done @andrepatta. Thanks Uranus97.
