### ISSUE TITLE
Linux Direct Miner Balance Shows Zero Balance Only

### ISSUE THREAD

**Issue by oleersoy** [electroneum/electroneum#32]
Hi,

I'm giving the Linux direct miner a shot.  I first ran the daemon towards the end it printed this:

```
2017-12-09 17:51:20.172	[P2P2]	INFO 	global	src/cryptonote_core/blockchain.cpp:893	REORGANIZE SUCCESS! on height: 60304, new blockchain size: 60306
2017-12-09 17:51:23.080	[P2P1]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1518	SYNCHRONIZED OK
2017-12-09 18:10:08.222	[P2P1]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:302	[73.47.228.92:55706 INC] Sync data returned a new top block candidate: 60329 -> 60330 [Your node is 1 blocks (0 days) behind] 
SYNCHRONIZATION started
2017-12-09 18:10:10.599	[P2P6]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1518	SYNCHRONIZED OK
2017-12-09 18:10:56.492	[P2P5]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:302	[105.246.9.158:59277 INC] Sync data returned a new top block candidate: 60330 -> 60331 [Your node is 1 blocks (0 days) behind] 
SYNCHRONIZATION started
2017-12-09 18:11:23.927	[P2P7]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1518	SYNCHRONIZED OK
2017-12-09 18:11:55.408	[P2P0]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1518	SYNCHRONIZED OK
```

So that should be all good.  I then created a wallet by running `./electroneum-wallet-cli` and folllowed the promts and finally once that was complete I exectued the `start_mining 7` command to start mining with 7 threads.  

The daemon starts logging output like this so it looks as if it's mining:
```
2017-12-09 19:57:54.303	[RPC0]	WARN 	miner	src/cryptonote_basic/miner.cpp:305	Mining has started with 7 threads, good luck!
2017-12-09 19:57:54.303	[miner 1]	INFO 	global	src/cryptonote_basic/miner.cpp:416	Miner thread was started [1]
2017-12-09 19:57:54.303	[miner 2]	INFO 	global	src/cryptonote_basic/miner.cpp:416	Miner thread was started [2]
2017-12-09 19:57:54.303	[miner 4]	INFO 	global	src/cryptonote_basic/miner.cpp:416	Miner thread was started [4]
2017-12-09 19:57:54.303	[miner 3]	INFO 	global	src/cryptonote_basic/miner.cpp:416	Miner thread was started [3]
2017-12-09 19:57:54.303	[miner 5]	INFO 	global	src/cryptonote_basic/miner.cpp:416	Miner thread was started [5]
2017-12-09 19:57:54.303	[miner 6]	INFO 	global	src/cryptonote_basic/miner.cpp:416	Miner thread was started [6]
```

But when checking the wallet balance with `refresh`, I only see`Balance: 0.00, unlocked balance: 0.00`

``` console 
[wallet etnk76 (out of sync)]: start_mining 7
Mining started in daemon
[wallet etnk76 (out of sync)]: refresh
Starting refresh...
Refresh done, blocks received: 1                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 1                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 0                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 1                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refersh
unknown command: refersh
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 0                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 0                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 1                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 1                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 0                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76 (out of sync)]: refresh
Starting refresh...
Refresh done, blocks received: 0                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 3                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 2                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh
Starting refresh...
Refresh done, blocks received: 1                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: refresh     
Starting refresh...
Refresh done, blocks received: 1                                
Balance: 0.00, unlocked balance: 0.00
[wallet etnk76]: 
```

So obviously something is going on because it says the there are blocks received - but what are these blocks actually translating into?  Also with the linux direct minre we just type `start_mining <threads>` in the wallet, so we don't really know what pool we are going to??  I've seen some youtube explanatory videos where we go to the pool site (ASIA, US, etc) and type in our wallet ID.  So how would we do this with the Linux Direct Miner?  Thoughts?

**Comment by oleersoy** [comment]
Also what are the wallet commands?  Where little documentation to go along with the Linux Direct Miner ....

**Comment by oleersoy** [comment]
I'm attempting to hack my way around this.  I compiled and started the the [cpuminer-multi](https://github.com/OhGodAPet/cpuminer-multi) and pointed it to the pool [https://uspool.electroneum.com/](https://uspool.electroneum.com/).  When I go to that pool and put in my walled address I get the following:

 Pending Balance: 0.00 ETN
Total Paid: 0.00 ETN
Last Share Submitted: 3 minutes ago
Hash Rate: 23.41 H/sec 

So the pool tells me nothing about how much I have mined so far in general.  Shouldn't the `Total Paid` quantity reflect earlier amounts written to the block chain by the Linux Direct Miner?

**Comment by WalterMagnum** [comment]
Blocks received means that the wallet exe received a block.  That does not mean that the block it received contains any transactions involving your wallet address.  A block is just part of the blockchain (the decentralized distributed ledger that stores all transactions).

**Comment by oleersoy** [comment]
So I've been mining all day now on two laptops and so far trying my balane is zero when looking at it through the wallet cli and the pool interface at https://uspool.electroneum.com/.  Is that normal?

**Comment by tahv0** [comment]
Having same issue:
```
[wallet etnkG2]: refresh
Starting refresh...
Refresh done, blocks received: 0                                
Balance: 0.00, unlocked balance: 0.00
```
Have I lost my money?

**Comment by electroneumRepo** [comment]
Direct Mining is nothing to do with pool mining.
The reason you are seeing no coins is because Direct Mining is VERY difficult. This is why people use pools to mine.

When you were using the pool miner, you wont see coins straight away. You get rewarded periodically according to the amount of work that you machine did in breaking the block.

I hope this helps and makes sense to you.

**Comment by oleersoy** [comment]
Happy new year!  I'll just give you some feedback.  If you are launching the coin with something that sounds promising like Direct Mining and you later have to explain it as "VERY DIFFICULT", that's bad.  Just don't launch that then.  I'm a pretty savvy developer, so if it's hard for me, then I suspect that 99.99% of the people trying that out are going to be very disappointed, which obviously you don't want.

When I'm running a magi coins pool miner on various pools I see transactions earned every 1/2 hour to 2 hours.  This gives miners confidence in the coin and they feel like they are not wasting their time.  You want that.

Good luck.  I hope you can make it work.
