### ISSUE TITLE
Testnet coin

### ISSUE THREAD

**Issue by loyogoy-g** [electroneum/electroneum#322]
How to have testnet coin ? I am working locally

**Comment by ghost** [comment]
**Step 1** 
Make a testnet wallet:
./electroneum-wallet-cli --testnet
and follow instructions

**Step 2** 
Then run the daemon like
./electroneumd --testnet
and then once synchronised with the network type into the daemon
start_mining <wallet address> <#threads>

**Step 3** 
Wait until you find a block and the funds to unlock (18 block confs)
