### ISSUE TITLE
Where should I bind the port 26969 or 26968

### ISSUE THREAD

**Issue by loyogoy-g** [electroneum/electroneum#323]
I am having a hard time to start the RPC wallet

**Comment by ghost** [comment]
For JSON RPC requests --rpc-bind-port 40100
--daemon-address 127.0.0.1:26968

Something like:

--daemon-address 127.0.0.1:26968 --rpc-bind-port 41000 --disable-rpc-login --trusted-daemon --wallet-file /Users/loyo/wallet

should do the trick
