### ISSUE TITLE
Add command to build instruction

### ISSUE THREAD

**Issue by Unyxos** [electroneum/electroneum#324]
For people having an issue when building from the sources, if the error is : 

`implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Wimplicit-function-declaration]`

Install the following package:
`apt-get install libssl1.0-dev`

Credits to: https://github.com/openlink/virtuoso-opensource/issues/663

(Maybe add this in the readme ? ;))

**Comment by ghost** [comment]
We're updating SSL in the next update. Thanks for the heads up.
