### ISSUE TITLE
RPC sweep_all doesn't work

### ISSUE THREAD

**Issue by xinyijun** [electroneum/electroneum#325]
I created a new wallet, and transfer coins from another wallet to it 4 times(with coin 100/200/300/500). Then I issued a RPC sweep_all call with address set to self and below_amount set to 400, the result was expected, the coin 100/200/300 was merged into 599(with fee 1). Now I had 2 coins: one is 500, the other is 599. After that, I issued another RPC sweep_all call with address set to self and below_amount set to 90, the call succeed and 1 transaction hash was returned, I used RPC get_transfer_by_txid to view the transaction and found the amount was 8 and fee was 1. It's very strange behavior, the 2nd RPC sweep_all call should have return empty transaction hash list, because I only have 2 big coins(500 and 599) and sweep_all with below_amount set to 90 should have nothing to do. Attachment is related RPC call and response.
[rpc_call_and_response.txt](https://github.com/electroneum/electroneum/files/3067921/rpc_call_and_response.txt)

**Comment by xinyijun** [comment]
The testing use private chain(option --testnet was used), the version of electroneum-wallet-rpc is: Electroneum 'August 2018' (v2.1.1.1-a15d47f)

**Comment by ghost** [comment]
When you send ETN from one wallet to another, it can split your inputs into fractional outputs. 
For example:
IN: 555
OUT: 500, 50, 5
The sweep below parameter allows you to sweep **outputs** in your wallet below a certain value.

**Comment by xinyijun** [comment]
Understand that, but I call sweep_all twice, the 1st call use 400 as value of below_amount, the 2nd call use 90 as value of below_amount, in my understanding, the 2nd call should return EMPTY result, but it did NOT.

**Comment by ghost** [comment]
But you're sweeping back to your own wallet.... 
Look at the heights of your sweeps (190,180)
192 -180 = 12
12 > cryptonote default unlock time 
So the output of 8 will be an unlocked output from your first sweep.

Try the test again with your sweeps taking place less than ten blocks apart.

**Comment by xinyijun** [comment]
Thanks, understand it, sweep also produce fractional outputs(it seems to be conflict with the function of sweep?). Is there any lower bound of amount of these fractional outputs? We receive many small changes frequently, when we want to send someone a big one, we got error "Transaction would be too large. try /transfer_split.", but transfer_split will produce more than 1 transaction, which is not what we expect, is there any suggestion for this case?

**Comment by ghost** [comment]
0.01 is the lower bound.

When the number of inputs increases, you still get splitting, however the number of outputs will not scale linearly with the number of inputs. For example you could sweep 111 inputs of 10 etn and still only get three outputs (1000,100,10)

 If you're interested in the output possibilities at present, see
static const uint64_t valid_decomposed_outputs[] inside the file src/cryptonote_basic/cryptonote_format_utils.cpp.

On your topic of transfer split, it splits so there is more chance of the tx being included in a block. If the tx size was arbitrary, the block size limit might mean that the tx is never assigned a block.

**Comment by xinyijun** [comment]
Thanks. In my understanding, all possible output amount are in valid_decomposed_outputs except the one smaller than 1, when creating transaction, the wallet will choose the biggest one(but <= sum(input amount) - fee) in valid_decomposed_outputs as 1st output, then the biggest one(but <= sum(input amount) - fee - 1st output amount) as 2nd output , then..., right?

**Comment by ghost** [comment]
A few things:
Any output seen in that matrix should be divided by 100 as per the #decimals for ETN.
Not all outputs are valid and decomposed as per the matrix. For example 0.11ETN isn't seen.
Your logic for output choice is correct.

**Comment by xinyijun** [comment]
Thanks.
