### ISSUE TITLE
destinations lost in out transaction

### ISSUE THREAD

**Issue by xinyijun** [electroneum/electroneum#326]
Recently we observed several(not all) transactions(type out) with field "destinations" lost, attachment is the 2 transactions with such issue. Please help to investigate it, thanks.
[tx_lost_destinations.txt](https://github.com/electroneum/electroneum/files/3097451/tx_lost_destinations.txt)

**Comment by xinyijun** [comment]
we found 26 such transactions(type out) finally.

**Comment by ghost** [comment]
https://github.com/monero-project/monero/issues/2861

**Comment by xinyijun** [comment]
Thank you, but our case is not the same as monero-project#2861, we only run electroneum-wallet-rpc(never run electroneum-wallet-cli), we didn't run rescan either.  Type out transactions with destinations and type out transactions without destinations were interleaved. The attachment is 25 type out transactions without destinations(we found 26 such transactions and manually fixed data manually for one of them).
[destination_lost_tx.txt](https://github.com/electroneum/electroneum/files/3110377/destination_lost_tx.txt)
