### ISSUE TITLE
can't build electroneumd on win10 home

### ISSUE THREAD

**Issue by lkelemen** [electroneum/electroneum#328]
$ make release-static-win64
mkdir -p build/release
cd build/release && cmake -G "MSYS Makefiles" -D STATIC=ON -D ARCH="x86-64" -D BUILD_64=ON -D CMAKE_BUILD_TYPE=Release -D BUILD_TAG="win-x64" -D CMAKE_TOOLCHAIN_FILE=../../cmake/64-bit-toolchain.cmake -D MSYS2_FOLDER=c:/msys64 ../.. && make
-- Building build tag win-x64
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- MSYS location: C:/msys64
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- looking for liblzma
-- liblzma found
-- Could not find libunwind (missing: LIBUNWIND_INCLUDE_DIR)
-- Stack trace on exception disabled
-- Could NOT find MiniUPnPc (missing: MINIUPNP_INCLUDE_DIR MINIUPNP_LIBRARY)
-- Using miniupnpc from local source tree for static build
-- Looking for libunbound
-- Using 64-bit LMDB from source tree
-- Building on  for x86-64
-- AES support enabled
-- Found Boost 1.70.0 at C:/msys64/mingw64/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS system;filesystem;thread;date_time;chrono;regex;serialization;program_options
-- Found boost_headers 1.70.0 at C:/msys64/mingw64/lib/cmake/boost_headers-1.70.0
-- Found boost_system 1.70.0 at C:/msys64/mingw64/lib/cmake/boost_system-1.70.0
-- No suitable boost_system variant has been identified!
--   libboost_system-mt.dll.a (shared, Boost_USE_STATIC_LIBS=ON)
--   libboost_system-mt.a (shared runtime, Boost_USE_STATIC_RUNTIME=ON)
CMake Error at C:/msys64/mingw64/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Found package configuration file:

    C:/msys64/mingw64/lib/cmake/boost_system-1.70.0/boost_system-config.cmake

  but it set boost_system_FOUND to FALSE so package "boost_system" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

Call Stack (most recent call first):
  C:/msys64/mingw64/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  C:/msys64/mingw64/share/cmake-3.14/Modules/FindBoost.cmake:266 (find_package)
  CMakeLists.txt:657 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/leo/electroneum-master/build/release/CMakeFiles/CMakeOutput.log".
See also "C:/msys64/home/leo/electroneum-master/build/release/CMakeFiles/CMakeError.log".
make: *** [Makefile:114: release-static-win64] Error 1

**Comment by lkelemen** [comment]
cmake version 3.14.2

**Comment by lkelemen** [comment]
why line 9 is different in the file version.cmake in the zipped download versus cloned via git?
zipped:
if ("" STREQUAL "")
git cloned:
if ("$Format:$" STREQUAL "")

**Comment by lkelemen** [comment]
version number and release name should be changed in

https://github.com/electroneum/electroneum/blob/master/src/version.h.in

**Comment by ghost** [comment]
Give me a minute to sort out the versioning.

**Comment by lkelemen** [comment]
the binaries still contain the old version number
