### ISSUE TITLE
electroneum-linux-v2.1.1.2.tar.gz is broke

### ISSUE THREAD

**Issue by tgwaste** [electroneum/electroneum#329]
./electroneumd --version
Electroneum 'August 2018' (v2.1.1.1-release)

o Version is wrong
o Executables inside are not +x
o The file is not Gziped.  It's only a tar.

**Comment by pviljaka** [comment]
I opened a forum topic about the same subject just when they updated the binaries here at github. Check this thread: https://community.electroneum.com/t/binaries-for-the-updated-electroneumd-cli-wallet/16100/9
