### ISSUE TITLE
Repo location cannot be changed

### ISSUE THREAD

**Issue by kudiaborm** [electroneum/electroneum#33]
Hello, Please allow me to change the location of the repo. When launching the daemon it automatically starts downloading to the C drive.]

**Comment by electroneumRepo** [comment]
Hi @kudiaborm,

You can use the `--data-dir` flag when starting the daemon.

For example, If you want to change the directory to be on your "D Drive" then you would run:

`electroneumd.exe --data-dir=D:\electroneum`

This will then download the blockchain to that folder. If the folder does not exist then it will be created.

I hope this helps

**Comment by kudiaborm** [comment]
Thanks! I wound up making a symlink. It's good to know about this feature
though
