### ISSUE TITLE
Super slow syncing

### ISSUE THREAD

**Issue by Crypto2** [electroneum/electroneum#336]
Syncing seems to be super slow in ETN, with anywhere up to 2 minutes per 100 blocks. Since the blockchain.raw file is ~1.5 months old it leaves the remaining ~25,000 to catch up on and that's going to take 4+ hours smh

**Comment by Crypto2** [comment]
And it deadlocks after a while and has to be hard killed ;(

**Comment by ghost** [comment]
The raw file is updated once a month I think. However if it's taking you that long, is it perhaps because you are using a HDD and not ssd?

**Comment by Crypto2** [comment]
Using NVMe

**Comment by shopglobal** [comment]
Just add checkpoints...

**Comment by hallowa-helwijk** [comment]
![Naamloos](https://user-images.githubusercontent.com/56957438/72923098-a0a2f900-3d4e-11ea-93bb-7b4c9aedcc89.jpg)
What you can try is to kill your computer's CPU, giving it more computing power to synchronize the blockchain. In principle it should be possible within 8 hours.
And indeed use an SSD drive.

**Comment by ghost** [comment]
New release coming out soon (3.1.0.0) that is designed to improve sync speeds. I just synced the whole of the blockchain with:

i7 proc
16gb ram
SSD
270Mbps internet download speed (speedtest)

in 1hr24mins.
