### ISSUE TITLE
Reg - ubuntu 16.04 Issue

### ISSUE THREAD

**Issue by osizadmin** [electroneum/electroneum#339]
we are not able use this updated package in ubuntu 16.04.
Is there any possibilities to install this package.

**Comment by andrepatta** [comment]
Hi @osiz-admin,

Could you please explain why you're not able to use the provided Ubuntu 16.04 binaries?

Remember you can always build the binaries yourself directly from source. More instructions on how to build from source here: [Build & Run](https://github.com/electroneum/electroneum/blob/master/docs/build-and-run.md)

Thanks

**Comment by osizadmin** [comment]
we have used "electroneum-release-static-linux-x86_64-3.1.0.0.tar.bz2" this linux package for installation.
we got this error while run electroneumd

"**./electroneumd: error while loading shared libraries: libnorm.so.1: cannot open shared object file: No such file or directory** "

**Comment by andrepatta** [comment]
Could you please double check if you have installed all required dependencies?

You can check the dependency list [here](https://github.com/electroneum/electroneum/blob/master/docs/build-and-run.md).

Additionally, get the latest libnorm by doing `sudo apt update && sudo apt install libnorm-dev`.

**Comment by osizadmin** [comment]
we have tried this command. but we got this issue from server

E: Unable to locate package libnorm-dev

Note : we have installed all dependencies 

sudo apt update && sudo apt install build-essential cmake pkg-config libboost-all-dev libssl-dev libzmq3-dev libunbound-dev libsodium-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libpgm-dev

**Comment by BKdilse** [comment]
I don't think `libnorm-dev` exists for `xenial (16.04)`, I'm now compiling from source.

**Comment by andrepatta** [comment]
Please let me know how the build goes. We should be releasing pre compiled binaries for 16.04 soon though.

Thanks

**Comment by BKdilse** [comment]
@andrepatta compiled fine, although I terminated `make `once `electroneumd `was compiled, as I only need the Daemon for my wallet sync.

**Comment by andrepatta** [comment]
Awesome. Have a nice day!

**Comment by osizadmin** [comment]
@andrepatta Are you release ubuntu 16.04 supported linux package.

**Comment by ghost** [comment]
> @andrepatta Are you release ubuntu 16.04 supported linux package.

We'll be sorting precompiled binaries for Ubuntu 16 asap.

**Comment by ghost** [comment]
@BKdilse , @osiz-admin I've uploaded the Ubuntu 16 binaries. Can you try them out to confirm they're working ok please? [http://www.github.com/electroneum/electroneum](url)

**Comment by BKdilse** [comment]
@ChrisCharrison I can confirm that your released the Daemon and Wallet CLI execute fine on Ubuntu 16.04.

**Comment by ghost** [comment]
Thanks for testing
