### ISSUE TITLE
Daemon v3.1.0.0-2fb3cb145 - Stuck at height 736815

### ISSUE THREAD

**Issue by BKdilse** [electroneum/electroneum#340]
Update to latest Daemon, and it is stuck at 736815/737644 (at this moment in time).

`Height: 736815/737644 (99.9%) on mainnet, not mining, net hash 290 H/s, v8, 4(out)+0(in) connections, uptime 0d 0h 12m 34s`

log level 1 shows connection timeouts.

Any ideas?

**Comment by andrepatta** [comment]
Hi @BKdilse ,

Can you start your deamon with `—log-level 4` argument and link the daemon log file?

Thanks

**Comment by BKdilse** [comment]
@andrepatta how long do you want me to run it for with that log level?

**Comment by andrepatta** [comment]
Start up the daemon, wait everything to load and type the command “status”.  That should be enough.

Thanks

**Comment by BKdilse** [comment]
[electroneum.zip](https://github.com/electroneum/electroneum/files/4136045/electroneum.zip)

here you go @andrepatta

**Comment by andrepatta** [comment]
Many thanks @BKdilse . I will take a look at the log file as soon as I get back to my pc in a few hours.

Appreciate your patience.

**Comment by andrepatta** [comment]
I couldn't spot any meaningful errors/exceptions in the log file provided and my v3.1.0.0 daemon seems to sync past the 736815 block without problems.

Are you using the pre compiled binaries provided in the GitHub's release page or you build them yourself? I suppose you're on Ubuntu?

**Comment by BKdilse** [comment]
Initially I compiled it myself, as the 18.04 version was no good to me.  I'm now using the pre-compiled version which I tested yesterday.

Both version are doing the same thing, stuck at that height.  I might try popping a few blocks, as this has worked on other coins.

EDIT:  That didn't help this time.

**Comment by BKdilse** [comment]
Are there any nodes I can try adding as an exclusive node?

**Comment by shopglobal** [comment]
pop about 10k blocks and let the main chain sync in the remaining blocks.
Check out the ETN fork https://t.me/electronero

**Comment by BKdilse** [comment]
yeah, thanks I was going to try a larger number, so I'll give it a go.

**Comment by BKdilse** [comment]
that didn't work either, syncing from scratch works, so I'm trying that now.

**Comment by BKdilse** [comment]
just an update, the sync took a few hours, and now it's past that block, and fully synced.

**Comment by andrepatta** [comment]
Good to know! Thanks @BKdilse
