### ISSUE TITLE
cli crash on transfer

### ISSUE THREAD

**Issue by Gert2525** [electroneum/electroneum#341]
Using the CLI on windows 10. When want to transfer coins, it crashes after inputting password.

**Comment by andrepatta** [comment]
Please provide wallet logs.

**Comment by Gert2525** [comment]
I blanked some with *****

**Comment by shopglobal** [comment]
Hit enter

**Comment by Gert2525** [comment]
Its after putting the password and hitting enter, when password wrong it give the message that the password if wrong, when correct it crashes.

**Comment by CryptoCruzer** [comment]
Same issue occurs for me on 3.1.0.0 and had zero issues on 3.0.0.0.  (Windows 10 here.)

Every time I try either sweep_all <address> <paymentID>  or transfer commands the CLI crashes immediately upon entry of correct password. This problem is consistent.

Please help.

**Comment by andrepatta** [comment]
Hi guys,

Could you both provide wallet logs but this time around with the argument `--log-level 4`? That would help a lot since the previous log sent by @Gert2525 didn't had any apparent errors.

In addition, are you guys using the pre-compiled binaries or have built your own?

Thanks

**Comment by Gert2525** [comment]
Hi @andrepatta the log I had send previous was with --log-level 4. Attached a new log also with --log-level 4. I use the pre-compiled ones.

**Comment by ghost** [comment]
@Gert2525 @CryptoCruzer  We will cross compile the binaries for windows to see if that helps. I'll let you know when they're up. Are you guys using both a 3.1 **daemon** as well as a 3.1 wallet? If not please use both together and see if that helps.

**Comment by Gert2525** [comment]
Yes both daemon and wallet 3.1.

**Comment by ghost** [comment]
@Gert2525 what kind of crash do you get? Is anything outputted to the terminal? Please paste it here

**Comment by Gert2525** [comment]
@ChrisCharrison not any output, after hitting enter takes about a second and the close the window. In terminal just jump to the prompt without any output.

**Comment by hallowa-helwijk** [comment]
@ChrisCharrison Create an offline wallet.
Then offline wallet in client and enter 3 keys.
Create a password and the screen will disappear

**Comment by shopglobal** [comment]
What are hardware specs? Maybe simple as not enough RAM or CPU available?

**Comment by Gert2525** [comment]
Core i7 8gen, 16 GB Ram, SSD. Plenty resources, just also tried with all closed.

**Comment by shopglobal** [comment]
Yes, that should be enough resources. Just wanted to eliminate it as a
possible cause. Hmm...

**Comment by ghost** [comment]
@Gert2525 No probs. We will explore what's going on today and have it fixed soon. Thanks for bringing it to our attention.

**Comment by andrepatta** [comment]
@Gert2525  @CryptoCruzer You can use the wallet-cli from v3.0.0.0 with the latest daemon by starting it with `--allow-mismatched-daemon-version` as a workaround while we investigate the issue with wallet-cli v3.1.0.0 (windows).

**Comment by andrepatta** [comment]
Hey folks,

Could you please try the following
[wallet-cli](https://github.com/electroneum/electroneum/files/4157766/electroneum-wallet-cli.win-x86_64.zip).

I'll submit a PR and rebuild the pre-compiled binaries as soon as you confirm the fix.

Thanks

**Comment by Gert2525** [comment]
Hi guys, going trough. Problem solved, thanks!

**Comment by hallowa-helwijk** [comment]
Okay. you can send a few etn to etnkHPDRoyDc9Sbam8rBZFJ4vMrjS8ap1H3qFLBakjqbDYBxxSSEw57XsJ7Wa9XEeaioGYzuwYJPDTyZGuu5n9W47QvEfbPDaW  to offline wallet. Then I will test it completely today.
Can I also see if something is coming in?
I will also make it online.
Thank you

**Comment by hallowa-helwijk** [comment]
It still does not work.
After entering 2x the password, the screen disappears after 3 seconds

Don't know how other people have this too?

The next step should be: new wallet generated: etn ......
The screen has already disappeared

**Comment by andrepatta** [comment]
#343 fix the wallet-cli crash on Windows.

Closing...
