### ISSUE TITLE
Cant Write or paste the Password

### ISSUE THREAD

**Issue by Cryptoerror** [electroneum/electroneum#347]
after i input the name of the wallet and press enter i cant input the password on ver 3.0 and 3.0.1 &3.1 3.2

**Comment by BegaMutex** [comment]
It doesn't show what you type Cryptoerror... but its there. Same when entering seed/private key when generating wallet from seed/keys.

**Comment by Cryptoerror** [comment]
Thanks i lost my mind trying to fix it
