### ISSUE TITLE
MacOS High Sierra - Newest Mac binary wont start

### ISSUE THREAD

**Issue by pviljaka** [electroneum/electroneum#356]
Hey. Been using the older cli version 3.0 something...
Tried to update to the newest 3.3.0.0 and it wont even start.
Is it compatible for MacOS High Sierra which i'm forced to run at this moment?
It seems to not find some library. Any tips how to fix it?

`dyld: Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib
  Referenced from: /Users/pete/Applications/electroneum_wallet/./electroneumd
  Reason: image not found
  Abort trap: 6
`

**Comment by ProrokEskobar1** [comment]
i will help ya in abouts 2
Thanks


P56™

**Comment by pviljaka** [comment]
> i will help ya in abouts 2 Thanks P56™
> […](#)

Ok, cool. Thanks. Take your time

**Comment by Jones1066** [comment]
I'm running Catalina v10.15.5 and getting the same. Termination Reason: DYLD, [0x1] Library missing

The full console error text is below. Thanks for any assistance!

Process:               electroneumd [54783]
Path:                  /Users/USER/Downloads/*/electroneumd
Identifier:            electroneumd
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [54543]
Responsible:           Terminal [54540]
User ID:               501

Date/Time:             2020-07-26 13:54:45.045 -0400
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        7DBBE150-26B0-84A2-00A6-699766156E8C

Sleep/Wake UUID:       45DE15D3-4CDB-40B6-BE2B-F6701B7F3936

Time Awake Since Boot: 310000 seconds
Time Since Wake:       3000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib
  Referenced from: /Users/USER/Downloads/*/electroneumd
  Reason: image not found

Binary Images:
       0x10fb7b000 -        0x111b84ff3 +electroneumd (0) <7BA5DC6B-6C59-3A34-B84B-296610CFA4D8> /Users/USER/Downloads/*/electroneumd
       0x1212c5000 -        0x121356eff  dyld (750.5) <E4698FBD-806A-3396-B279-E685BA37430B> /usr/lib/dyld

**Comment by andrepatta** [comment]
Could you please see if the wallet-cli below works? Thanks.
[electroneum-wallet-cli.zip](https://github.com/electroneum/electroneum/files/4980344/electroneum-wallet-cli.zip)

**Comment by pviljaka** [comment]
> Could you please see if the wallet-cli below works? Thanks.
> [electroneum-wallet-cli.zip](https://github.com/electroneum/electroneum/files/4980344/electroneum-wallet-cli.zip)

./electroneum-wallet-cli 
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/pete/Downloads/./electroneum-wallet-cli (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/pete/Downloads/./electroneum-wallet-cli (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

**Comment by Jones1066** [comment]
Thanks for the quick reply. I'll give this a try tonight and let you know.

**Comment by andrepatta** [comment]
Thanks. If the binaries above doesn't work, please do the following as a workaround while we investigate further.

1) Install Homebrew (if not already installed) from https://brew.sh/ 
2) Install ZeroMQ libraries using brew by opening the Terminal and typing "brew install zeromq".

I hope the steps above solve the issue for you. In case it still fails, please build from source following the guide from [Build and Run](https://github.com/electroneum/electroneum/blob/master/docs/build-and-run.md) (Advanced)

**Comment by Jones1066** [comment]
Hi Andre - I think there was some confusion. I was unable to
run electroneumd.

**Comment by pviljaka** [comment]
> Hi Andre - I think there was some confusion. I was unable to run electroneumd.
> […](#)

Same here. Actually both, electroneumd and the -wallet-cli

`./electroneumd
dyld: Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib
  Referenced from: /Users/pete/Applications/electroneum_wallet/./electroneumd
  Reason: image not found
Abort trap: 6

./electroneum-wallet-cli
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.8.dylib
  Referenced from: /Users/pete/Applications/electroneum_wallet/./electroneum-wallet-cli
  Reason: image not found
Abort trap: 6`

**Comment by andrepatta** [comment]
Hi folks,

Could you please try with these binaries https://www.dropbox.com/s/i1gj5aod9tg8mtu/etn-3.3.0.0-macos.zip?dl=0

This issue has been a tough one because we can't reproduce it on our machines, but I just want to let you know we're working on it.

Thanks

**Comment by pviljaka** [comment]
> Hi folks,
> 
> Could you please try with these binaries https://www.dropbox.com/s/i1gj5aod9tg8mtu/etn-3.3.0.0-macos.zip?dl=0
> 
> This issue has been a tough one because we can't reproduce it on our machines, but I just want to let you know we're working on it.
> 
> Thanks

Hey. Thanks for working towards it,  but no joy yet (High Sierra 10.13.6):

```
./electroneumd
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/pete/Downloads/etn-3.3.0.0-macos/./electroneumd (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/pete/Downloads/etn-3.3.0.0-macos/./electroneumd (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

./electroneum-wallet-cli
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/pete/Downloads/etn-3.3.0.0-macos/./electroneum-wallet-cli (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/pete/Downloads/etn-3.3.0.0-macos/./electroneum-wallet-cli (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

Will be happy to test the next candidate.

**Comment by andrepatta** [comment]
@pviljaka that definitely looks like binaries built in OSX Catalina aren't backwards compatible with OSX High Sierra. I'm  afraid we'd need to get a macbook with High Sierra to fix this one for you.

It seems @JeffJakkis is on Catalina (10.15.5), could you please see if the latest binaries works for you?

**Comment by adurabid** [comment]
Hi guys, @andrepatta
I was following this topic as i have the same issue as the others in here (i'm also on OSX High Sierra 10.13.6).
Was wondering if there is any update on this?
Thank you!

**Comment by ghost** [comment]
@adurabid, @pviljaka , @JeffJakkis please try the newer Electroneum 3.1.1.0 binaries located at www.github.com/electroneum/electroneum/releases and let me know if they fix your issue

**Comment by pviljaka** [comment]
@ChrisCharrison 
`osx86:electroneum-osx-3.3.1.0 pete$ ./electroneumd
dyld: Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib
  Referenced from: /Users/pete/Downloads/electroneum-osx-3.3.1.0/./electroneumd
  Reason: image not found
Abort trap: 6
`
and
`osx86:electroneum-osx-3.3.1.0 pete$ ./electroneum-wallet-cli 
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.8.dylib
  Referenced from: /Users/pete/Downloads/electroneum-osx-3.3.1.0/./electroneum-wallet-cli
  Reason: image not found
Abort trap: 6
`

**Comment by adurabid** [comment]
@ChrisCharrison  getting the same error as @pviljaka

**Comment by ghost** [comment]
Do you guys want to try the new ones on the release page?

**Comment by adurabid** [comment]
Hi @ChrisCharrison ,
I just tried 3.3.1.0, it works and it correctly synced up my wallet!
Thank you for the fix!

**Comment by pviljaka** [comment]
Just tested the current 3.3.1.0 on a High Sierra and now it starts and syncs OK.
Thanks !
