### ISSUE TITLE
Error Mining

### ISSUE THREAD

**Issue by Chief-Zach** [electroneum/electroneum#364]
I am getting this error message when I try to mine with Menero and need some help. I am fully synced to the wallet and the Daemon. 

>>> start_mining 
<MY_ACCOUNT>
[2021-01-12 4:07 PM] 2021-01-12 21:07:42.564 I Monero 'Oxygen Orion' (v0.17.1.9-release)
Error: Mining did not start-- rpc_request: BUSY

**Comment by ghost** [comment]
We're Electroneum , not Monero, and we don't allow mining anymore. Thanks and best wishes.
