### ISSUE TITLE
Unsigned txsets cannot be loaded via RPC

### ISSUE THREAD

**Issue by lxop** [electroneum/electroneum#365]
Commit 32d80ea5dd38bfb80f00f0d2fd0d3792dea7840e changed the version numbers in the txset magic headers back to their unencrypted values. This means that txsets exported by the RPC wallet are encrypted but have a magic number indicating that they are unencrypted, leading to the wallet failing to load them back in again. Instead the user just receives the response
```json
{"error": {"code": -39, "message": "cannot load unsigned_txset"}, "id": "1", "jsonrpc": "2.0"}
```

**Comment by ghost** [comment]
Do you have a line number? This was quite a big upstream merge. PR it if you like. Thanks

**Comment by lxop** [comment]
Line 104 in wallet2.cpp. PR coming shortly

**Comment by ghost** [comment]
Thank you @lxop
