### ISSUE TITLE
Block older 2.x peer versions

### ISSUE THREAD

**Issue by bonifacio123** [electroneum/electroneum#369]
Older 2.x peers seems to consume lots of bandwidth in gigs per day range (example 14GB). It would be helpful to have the ability to block peers less than 3.x without having to individually ban each one by one. I don't see this issue with 3.x connections. I'm running 3.10.3.0

Thank you.

**Comment by ghost** [comment]
I'm surprised that people are still running 2.x.x.x beings as they will be on a different chain altogether at this point. We can look into this though thanks
