### ISSUE TITLE
still no GUI wallet ?

### ISSUE THREAD

**Issue by auroracoin** [electroneum/electroneum#371]
still no GUI wallet ?

**Comment by IRGC** [comment]
time to build own wallet.

**Comment by auroracoin** [comment]
> time to build own wallet.

Wish I could. :)

**Comment by IRGC** [comment]
lets build in collaboration.

**Comment by IRGC** [comment]
are you a programmer?

**Comment by auroracoin** [comment]
> lets build in collaboration.
I have no knowledge of how to build one.

**Comment by auroracoin** [comment]
No

**Comment by ghost** [comment]
https://github.com/andrepatta/etn-desktop-wallet

Would be nice if it was made official and forked under Electroneum if @andrepatta didn't mind. Priorities I guess.

**Comment by IRGC** [comment]
etn is a mobile cryptocurrency but wallet available for only desktop
what kind of bullshit logic it is.

**Comment by ghost** [comment]
It has a GUI & CLI wallet that work on MACOS, Linux and Windows....integration for hardware wallet being reviewed by Ledger and a centralised mobile wallet on IOS/Android with over 3million downloads  .. So not really sure wtf you are talking about @IRGC.   

Perhaps leave github for actual issues/feature requests and head over to electroneum.com to read about the project or the forum to discuss with community.

**Comment by IRGC** [comment]
My concern is etn being mobile crypto currency but there is no other alternative wallet for mobile phones other than centralized shit.

**Comment by IRGC** [comment]
@ParkFrenzy  you asshole just joined GitHub 20 minutes ago just to comment on this 🤣😂

**Comment by ghost** [comment]
So you would like the Electroneum Team to create a second mobile app just to cater to a tiny % of users who want decentralised but don't want to use CLI/GUI?  🤦‍♂️ I'm sure they will get right on that "revolutionary coder". 

Now how about leaving github issues for what they are intended for and head on over to social media or the community for these little gems of insight you have.

**Comment by andrepatta** [comment]
This is a bug tracker for electroneum blockchain, not a help desk. Closing.

**Comment by IRGC** [comment]
Are you stupid and dumb to use mobile crypto currency on desktop cli/gui? Do you even have sense on what you are talking about?

And No one replies on forum go and check yourself each and every thread. 
https://community.electroneum.com
