### ISSUE TITLE
'wrong response code: 301' for reaching vl.electroneum.com

### ISSUE THREAD

**Issue by kycfeel** [electroneum/electroneum#373]
Hi there.

I just noticed that my electroneum node is not reaching vl.electroneum.com due to the error below:

```
2021-09-25 09:38:15.077 I Failed to invoke http request to /, wrong response code: 301
2021-09-25 09:38:15.077 I Unable to get validator_list json from vl.electroneum.com:80
2021-09-25 09:38:15.077 I Loading Validator List...
2021-09-25 09:38:15.077 I Validator list has too few public keys.
2021-09-25 09:38:15.077 I Validator List Grace Period
```

I can reach to the site properly with my web browser tho.

Looks like the website got an HTTPS redirection logic, but somehow the electroneumd is not following it.

Is there any way to solve it?

Thanks.

**Comment by andrepatta** [comment]
Hi @kycfeel,

Which OS are you running the electroneum node on? I tested on my Ubuntu and Windows machine and node seems to be fetching the validator list with no issues.

Also, are you using the binaries from the release page or did you compile them yourself?

Thanks.

**Comment by kycfeel** [comment]
@andrepatta Hi there.

I built the binary myself based on the `master` branch, for IBM System Z Mainframe (`s390x` arch).

The host machine is running Ubuntu 18.04 LTS, but the binary itself is built and running with Docker Ubuntu 16.04 LTS.

https://github.com/kycfeel/electroneum

This is my fork for electroneum. Added changes for the `s390x` build. 

You could find all the changes I made at there :)

Thank you.

**Comment by andrepatta** [comment]
That's great!

I'm wondering if there's something in your system preventing the electroneum node to connect to vl.electroneum.com. Maybe it's lacking firewall/system permission. Could you please double check that?

Thanks.

**Comment by kycfeel** [comment]
@andrepatta Hi again.

I just double-checked that my system does not have any restrictions to reach vl.electroneum.com. So this gotta be not a firewall/network issue.

For some reason, I'm no longer seeing the 301 error thing I mentioned after the full node restart.

But still, I'm having the general sync issue.

I attached the full logs from my electroneum node. Can you actually have a look if you have some time?

One suspicious thing is, I actually opened different ports for 26967 ~ 26968 ports (with NAT, opened 30000 ~ 30001 instead). Do you think this could be related too?

Many thanks.

[logs-from-electroneumd-in-electroneumd-76899bd7dc-96wwp.log](https://github.com/electroneum/electroneum/files/7241317/logs-from-electroneumd-in-electroneumd-76899bd7dc-96wwp.log)

**Comment by chrischarlesharrison** [comment]
We don't have time to
