### ISSUE TITLE
Configuring and compiling issues with Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by aicastell** [electroneum/electroneum#378]
Hello there. I am just trying to compile electroneum from sources using Ubuntu 20.04.5 LTS. I am using release/4.0.0.1 git branch. All dependencies have been solved as explained in this link: (https://github.com/electroneum/electroneum/blob/master/docs/build-and-run.md)

I have two issues:

1) Getting a configuration error when configuring the trezor build with cmake:

```
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread (found version "3.6.1") 
-- Protobuf lib: /usr/lib/x86_64-linux-gnu/libprotobuf.so, inc: /usr/include, protoc: /usr/bin/protoc
CMake Warning at cmake/CheckTrezor.cmake:126 (message):
  Trezor protobuf messages could not be regenerated (err=1, python ).OUT: ,
  ERR: Traceback (most recent call last):

    File "/home/aaa/Descargas/electroneum/src/device_trezor/trezor/tools/pb2cpp.py", line 219, in <module>
      main()
    File "/home/aaa/Descargas/electroneum/src/device_trezor/trezor/tools/pb2cpp.py", line 213, in main
      protoc(
    File "/home/aaa/Descargas/electroneum/src/device_trezor/trezor/tools/pb2cpp.py", line 104, in protoc
      shutil.copy(file, tmp_file)
    File "/usr/lib/python3.8/shutil.py", line 418, in copy
      copyfile(src, dst, follow_symlinks=follow_symlinks)
    File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
      with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:

  FileNotFoundError: [Errno 2] No such file or directory:
  '/home/aaa/Descargas/electroneum/external/trezor-common/protob/messages-electroneum.proto'


  Traceback (most recent call last):

    File "tools/build_protob.py", line 45, in <module>
      subprocess.check_call(exec_args)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)

  subprocess.CalledProcessError: Command '['/usr/bin/python3.8',

```

2) Getting this compiling error during the make process:

```
[ 50%] Linking CXX static library libringct_basic.a
[ 50%] Built target ringct_basic
[ 51%] Generating generated_stagenet_blocks.c
[ 51%] Generating generated_checkpoints.c
[ 51%] Generating generated_testnet_blocks.c
Scanning dependencies of target blocks
[ 51%] Building CXX object src/blocks/CMakeFiles/blocks.dir/blocks.cpp.o
[ 52%] Building C object src/blocks/CMakeFiles/blocks.dir/generated_checkpoints.c.o
cc: fatal error: Terminado (killed) signal terminated program cc1
compilation terminated.
make[2]: *** [src/blocks/CMakeFiles/blocks.dir/build.make:88: src/blocks/CMakeFiles/blocks.dir/generated_checkpoints.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3209: src/blocks/CMakeFiles/blocks.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

Does some of you know how to fix this issues?

**Comment by aicastell** [comment]
Just for reference in case this is a bug, the same process has worked fine with exactly the same set of dependencies, using v3.3.1.0 git tag.

**Comment by chrischarlesharrison** [comment]
1. We do not support Trezor.
2. This is some kind of problem with your specific computer and not a bug. Something is terminating the compilation process. It is a generic compilation error; It could be because of anything, but I cannot determine what from this error message.

**Comment by aicastell** [comment]
1. The configuration process does support it, and it seems to be broken. This is not important for me, just reporting in case you are not aware of this issue.  
2. The environment is easy to replicate. I am building on a fresh xubuntu desktop 20.04.5 LTS fully updated. The set of dependencies has been installed such as explained in the documentation. 

In both cases, I can provide the set of installed packages (dpkg -l)  or any other data that can be helpful to investigate this issue further. Is not urgent, as pre-compiled releases work really nice. Many thanks in advance.
