### ISSUE TITLE
Error: refresh failed: internal error: Overall migration failed but some balances may have migrated ok.

### ISSUE THREAD

**Issue by aicastell** [electroneum/electroneum#379]
I started using pre-compiled binary v4.0.0.1, and found this issue with an old wallet created with an old v0.11.1.0 electroneum daemon more than 4 years ago. Now I am trying to open my wallet with v4.0.0.1 and found this error:

```
Electroneum 'Aurora' (v4.0.0.1-release)
Logging to ./electroneum-wallet-cli.log
Specify wallet file name (e.g., MyWallet). If the wallet doesn't exist, it will be created.
Wallet file name (or Ctrl-C to quit): MY-CUSTOM-WALLET.etn
Wallet and key files found, loading...
Wallet password: 
Opened wallet: etn<REMOVED>
**********************************************************************
Use the "help" command to see the list of available commands.
Use "help <command>" to see a command's documentation.
**********************************************************************
Starting refresh...
Error: refresh failed: internal error: Overall migration failed but some balances may have migrated ok. Please restart the wallet and try again and contact Electroneum if the issue persists.. Blocks received: 600
Background refresh thread started

```
I check my wallet on the blockchain explorer andI see this:

`Balance ? ETN
`

but I have some ETN in that wallet.

```
[wallet etnkM7 (out of sync)]: balance 
Currently selected account: [0] Primary account Tag: (No tag assigned) 
Pre V10 Balance: 802.94, Pre V10 unlocked balance: 802.94
```

What is wrong with that? Please some help would be appreciated. Thanks!

**Comment by aicastell** [comment]
Ok, I had to resync the full blockchain again. After the re-sync  (and not before), I opened my wallet with the electroneum-wallet-cli. And some magic happened, as now I can check the explorer blockchain and proper balance is in my wallet. So this can be closed as fixed. Thanks for your work!

**Comment by chrischarlesharrison** [comment]
Glad to hear it. Thanks for your support.
