### ISSUE TITLE
Using relay_tx  method broadcasting tx_ Metadata data error :  E Failed to parse transaction from blob. Could the ETN technical team please take a look at any issues.

### ISSUE THREAD

**Issue by wenl001** [electroneum/electroneum#382]
Using relay_tx  method broadcasting tx_ Metadata data error :  E Failed to parse transaction from blob.
Could the ETN technical team please take a look at any issues.
this my code:
curl -k -X POST http://127.0.0.1:18082/json_rpc  -d '{"jsonrpc":"2.0","id":"0","method":"transfer","params":{"destinations":[{"amount":200,"address":"etnkX33bHyX9n6oGtiTwfigJZfFkQyvxahJ28tmVPWf4TVVWq6E27Dm8hg9pQ32pksWX4rHzKFXPkNRX6S7C7ezw2VvDPsN3Tn"}],"account_index":0,"priority":1,"do_not_relay":true,"get_tx_key":true,"get_tx_metadata":true,"payment_id":"0000000000000000000000000000000000000000000000000000000000000001"}}' -H 'Content-Type: application/json'   

curl -k -X POST http://127.0.0.1:18082/json_rpc   -d '{"jsonrpc":"2.0","id":"0","method":"relay_tx","params":{"hex":"...tx_metadata hex"}}' -H 'Content-Type: application/json'

**Comment by chrischarlesharrison** [comment]
We are close to releasing the final version of this project before we migrate to the electroneum smart chain (github.com/electroneum/electroneum-sc). We can have a look at this afterwards unless it becomes redundant for us to do so (for you) after you've migrated. Do you work for a company?

**Comment by wenl001** [comment]
> We are close to releasing the final version of this project before we migrate to the electroneum smart chain (github.com/electroneum/electroneum-sc). We can have a look at this afterwards unless it becomes redundant for us to do so (for you) after you've migrated. Do you work for a company?

Yes, I work at the Kucoin Exchange and am currently working on signature broadcast separation optimization, but I have found that it cannot work

**Comment by wenl001** [comment]
> We are close to releasing the final version of this project before we migrate to the electroneum smart chain (github.com/electroneum/electroneum-sc). We can have a look at this afterwards unless it becomes redundant for us to do so (for you) after you've migrated. Do you work for a company?

Are you preparing to create a new chain? and Can you help solve this problem?
If it's convenient, could you leave a contact information for Telegram.

**Comment by chrischarlesharrison** [comment]
We will be launching a new blockchain version relatively soon but the technology will be based off go-ethereum / EVM instead of Monero. This means that your current issue isn't worth sorting out if it's just an issue with using commands to  optimise your process for the current version, because the issue will disappear once you migrate your users over to the new version. We will explain everything soon. Also we have a telegram chat open already with Kucoin staff. Please ask your colleagues internally for access to this. Thanks for your patience.
