### ISSUE TITLE
Exchanges Deposit

### ISSUE THREAD

**Issue by AlbenPH** [electroneum/electroneum#383]
I would like to raise an possible bug/issue on Deposit and withdrawal on Exchanges Huobi and kucoin

kucoin- Deposit's have been in maintenance for several weeks now (No announcement)
huobi- You can't withdraw to other exchanges wallet (it says invalid wallet address) only Offical wallet address from my.electroneum is working

**Comment by chrischarlesharrison** [comment]
These issues should be fixed now
