### ISSUE TITLE
What does this have to do if I have the GUI wallet?

### ISSUE THREAD

**Issue by auroracoin** [electroneum/electroneum#386]
What does this have to do if I have the GUI wallet ver2.0.0.1? thx

**Comment by chrischarlesharrison** [comment]
you need to avoid the gui wallet and download all of the latest command line programs (v5) and read our news about migrating to the new chain. Thanks

**Comment by auroracoin** [comment]
I need a gui wallet for the new chain. :( I don't deal with coins on a phone. But where can I find info on the new chain plz?

**Comment by auroracoin** [comment]
> I need a gui wallet for the new chain. :( I don't deal with coins on a phone.
