### ISSUE TITLE
How to migrate coins

### ISSUE THREAD

**Issue by auroracoin** [electroneum/electroneum#389]
Hi how do I migrate my coins to my desktop? There are no instructions.  thank you

**Comment by tandasima** [comment]
Migrate them from where? Also, when you say desktop, what do you mean? There isn't an official desktop wallet.

**Comment by andrepatta** [comment]
Official documentation can be found at [developer.electroneum.com](https://developer.electroneum.com/).
- [How to Migrate](https://developer.electroneum.com/migration-to-smart-chain/overview)
