### ISSUE TITLE
Orphan block when syncing from blockchain.raw

### ISSUE THREAD

**Issue by pyromaticx** [electroneum/electroneum#39]
Trying to sync blockchain under ubuntu 16.04 vps. Built from source. Error in console reads

`block 5140 / 430432017-12-12 07:49:40.703               b7594940        ERROR  bcutil   src/blockchain_utilities/blockchain_import.cpp:199      Block verification failed, id = c2ee1058f801020108a2e53d4ccc36d921c3a465186dbcf163276df5bba57c49
2017-12-12 07:49:49.580         b7594940        ERROR   bcutil  src/blockchain_utilities/blockchain_import.cpp:205      Block received at sync phase was marked as orphaned
`

I have synced from blockchain.raw in past from release binary under mac and linux on another vps.

**Comment by Cyper77** [comment]
set your host date time with NTP server. and resync
