### ISSUE TITLE
after etn-legacy migrate, the etn-sc balance don't increased. 

### ISSUE THREAD

**Issue by ricksumi** [electroneum/electroneum#392]
RT . 

after one hours later, the migration don't occur on etn-sc blockchain. 

it's need approve on etn-sc chain ?

**Comment by AlbenPH** [comment]
is this a kucoin exchange wallet?

**Comment by andrepatta** [comment]
Hi @inkbx ,

We noticed your wallet has a high volume of transactions. If you are an exchange, please reach out via Telegram for priority support.

Thanks!
