### ISSUE TITLE
electroneumd.exe crashing

### ISSUE THREAD

**Issue by stefanmkd** [electroneum/electroneum#42]
I was running electroneumd.exe to sync with the network, when my pc froze and had to do a hard restart. Since than, I cannot run electroneumd.exe, it crashes right away. I was able to capture this screen with a slomo video. Any help would be greatly appreciated.

https://imgur.com/x0AvyMa

Thanks

**Comment by ghost** [comment]
me too 
https://imgur.com/K0qIz9Z

**Comment by stefanmkd** [comment]
Got it to work. Open CMD and access the folder where electroneumd is located. The command is cd "path".

Than just execute this command "start electroneumd.exe --db-salvage"

**Comment by ghost** [comment]
Nice, how did you figure it out?

**Comment by stefanmkd** [comment]
Well, I knew I had to execute the --db-salvage command, however I am not a programmer and had no idea how. Friend of mine told me it should be executed as a flag in cmd. It was googling from there

**Comment by chaosmaster3333** [comment]
Hi the salvage command didnt work
for me it still crashes
