### ISSUE TITLE
Did not receive the sms

### ISSUE THREAD

**Issue by thesunlover** [electroneum/electroneum#44]
Hello
I didn't received my sms for confirmation of mobile
the entered number is my own and the correct one
Bad Gate 502 all the time during the relaunch!
Raise your qouta in the AWS services

**Comment by RdeWilde** [comment]
Same,

**Comment by bovcan** [comment]
i got it few min ago. but dont get why you asking this here?

**Comment by thesunlover** [comment]
it worked when the traffic of the page cleared
