### ISSUE TITLE
Wallet still not found

### ISSUE THREAD

**Issue by Manza88** [electroneum/electroneum#45]
Hello,

So I got an Offline wallet back on Nov 1, 2017, at the first launch and it when I would search my wallet on the "Stats & Payment History" it kept saying "Not Found."

Then it went offline and I would periodically check just to see if it was found but no luck. Well now that Electroneum is up and running again I tried to find my wallet again, and it still i keep getting "Not Found".

Any ideas? I made two new offline wallets, but those are also not found.

**Comment by electroneumRepo** [comment]
Hi @Manza88,

Firstly, where are you seeing the "Not Found" message?
Secondly, What are you expecting to see?
