### ISSUE TITLE
Virus detected via Webroot program

### ISSUE THREAD

**Issue by benjets42** [electroneum/electroneum#49]
After downloading "win-x64-0.11.0.0.zip" then extracting the files, Webroot found potential virus in all of the extracted .exe files and deleted them. This denies my transfer of Public Wallet to Cryptopia coin exchange. I cannot proceed until this issue is corrected.

**Comment by koffienl** [comment]
Correction: "webroot denies my transfer of Public Wallet to Cryptopia coin exchange"

**Comment by cyptmatic** [comment]
The files you extract from the zip file will get flagged and quarantined by Webroot as well as "minerd.exe". To allow these files to work their magic you need to "allow" them access. You can do this by opening the Webroot application, going to the cog icon i.e. the "settings" button that is next to "PC Security". Click on the "Block/Allow Files" tab and click on "allow" for your needed files. Careful: make sure you know where each of these files comes from. Don't start allowing every file that comes through your PC while mining, for example: bitcoinminer.exe will partial some of your resources to mine to the owner's wallet. Happy mining!
