### ISSUE TITLE
compiling : boost dependency on Centos 7

### ISSUE THREAD

**Issue by NmxMilk** [electroneum/electroneum#53]
Centos 7 shipped boost lib is 1.53.

To install boost-devel 1.59 in CentOS7‏, id did the following:
$ sudo wget http://repo.enetres.net/enetres.repo -O /etc/yum.repos.d/enetres.repo
$ wget fr2.rpmfind.net/linux/Mandriva/official/2010.0/x86_64/media/main/release/lib64icu42-4.2.1-1mdv2010.0.x86_64.rpm
$ sudo rpm -ivh lib64icu42-4.2.1-1mdv2010.0.x86_64.rpm
$ sudo yum install boost-devel

**Comment by electroneumRepo** [comment]
Hi @NmxMilk,

So were you able to get the daemon / wallet working successfully?

**Comment by NmxMilk** [comment]
Not yet. I'm struggling with link undefined symbols linked to the boost library.

I'm on my way wgetting latest boost 1.66 source code and installing it with my devtool set (devtool6-gcc)

**Comment by NmxMilk** [comment]
Finally got it to compile.
cmake version 3.9.1
g++ (GCC) 7.2.0
boost 1.64.0

Struggled to get boost correctly installed. Beware if you compile boost yourself with a gcc version different from system's default. Boost build system bugged me.
It will compile with gcc 7.2 but will install with gcc 4.8 (after recompiling) !
