### ISSUE TITLE
Unable to see transferred ETN from online wallet to paper wallet.

### ISSUE THREAD

**Issue by ElectroneumGH** [electroneum/electroneum#54]
I was able to withdraw coins I bought from Cryptopia into my paper wallet much earlier on with no hassle and each time I type balance that amount reflects with no issues. Unfortunately I've been trying to transfer my ETN coins from my online wallet to that same paper wallet since Wednesday. In my online wallet it shows there has been a debit with a transaction hash, which I entered into the Electroneum blockchain explorer to confirm if that the transfer had been carried out. 
Correct me if I'm wrong but I run the electroneumd file (Mac OS), waited for it to sync and run the electroneum-wallet-cli file (via terminal) after sync was complete. Is this the right procedure? Also after doing this I received two error messages, both times I refreshed the wallet:
1. Error: refresh failed: no connection to daemon. Please make sure daemon is running.. Blocks received: 0
2. Error: wallet failed to connect to daemon: http://localhost:26968. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.

For the first error my wallet was "out of sync" and for the second one, "no daemon".
And to make matters worse the transferred coins from my online wallet are still not showing in my paper wallet.

**Comment by electroneumRepo** [comment]
Hi @ElectroneumGH 

Both the errors you are getting indicate that you do not have the daemon running.

Once the daemon is synced you can open the `electroneum-wallet-cli` but you MUST leave the `electroneumd` daemon running.

Please ensure you leave it running and then try to open your wallet again.

**Comment by ElectroneumGH** [comment]
Problem solved now. I kept refreshing the wallet each time the error came up and now the ETN coins are finally in my paper wallet. Thanks.

**Comment by electroneumRepo** [comment]
Glad you got it sorted!
