### ISSUE TITLE
how to fix reason double spend

### ISSUE THREAD

**Issue by woodhelping10** [electroneum/electroneum#57]
well i send so many times and now its giving me that message how can i fix it please.
![afx58p4cd5301](https://user-images.githubusercontent.com/32320964/34197244-3cbef0ea-e56e-11e7-92f2-41efe465ffaf.jpg)

**Comment by patillacode** [comment]
I have the exact same problem.

Once a week or so I send from an account (let's say my global account) were I get all the mining profits to my other accounts (personal accounts)

I had this issue before and it got solved by doing a `rescan_bc` but today that didn't work, I have been trying for hours now without luck, could anyone give me some advice?

Thanks.
