### ISSUE TITLE
electroneumd takes ages to sync and after syncing never stops.

### ISSUE THREAD

**Issue by SirLouen** [electroneum/electroneum#66]
I can't understand why electroneumd takes so much to sync. Actually, I've found that sometimes, blocks are being created most of the time faster that they are being synced in my computer so it's absurd.

It can take like 3 hours to sync only 3 days.

I created a service to keep it synced, but the problem is that the Harddrive it's -constantly- read/writing. 

In case that the sync process is so slow by default, then for me a solution could be some type of mechanism to sync lets say once an hour (not every second)

I don't know if to tag this as a feature request or as an issue.

Could this be possible?

**Comment by electroneumRepo** [comment]
Hi,

Can you confirm if your using a HDD or SSD.

Sync times can vary, your internet could be affecting sync times but most commonly its down to the drive that your storing the blockchain on.

SSD has much better performance than HDD

**Comment by SirLouen** [comment]
Im using an External Hdd. I'm did not want to use my ssd because since this keep growing and do too many IO actions it may affect long term performance of the drive.

But the thing is that there is no possibility of delaying the requests, is it?

**Comment by ianw1974** [comment]
It's not related to hard disk.  Even with SSD it takes for me since yesterday afternoon and still 9 days to go.  Yet other blockchains can download from 2014 to present day much quicker.  All I can think is the electroneum network infrastructure is poor in some respects, otherwise it would download quicker.  And it's not my network either, as I downloaded other blockchains on the same machine far quicker.

**Comment by Necromurloc** [comment]
i have 3 days trying to sync my daemon with the blockchain and still are on block "Synced 65779/14988"

**Comment by gvirus911** [comment]
42299 -> 307508 [Your node is 265209 blocks (368 days) behind]
all day SYNCHRONIZATION started why is that ?
i can't mining
