### ISSUE TITLE
ETN not received from Offline wallet

### ISSUE THREAD

**Issue by ishubhamgoyal** [electroneum/electroneum#67]
Before 4-5 days I transfer 1612 ETN from offline wallet to online wallet But I didn't  receive any ETN yet. And when I am open my app it shows unable to update your balance and transaction. What should I do plz help me!! When I sync blockchain on the server to check my transaction is done or not, It shows my 1612 ETN goes out from my offline wallet.
![screenshot_2017-12-23-15-14-09-494_com electroneum mobile](https://user-images.githubusercontent.com/34095389/34326646-432a8922-e8d8-11e7-935f-c742cd340f0c.png)

**Comment by ZielarSRC** [comment]
What i must say? I have 8600 ETN on this same wallet, and can't withdraw them to any other. I can't take them locally, becouse we don't have keys to this wallets. GET BACK MONEY ELECTROTHIEFT'S!

**Comment by ishubhamgoyal** [comment]
So what should we do right now. WAIT??

**Comment by ZielarSRC** [comment]
Only waiting is left. If by the end of the year I do not get a response from the support - at the beginning of the year I take legal steps, because it will be nothing but one big shaft and cheat, and I will not give it for $ 800

**Comment by igortsev** [comment]
same problem

**Comment by agario654** [comment]
same issue. Import from offline wallet still in processing status for a week.

**Comment by agario654** [comment]
Just figured it out. Run the daemon to download all the blocks and refresh the offline wallet. The processing transactions are expired and back to the offline wallet. you can move it from there. 

Link to download:
https://github.com/electroneum/electroneum/releases

Good luck
