### ISSUE TITLE
Bypass wallet seed language in cli new wallet?

### ISSUE THREAD

**Issue by wasntafairfight** [electroneum/electroneum#68]
Is it possible to bypass the "list of available languages for your wallet's seed" part of creating a new wallet via cli?

I'm trying to create new addresses automatically as needed.

**Comment by crazy-logic** [comment]
have a look at using the switch/option '--mnemonic-language', and have a look at this thread. https://github.com/monero-project/monero/issues/1151

**Comment by wasntafairfight** [comment]
Thank you!

**Comment by crazy-logic** [comment]
You're welcome - feel free to mark this issue as closed once you've succeeded.
