### ISSUE TITLE
Build error Ubuntu 16.04

### ISSUE THREAD

**Issue by t78Linux** [electroneum/electroneum#7]
Recent github snapshot can not be built on my machine running 16.04 with all the dependencies installed in the README.
This is my error after issuing "make":

`[ 57%] Building CXX object tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o
/home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp: In function ‘bool {anonymous}::lift_up_difficulty(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&, std::vector<long unsigned int>&, std::vector<long unsigned int>&, test_generator&, size_t, cryptonote::block, const cryptonote::account_base&)’:
/home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp:48:85: error: ‘DIFFICULTY_TARGET_V1’ was not declared in this scope
       difficulty_type diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                     ^
/home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp: In member function ‘bool gen_block_invalid_nonce::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const’:
/home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp:178:81: error: ‘DIFFICULTY_TARGET_V1’ was not declared in this scope
   difficulty_type diffic = next_difficulty(timestamps, commulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                 ^
In file included from /home/holger/Documents/electroneum-master/src/cryptonote_basic/cryptonote_basic.h:47:0,
                 from /home/holger/Documents/electroneum-master/src/cryptonote_basic/account.h:33,
                 from /home/holger/Documents/electroneum-master/src/cryptonote_basic/account_boost_serialization.h:33,
                 from /home/holger/Documents/electroneum-master/tests/core_tests/chaingen.h:47,
                 from /home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp:31:
/home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp: In member function ‘bool gen_block_unlock_time_is_timestamp_in_future::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const’:
/home/holger/Documents/electroneum-master/src/cryptonote_config.h:85:57: error: ‘DIFFICULTY_TARGET_V1’ was not declared in this scope
 #define DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN             DIFFICULTY_TARGET_V1 //just alias; used by tests
                                                         ^
/home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp:267:87: note: in expansion of macro ‘DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN’
   miner_tx.unlock_time = blk_0.timestamp + 3 * CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW * DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN;
                                                                                       ^
/home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp: In member function ‘bool gen_block_invalid_binary_format::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const’:
/home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp:575:67: error: ‘DIFFICULTY_TARGET_V1’ was not declared in this scope
     diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                   ^
/home/holger/Documents/electroneum-master/tests/core_tests/block_validation.cpp:590:65: error: ‘DIFFICULTY_TARGET_V1’ was not declared in this scope
   diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                 ^
tests/core_tests/CMakeFiles/coretests.dir/build.make:86: recipe for target 'tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o' failed
make[3]: *** [tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o] Error 1
make[3]: Leaving directory '/home/holger/Documents/electroneum-master/build/release'
CMakeFiles/Makefile2:2157: recipe for target 'tests/core_tests/CMakeFiles/coretests.dir/all' failed
make[2]: *** [tests/core_tests/CMakeFiles/coretests.dir/all] Error 2
make[2]: Leaving directory '/home/holger/Documents/electroneum-master/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/holger/Documents/electroneum-master/build/release'
Makefile:62: recipe for target 'release-all' failed
make: *** [release-all] Error 2
`

**Comment by t78Linux** [comment]
Update: make release-static works
Info: Latest snapshot not retrieved via git, but from downloading the master.zip through github

**Comment by jankamon** [comment]
The same issue here on 56%. I tried to re-clone and make release. It worked but electroneumd won't start.

`[ 56%] Building CXX object tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o
/root/electroneum/tests/core_tests/block_validation.cpp: In function 'bool {anonymous}::lift_up_difficulty(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&, std::vector<long unsigned int>&, std::vector<long unsigned int>&, test_generator&, size_t, cryptonote::block, const cryptonote::account_base&)':
/root/electroneum/tests/core_tests/block_validation.cpp:48:85: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
 _type diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_
                                                                     ^
/root/electroneum/tests/core_tests/block_validation.cpp: In member function 'bool gen_block_invalid_nonce::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const':
/root/electroneum/tests/core_tests/block_validation.cpp:178:81: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
 _type diffic = next_difficulty(timestamps, commulative_difficulties,DIFFICULTY_
                                                                     ^
In file included from /root/electroneum/src/cryptonote_basic/cryptonote_basic.h:47:0,
                 from /root/electroneum/src/cryptonote_basic/account.h:33,
                 from /root/electroneum/src/cryptonote_basic/account_boost_serialization.h:33,
                 from /root/electroneum/tests/core_tests/chaingen.h:47,
                 from /root/electroneum/tests/core_tests/block_validation.cpp:3 :
/root/electroneum/tests/core_tests/block_validation.cpp: In member function 'bool gen_block_unlock_time_is_timestamp_in_future::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const':
/root/electroneum/src/cryptonote_config.h:85:57: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
 #define DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN             DIFFICULTY_TARGET_V1 //
                                                         ^
/root/electroneum/tests/core_tests/block_validation.cpp:267:87: note: in expansion of macro 'DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN'
 time = blk_0.timestamp + 3 * CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW * DIFFICULTY_
                                                                     ^
/root/electroneum/tests/core_tests/block_validation.cpp: In member function 'bool gen_block_invalid_binary_format::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const':
/root/electroneum/tests/core_tests/block_validation.cpp:575:67: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
     diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TA
                                                                   ^
/root/electroneum/tests/core_tests/block_validation.cpp:590:65: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
   diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARG
                                                                 ^
tests/core_tests/CMakeFiles/coretests.dir/build.make:86: recipe for target 'tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o' failed
make[3]: *** [tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o] Error 1
make[3]: Leaving directory '/root/electroneum/build/release'
CMakeFiles/Makefile2:2157: recipe for target 'tests/core_tests/CMakeFiles/coretests.dir/all' failed
make[2]: *** [tests/core_tests/CMakeFiles/coretests.dir/all] Error 2
make[2]: Leaving directory '/root/electroneum/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/electroneum/build/release'
Makefile:62: recipe for target 'release-all' failed
make: *** [release-all] Error 2
`

**Comment by t78Linux** [comment]
If I read it correctly, you built the binaries being root, therefore the binaries will be owned by root and only executable by root as I suppose.
Build the binaries not as root !

**Comment by jankamon** [comment]
Finally I got it. After re-clone and make-release I had problems with DNS, that is why electroneumd did not work.

**Comment by electroneumRepo** [comment]
Glad you got it sorted.

I'll now close this issue

**Comment by t78Linux** [comment]
"Make" still does not work, only "make release-static". This is by far not solved as it should work with a dynamically linked binary too.
