### ISSUE TITLE
build failed, internal compiler error in http_auth.cpp.o

### ISSUE THREAD

**Issue by vekaputra** [electroneum/electroneum#70]
i setup a 16.04 ubuntu server with all dependency, after running `make release-static` i got this error.

mkdir -p build/release
cd build/release && cmake -D STATIC=ON -D ARCH="x86-64" -D BUILD_64=ON -D CMAKE_BUILD_TYPE=release ../.. && make
-- Building without build tag
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled
-- Found miniupnpc API version 10
-- Using miniupnpc from local source tree for static build
-- Looking for libunbound
-- Using 64-bit LMDB from source tree
-- Building on x86_64 for x86-64
-- AES support enabled
-- Found Boost Version: 105800
-- Could NOT find Readline (missing:  Readline_INCLUDE_DIR Readline_LIBRARY)
-- Could not find GNU readline library so building without readline support
-- Found Git: /usr/bin/git
-- Configuring done
-- Generating done
-- Build files have been written to: /root/electroneum/build/release
make[1]: Entering directory '/root/electroneum/build/release'
make[2]: Entering directory '/root/electroneum/build/release'
make[3]: Entering directory '/root/electroneum/build/release'
make[3]: Leaving directory '/root/electroneum/build/release'
[  1%] Built target version
make[3]: Entering directory '/root/electroneum/build/release'
make[3]: Leaving directory '/root/electroneum/build/release'
[  6%] Built target libminiupnpc-static
make[3]: Entering directory '/root/electroneum/build/release'
make[3]: Leaving directory '/root/electroneum/build/release'
[ 32%] Built target unbound
make[3]: Entering directory '/root/electroneum/build/release'
make[3]: Leaving directory '/root/electroneum/build/release'
[ 33%] Built target lmdb
make[3]: Entering directory '/root/electroneum/build/release'
make[3]: Leaving directory '/root/electroneum/build/release'
[ 34%] Built target easylogging
make[3]: Entering directory '/root/electroneum/build/release'
make[3]: Leaving directory '/root/electroneum/build/release'
[ 40%] Built target obj_cncrypto
make[3]: Entering directory '/root/electroneum/build/release'
make[3]: Leaving directory '/root/electroneum/build/release'
[ 40%] Built target cncrypto
make[3]: Entering directory '/root/electroneum/build/release'
make[3]: Leaving directory '/root/electroneum/build/release'
make[3]: Entering directory '/root/electroneum/build/release'
[ 41%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
contrib/epee/src/CMakeFiles/epee.dir/build.make:86: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o' failed
make[3]: *** [contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o] Error 4
make[3]: Leaving directory '/root/electroneum/build/release'
CMakeFiles/Makefile2:456: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/all' failed
make[2]: *** [contrib/epee/src/CMakeFiles/epee.dir/all] Error 2
make[2]: Leaving directory '/root/electroneum/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/electroneum/build/release'
Makefile:66: recipe for target 'release-static' failed
make: *** [release-static] Error 2

note: i already try to build this before, so all files before http_auth.cpp.o is already built, and the `make` command skips it.

**Comment by electroneumRepo** [comment]
Hi,

Could you confirm that you installed all dependencies.
Can you also confirm your system specs? (i.e what CPU/RAM do you have)

**Comment by vekaputra** [comment]
i'm using 512MB VPS / 1 CPU (didn't know what it is) from digital ocean, ubuntu 16.04. i'm trying to setup remote node btw, is it better to build / use compiled binary?.

**Comment by electroneumRepo** [comment]
Hi,

Yes I would recommend that you use the pre-compiled binaries.

I would say that your getting that error because you only have a small amount of RAM.

**Comment by dtison** [comment]
Try adding some swap.  I couldn't get it to compile with less than 2 GB combined total RAM + swap.
