### ISSUE TITLE
Issue with withdrawal from online wallet

### ISSUE THREAD

**Issue by ZielarSRC** [electroneum/electroneum#72]
I have a huge problem! I have an Online wallet on my.electroneum.com. I have over 8,000 ETNs on the fence and I wanted to make a withdrawal to the stock exchange, however, withdrawal attempts although they pass successfully - after a while they turn into FAILED. I have a frozen sum, which I can not access for reasons unknown to me. How should I withdraw it?!?!?!?!

**Comment by mobileoverlord** [comment]
I am experiencing issues in sending ETN from the online wallet to other wallets. The site is stalled and always reports status of Failed.

**Comment by GoZippy** [comment]
similar but not related - earlier movements from online wallet (mobile) to cryptopia (1000 coins) status shows failed or pending - coins ended up at exchange a few hours later but still show pending in the mobile app and online wallet. I have not exported to cli to verify. Coins were mined to paper wallet imported to cli locally then sent to the mobile app online wallet - then to cryptopia all transactions were good until transfer to cryptopia - as I said I think the coins made it there but still show pending on the wallet and mobile app. not sure how to fix that as I do not see any place for the code on the wallet app or website scripts...
