### ISSUE TITLE
Possible conflicts when running monerod and electroneumd on the same node

### ISSUE THREAD

**Issue by zigglzworth** [electroneum/electroneum#75]
Running monerod and electroneumd on the same node seems to cause a slow down in sync speed (for monerod)

Are there any conflicts to consider when running monerod and electroneumd on the same node?

**Comment by electroneumRepo** [comment]
Hi,

This will be down to the fact that both daemons are sharing your resources.

Ideally you should run the daemon's on their own server to avoid slow sync times.

I hope this helps.

**Comment by zigglzworth** [comment]
Thanks
