### ISSUE TITLE
RPC: getlastblockheader does not return reward in smallest coin units

### ISSUE THREAD

**Issue by ghost** [electroneum/electroneum#77]
I noticed that the RPC method `getlastblockheader` does not return the reward in smallest coin units. Instead you have to divide it by 100 to convert to ETN. I haven't seen any other CryptoNote currency with this behavior yet.

See also `src/cryptonote_config.h`:
// COIN - number of smallest units in one coin
#define COIN                                            ((uint64_t)1000000000000) // pow(10, 12)

### Sample
`curl -X POST http://localhost:26968/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getlastblockheader"}' -H 'Content-Type: application/json'`

```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "block_header": {
      "block_size": 37310,
      "depth": 0,
      "difficulty": 12214520990,
      "hash": "dd72a5fd82ca2307905956a7adce3ca84abc00e73fd1a0c48085b1d11c69fc2d",
      "height": 88628,
      "major_version": 1,
      "minor_version": 1,
      "nonce": 105715,
      "num_txes": 12,
      "orphan_status": false,
      "prev_hash": "b19e913bea256a5a61667b9934d1c656ee47986009722a5ef9be5eb9270398c2",
      "reward": 734555,
      "timestamp": 1514542313
    },
    "status": "OK"
  }
}
```

**Comment by oliverw** [comment]
This also applies to getblockheaderbyheight and getblockheaderbyhash

**Comment by andyaldridge** [comment]
`reward` is an integer that represents the atomic units. A division by 100 is needed to convert to normal units.

**Comment by ghost** [comment]
But the smallest atomic unit is defined as 10^-12 (see `src/cryptonote_config.h`).
Either the definition is wrong or the RPC implementation.

**Comment by ThrownLemon** [comment]
Yep something is wrong here.
