### ISSUE TITLE
Error: Mining did not start -- BUSY

### ISSUE THREAD

**Issue by tlangdon123** [electroneum/electroneum#8]
Can anyone help with this?
I am using an iMac and I am getting this error when I enter in start_mining (wallet) 2 or 4.
I want to start mining ETN but this is really discouraging me from doing so.

Any help is appreciated.

**Comment by tlangdon123** [comment]
https://github.com/electroneum/electroneum/issues/6
this solved my problem

**Comment by electroneumRepo** [comment]
Glad you got it sorted.
