### ISSUE TITLE
"Failed to open specified PID file for writing"  when starting daemon on same server as monero

### ISSUE THREAD

**Issue by ethernet802** [electroneum/electroneum#80]
can you look at:

 src/daemonizer/posix_fork.cpp:26        Failed to open specified PID file for writing

`output += "/bitmonero.daemon.stdout.stderr";`

this conflicts when running monero daemon and electroneum daemon on the same server

changing it to:

`output += "/electroneum.daemon.stdout.stderr";`

seems to work ok.

**Comment by electroneumRepo** [comment]
#200
