### ISSUE TITLE
Import of Offline paper wallet 4 days still processing

### ISSUE THREAD

**Issue by igortsev** [electroneum/electroneum#81]
I step buy step import all ETN via Import Form Offline paper wallet.
I did that before and all works fine. But right now i have 5 imports to processing.

Last import i did 26 december and now status processing here:
https://my.electroneum.com/

Resent transaction

**Comment by thevena** [comment]
I have the same issue...since the same date. No response from, support yet, I take it they are still in Holiday mode.

**Comment by davinhun** [comment]
I have the same issue too

**Comment by unlcky** [comment]
Same issue from the same date. If this is due to a holiday break... Why is the success of transactions dependent on people being at work or not?

**Comment by agario654** [comment]
Same issue here. Two import from the offline wallet at 28th and 29th Dec and still processing status. No response from the team!

**Comment by unlcky** [comment]
How embarrassing. Just pulled my money from this shitcoin based on this experience. US bank ACH is faster than this.

**Comment by thevena** [comment]
so I went on the Telegram...the one with 30k plus users...and an admin said they are working on it.

**Comment by agario654** [comment]
Just run the daemon to download all the blocks and refresh the offline wallet. The processing transactions are expired and back to the offline wallet. you can move it from there. 

Link to download:
https://github.com/electroneum/electroneum/releases

Good luck
