### ISSUE TITLE
How to change cli wallet staring block

### ISSUE THREAD

**Issue by nasopraso** [electroneum/electroneum#83]
Hi,

Could you tell me how to change the wallet starting block? It's very annoying

Every time my wallet start to sync from block  65000...now block is 95000...I must wait a lot of time!!

I want to set my wallet to sync from my last sync

**Comment by electroneumRepo** [comment]
Hi,

When you close a wallet. It stores the current height that the wallet is up-to-date on.

Next time you open it, It'll only sync from that height.

The only way it wouldn't do this is if you were to not exit the wallet safely.

**Comment by nasopraso** [comment]
how to logout safely?

**Comment by bovcan** [comment]
type "exit"
