### ISSUE TITLE
ISSUE SYNCING

### ISSUE THREAD

**Issue by pjp21** [electroneum/electroneum#84]
Hello I am using a mac and am having trouble syncing to the network. I get this error:

> Bus error: 10
> logout
> 
> [Process completed]

I tried deleting the zip files and redownloading them but this did not work. Thank you in advance for any help or advice!

**Comment by bet0x** [comment]
Something that you can do is go to https://etn.electromineros.com/, under `Descargar Raw Blockchain para electroneum-blockchain-import (4GB aprox)` you download the raw blockchain (daily update) and run electroneum-blockchain-import with the argument pointing to the location of the raw blockchain.
