### ISSUE TITLE
Files for Mac Damaged?

### ISSUE THREAD

**Issue by celaineis** [electroneum/electroneum#85]
When I download the app for Mac, it says the files are damaged and should be moved to trash....

**Comment by truth3** [comment]
@celaineis It installed OK and has been running well for me since launch.

**Comment by celaineis** [comment]
@truth3 hmmm what exactly did you do to open and install it? I'm totally unfamiliar with all this and learning as I go. I was just clicking it to open it (and then having to give my computer permission to open the files.) I was just double clicking to open them. Is there some other way that's better?

**Comment by truth3** [comment]
@celaineis Once you download the folder, follow the steps below.

1. Open the folder and right click on electroneumd, and select "Get Info"
![screen shot 2018-01-04 at 2 59 49 pm](https://user-images.githubusercontent.com/7986768/34581910-21f1bf1a-f160-11e7-830c-bb619f7d1c68.png)


2. Then copy the path to the file like I show in the highlighted part of the screen shot
![screen shot 2018-01-04 at 3 00 06 pm](https://user-images.githubusercontent.com/7986768/34581930-355c844a-f160-11e7-99df-349f6099f2b4.png)

3. Open your terminal window and paste what you just copied. At the end of the string, just type "electroneumd" and then hit enter.

![screen shot 2018-01-04 at 3 00 26 pm](https://user-images.githubusercontent.com/7986768/34581950-4f9e3c68-f160-11e7-80c6-1cc9a272fc95.png)


That should do it

**Comment by celaineis** [comment]
Ill give it a shot! Thank you for the help :) 👍

**Comment by celaineis** [comment]
@truth3 It doesn't like me.

Here's what I get when I do "get info" 
<img width="263" alt="screen shot 2018-01-04 at 3 13 49 pm" src="https://user-images.githubusercontent.com/35113812/34582480-ef12c7a4-f161-11e7-92b6-713dc18f6b3f.png">

And here's what I get with the next step... Tried it two different ways:
<img width="568" alt="screen shot 2018-01-04 at 3 15 03 pm" src="https://user-images.githubusercontent.com/35113812/34582509-1087f38c-f162-11e7-9627-a6b819b0323a.png">

Now granted I could still be doing it wrong....

**Comment by truth3** [comment]
@celaineis rename the downloaded folder something simple, like "electroneum" and then try again

**Comment by celaineis** [comment]
@truth3 You're so cool! Haha It worked, thank you!!

**Comment by celaineis** [comment]
@truth3 Now to figure out what the hell I'm doing going forward. That was just getting the damn thing opened lol

**Comment by truth3** [comment]
@celaineis You need to do the same thing for "electroneum-wallet-cli" in another terminal window. Follow the prompts to setup your wallet and wait for the sync to happen. After the sync is complete then type in this command.

`start_mining 2`

**Comment by celaineis** [comment]
@truth3 Should I wait for the first one to stop? Or can I do them both at the same time? Thank you again for your quick help!

**Comment by celaineis** [comment]
@truth3 also any idea why the electroneum website doesn't say to do do it for: electroneum-wallet-cli  just for the electroneumd?

<img width="1139" alt="screen shot 2018-01-04 at 4 10 33 pm" src="https://user-images.githubusercontent.com/35113812/34584545-334cca52-f16a-11e7-91ee-e5f96b3a3cae.png">

**Comment by truth3** [comment]
@celaineis Its actually the last bullet point where they talk about using the wallet-cli to create the wallet. I figured I was already working on the command line, I would rather stay using that to make the wallet. 

In regards to mining, you need to wait for the sync to complete before you can start the miner.

**Comment by truth3** [comment]
@electroneumRepo I think this could likely be closed, as there isn't anything to fix.
