### ISSUE TITLE
Need faster synchronization with network

### ISSUE THREAD

**Issue by asif-shaikh** [electroneum/electroneum#86]
Hi Team,

It takes to longer to download all the blocks from the network through command-line to **C:\ProgramData\electroneum**.
It is good if a zip file of this directory is provided every week, then the synchronization will not take more than an hour for anyone.

_Friends, can anyone send me a zip of your folder?_

Thanks in advance.

**Comment by electroneumRepo** [comment]
Hi,

You can use the raw blockchain download and import it using the electroneum-blockchain-import executable.

We try to update the raw blockchain download on a regular basis. The currently available version was updated around 1 week ago.

**Comment by bet0x** [comment]
if it helps, we have a daily dump of the blockchain at https://etn.electromineros.com/ you will see a link wich says `Descargar Raw Blockchain para electroneum-blockchain-import (4GB aprox)`

**Comment by j4y-k** [comment]
Imported raw blockchain from Dec 29/17 (https://github.com/electroneum/electroneum/releases).. taking days to sync the blockchain on Linux.. please fix, and provide a recent blockchain file
