### ISSUE TITLE
Transaction lost?

### ISSUE THREAD

**Issue by inb0x** [electroneum/electroneum#88]
I withdrew from cryptopia, and can see the txid at https://blockexplorer.electroneum.com/search?value=2478726e57fd4f4eb5274a070b1c62c77acec15c0597ad9f879a5de8ee6372de

I saw the transaction in the mem pool in my wallet, However, it does not show up in there anymore!  Balance shows 0 and no sign of any transaction.

My daemon is synced, and I even tried a remote node as well.

I have tried rescan_bc and rescan_spent to no avail.

show_transfer and show_transfers does not see anything.

**Comment by ChrisCharrison** [comment]
Could have been returned to the exchange after it sat in the mempool for 24 hours. Send the exchange a message and let us know how you get on.

**Comment by electroneumRepo** [comment]
Hi,

Can you do set refresh-from-block-height 0 and then do rescan_bc
