### ISSUE TITLE
What is the purpose of the 'etn' prefix to wallet address

### ISSUE THREAD

**Issue by zigglzworth** [electroneum/electroneum#89]
What is the purpose of the 'etn' prefix to wallet address? Is it possible to generate a wallet address without the 'etn' prefix? 

Also, where in the codebase was this change made ?

**Comment by dtison** [comment]
The etn that appears happens as a result of the base58 encoding of the account address.

You can find this in the function
```
  std::string get_account_address_as_str(
      bool testnet
    , account_public_address const & adr
    )
```
and in the processing that takes place within the base58 encoder.

**src/cryptonote_basic/cryptonote_basic_impl.cpp**

The internals of of the base58 encoder are generating **etn** as part of the address.
