### ISSUE TITLE
Error out during make

### ISSUE THREAD

**Issue by kinkay716** [electroneum/electroneum#90]
Hello,  I've installed all the dependences listed and ran 'make' but getting the following error:

make[3]: Entering directory '/root/electroneum/build/release'
[ 12%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
contrib/epee/src/CMakeFiles/epee.dir/build.make:86: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o' failed
make[3]: *** [contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o] Error 4
make[3]: Leaving directory '/root/electroneum/build/release'
CMakeFiles/Makefile2:340: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/all' failed
make[2]: *** [contrib/epee/src/CMakeFiles/epee.dir/all] Error 2
make[2]: Leaving directory '/root/electroneum/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/electroneum/build/release'
Makefile:62: recipe for target 'release-all' failed
make: *** [release-all] Error 2

Any ideas would be most helpful.

Thanks!

**Comment by electroneumRepo** [comment]
Hi,

Try `make release-static`

**Comment by kinkay716** [comment]
Still no luck.  Here is the output I'm seeing: 

mkdir -p build/release
cd build/release && cmake -D STATIC=ON -D ARCH="x86-64" -D BUILD_64=ON -D CMAKE_BUILD_TYPE=release ../.. && make
-- Building without build tag
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled
-- Found miniupnpc API version 10
-- Using miniupnpc from local source tree for static build
-- Looking for libunbound
-- Using 64-bit LMDB from source tree
-- Building on x86_64 for x86-64
-- AES support enabled
-- Found Boost Version: 105800
-- Could NOT find Readline (missing:  Readline_INCLUDE_DIR Readline_LIBRARY) 
-- Could not find GNU readline library so building without readline support
-- Found Git: /usr/bin/git
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lmoy/electroneum/build/release
make[1]: Entering directory '/home/lmoy/electroneum/build/release'
make[2]: Entering directory '/home/lmoy/electroneum/build/release'
make[3]: Entering directory '/home/lmoy/electroneum/build/release'
make[3]: Leaving directory '/home/lmoy/electroneum/build/release'
[ 12%] Built target version
make[3]: Entering directory '/home/lmoy/electroneum/build/release'
make[3]: Leaving directory '/home/lmoy/electroneum/build/release'
[ 12%] Built target libminiupnpc-static
make[3]: Entering directory '/home/lmoy/electroneum/build/release'
make[3]: Leaving directory '/home/lmoy/electroneum/build/release'
[ 12%] Built target unbound
make[3]: Entering directory '/home/lmoy/electroneum/build/release'
make[3]: Leaving directory '/home/lmoy/electroneum/build/release'
[ 12%] Built target lmdb
make[3]: Entering directory '/home/lmoy/electroneum/build/release'
make[3]: Leaving directory '/home/lmoy/electroneum/build/release'
[ 12%] Built target easylogging
make[3]: Entering directory '/home/lmoy/electroneum/build/release'
make[3]: Leaving directory '/home/lmoy/electroneum/build/release'
[ 12%] Built target obj_cncrypto
make[3]: Entering directory '/home/lmoy/electroneum/build/release'
make[3]: Leaving directory '/home/lmoy/electroneum/build/release'
[ 12%] Built target cncrypto
make[3]: Entering directory '/home/lmoy/electroneum/build/release'
make[3]: Leaving directory '/home/lmoy/electroneum/build/release'
make[3]: Entering directory '/home/lmoy/electroneum/build/release'
[ 12%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
contrib/epee/src/CMakeFiles/epee.dir/build.make:86: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o' failed
make[3]: *** [contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o] Error 4
make[3]: Leaving directory '/home/lmoy/electroneum/build/release'
CMakeFiles/Makefile2:456: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/all' failed
make[2]: *** [contrib/epee/src/CMakeFiles/epee.dir/all] Error 2
make[2]: Leaving directory '/home/lmoy/electroneum/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lmoy/electroneum/build/release'
Makefile:66: recipe for target 'release-static' failed
make: *** [release-static] Error 2

**Comment by electroneumRepo** [comment]
Hi,

Can you confirm the specs of the machine you are trying to build on?

The build process can be quite CPU / Memory intensive.

**Comment by kinkay716** [comment]
I bumped up my droplet on Digital Ocean and that fixed it.  I was on a 1GB memory droplet and bumped up to 3GB.
