### ISSUE TITLE
Lost transacton to Cryptopia 

### ISSUE THREAD

**Issue by Josh5899** [electroneum/electroneum#97]
I sent from my wallet to Cryptopia 2 days ago and it has not arrived I checked the block chain and there is 3074 confirmations..but still not pending and does not show any amount. 

Tx public key: 117e17c19b8bb2bcb1c5acf70d2d903188a54b93beac70807d63245691ac1309
Payment id: 87218b6292d3316ba56dd1c6cd4c7a1c2ca802ac6458c7418eefbd324fefd50f

Please fix the transaction

**Comment by Josh5899** [comment]
Payment ID: 87218b6292d3316ba56dd1c6cd4c7a1c2ca802ac6458c7418eefbd324fefd50f

**Comment by TriJetScud** [comment]
Asking the devs to fix the transaction related to a third party is next to impossible here.

You'll need to take up the issue with Cryptotopia, not with the developers here as a github issue. Only cryptotopia holds the keys to that wallet and only they can help you.

**Comment by jpeter12** [comment]
Cryptopia are having problems accepting ETN at the moment. Check their coin info page and scroll down to ETN. Contact Cryptopia support and hope to hear back from them within next month :(
